### ISSUE TITLE
[Feature Request]: Restart download on re-connection to WiFi/check for partially downloaded zip

### ISSUE THREAD

**Issue by Ju1-js** [an-anime-team/an-anime-game-launcher#100]
If there is an interruption during game download in launcher (e.g. after system shut off or launcher crash).
Current situation:

- Download cannot be resumed from where it left off.
- Partially completed zip file may occupy too much space, requiring manual deletion to start a new download.

Proposed solution:

- Launcher feature to restart download from where it left off when internet connection is restored.
- Check for partially downloaded zip files when download button is clicked (After the launcher is restarted).

_A pause download function could also be nice._

**Comment by Mar0xy** [comment]
The launcher resumes the download nowadays if it gets interrupted and when you open it back up there is still no pause button but the pause button equivalent to this is literally just closing launcher and then reopening it if you want to continue
