### ISSUE TITLE
Crash on news screen In game

### ISSUE THREAD

**Issue by Saskya99** [an-anime-team/an-anime-game-launcher#102]
Fresh install on Fedora 37 with last flatpak
Crash of ZFGameBrowser.exe  when I click on the event menu and wine freeze
![Screenshot_20230317_082325](https://user-images.githubusercontent.com/13392574/225839404-3219e903-fec5-492f-a219-ff811bdc60a9.png)
[backtrace(details of error).txt](https://github.com/an-anime-team/an-anime-game-launcher/files/10998850/backtrace.details.of.error.txt)
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/10998851/debug.log)

**Comment by Mar0xy** [comment]
This is a normal expected behaviour as Wine has issues with loading the Web Page URLs in the games in-game browser.
