### ISSUE TITLE
[Question]: How to use a pre-existing installation

### ISSUE THREAD

**Issue by NaiveInvestigator** [an-anime-team/an-anime-game-launcher#107]
I have already downloaded the anime game in windows and played for some time. how i can play it on linux using those files. I couldn't find any way to do it.

**Comment by icedgreen** [comment]
Open the config file from the hamburger menu towards the top of the launcher. In here you can change the "game" path to the directory where your game is stored (specifically the folder with the Genshin exe). Then restart the launcher and it should detect your game.

**Comment by NaufalF22** [comment]
How to use? i try it but get error game diff and launcher doesnt exist

**Comment by hansjohn** [comment]
> 

the same as you.
