### ISSUE TITLE
New launcher keeps telling me to download wine

### ISSUE THREAD

**Issue by Sorual** [an-anime-team/an-anime-game-launcher#108]
![Screenshot_20230321_215603](https://user-images.githubusercontent.com/16091816/226781948-3c172017-bd6d-4005-915c-33fb7c9d3b77.png)
Ever since updating to the new version of the launcher, the launch button has been replaced with a "download wine" button. I already have wine installed. But just to be sure, I went into the settings and downloaded the newest version of wine GE Proton.
![Screenshot_20230321_215744](https://user-images.githubusercontent.com/16091816/226782154-a412b19b-fb13-4113-a6cf-ca8164595b1a.png)

Clicking on the "download wine" button does absolutely nothing.

**Comment by lolololer1337228** [comment]
Same for me. Already have Wine installed, and the launcher even sees it, but clicking on "download Wine" does nothing
I'm on Arch, latest Wine-GE-Proton
