### ISSUE TITLE
[Issue]: in game browser not working

### ISSUE THREAD

**Issue by ch604** [an-anime-team/an-anime-game-launcher#11]
### Distro

Steamos 3.4

### Installation Type

Flatpak

### Describe the issue

When attempting to sign up for an account in game, the browser will not open

### Reproduction Steps

Flatpak install with all default settings and versions

**Comment by ppwwyyxx** [comment]
Some user claims that this patch of wine: https://www.winehq.org/pipermail/wine-devel/2021-May/187791.html can fix the in-game browser.

**Comment by Mar0xy** [comment]
exactly as said above this is an upsteam WINE issue and the only way to get around this is to use the browser for tasks like that as a flatpak/deck user.
