### ISSUE TITLE
Glowing textures and low fps

### ISSUE THREAD

**Issue by fwflunky** [an-anime-team/an-anime-game-launcher#114]
**Everything was fine before**. Now after reinstalling the game it became impossible to play
Tried using GE-Proton, Wine-GE-Proton, Lutris - no changes
Tried playing on amdgpu (integrated) and nvidia gpu - same, no changes <br/>
![изображение](https://user-images.githubusercontent.com/38854160/227593558-9fa1888f-60d4-4aba-804d-a281de614c64.png)
![изображение](https://user-images.githubusercontent.com/38854160/227593587-51e33a69-4163-4de2-adba-05dc18324c72.png)
![изображение](https://user-images.githubusercontent.com/38854160/227593602-89481a85-b95b-434d-8a3a-c0e184c51716.png)
![изображение](https://user-images.githubusercontent.com/38854160/227593625-e8a70c60-6a48-45b0-9702-73439591399c.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594126-70ac6471-aaca-4f9e-aeae-417f8ab1c1e2.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594331-f5dd92e3-6f28-41a9-815e-2c52f2b85a2d.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594346-9b65e1ca-1c10-4f58-aa59-108236e6def5.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594381-6f5eb77a-8bd6-4a99-b58f-6a0d0e6c4d38.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594592-57e4dfee-11f8-46b6-951a-932707cc7671.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594622-dacc44b2-9c4c-4431-945d-16527004e601.png)
![изображение](https://user-images.githubusercontent.com/38854160/227594668-16b1f7b8-523b-41ba-bc35-014f1239ef4f.png)

**Comment by fwflunky** [comment]
[latest.log](https://github.com/an-anime-team/an-anime-game-launcher/files/11064806/latest.log)

**Comment by fwflunky** [comment]
![изображение](https://user-images.githubusercontent.com/38854160/227596583-9bb52001-9139-436a-8131-ae8b2cbbdc1d.png)

**Comment by krypt0nn** [comment]
1) Проблема, собственно, в том, что не был применен DXVK. Попробуй разные версии в настройках, одна из них заработает

2) Друг.... Мы эту версию лаунчера уже как пол года забросили. Обновись, не знаю

**Comment by fwflunky** [comment]
Тоже самое с новой версией

https://user-images.githubusercontent.com/38854160/227670151-dda94fe2-e908-47e6-a5e9-47287d2ec3a6.mp4

**Comment by fwflunky** [comment]
Заработало нормально с Wine-GE-Proton 7-39 и dxvk-asynk-2.0
