### ISSUE TITLE
X11 hangs after clicking "apply the patch"

### ISSUE THREAD

**Issue by lolololer1337228** [an-anime-team/an-anime-game-launcher#116]
When I'm trying to apply the patch, my window manager just hangs. No response, I can only switch to another tty and I can't even kill the one that hang. Very weird

Arch Linux, Intel Xeon X5687, Msi Radeon RX580 8GB, 24GB DDR3

**Comment by lolololer1337228** [comment]
Something strange is that my cursor is still moving somehow, but it can't interact with anything

**Comment by Mar0xy** [comment]
Would be useful to know what window manager is being used as just stating the usage of a window manager is not enough as there are known issues with certain window managers missing the polkit gui causing stuff to break until a polkit agent with gui is installed

**Comment by lolololer1337228** [comment]
I use qtile
