### ISSUE TITLE
Blank page and error screen when opening "Notices"

### ISSUE THREAD

**Issue by Vlakc** [an-anime-team/an-anime-game-launcher#118]
When I click on "Notices" All I get is a blank page and the following error message:

![Screenshot from 2023-04-01 14-58-41](https://user-images.githubusercontent.com/129604470/229294912-3a164dbf-ae21-48d7-81ae-7cdd50c07238.png)

![Screenshot from 2023-04-01 15-41-16](https://user-images.githubusercontent.com/129604470/229295910-00c20f70-145a-4896-9cff-01dfd99ed9d1.png)

System:
OS: Manjaro Linux x86_64 
Kernel: 6.2.8-1-MANJARO 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 43.4 
WM: Mutter 
WM Theme: CustomAccentColors 
Terminal: gnome-terminal 
CPU: AMD Ryzen 5 4600H with Radeon Graphics (12) 
GPU: NVIDIA GeForce RTX 2060 Mobile

**Comment by krypt0nn** [comment]
We have nothing to do with it since it's wine-related. For note, in-game browser works to me, and I didn't install any additional packages to my prefix, so maybe, *maybe*, this issue somehow fixes itself
