### ISSUE TITLE
Version 3.x detects game version wrong

### ISSUE THREAD

**Issue by saepurusass** [an-anime-team/an-anime-game-launcher#119]
I recently tried to move to 3.x version but had several issues.

Biggest of them is that for whatever reason 3.x (3.3.0 at the time of writing) believes that my game version is 3.4.0 and wants to update/download the game again. And I would like to avoid that, it takes many hours on my slow connection.
At the same time it shows that patch version is 3.5.0 and xlua patch is also 3.5.0.

I have not been able to figure out where 3.4 comes from.
I found couple of files in game directory that contained 3.4, changed those to 3.5 but no effect. Either I missed one or it detects the version by some other method.

The latest 2.x (2.4.5) works just fine, so I am sticking with that right now. But I believe that I have to move to 3.x sooner or later. So would be nice to somehow solve that problem.

I also had trouble figuring out how to specify game location other than in home directory. Found it in configuration file and updated manually.
That is completely different issue but would be nice to have UI option to browse for game location.

Wine version was also an issue but I see that this one is fixed in latest version. But it is still detecting game version as 3.4.0.

![image](https://user-images.githubusercontent.com/28107527/229619749-d74b5634-c264-495e-82ea-be806edcb1a3.png)

**Comment by krypt0nn** [comment]
I didn't change version detection algorithm since the first time I wrote it:

`Game.ts`, Dec 22, 2021: https://github.com/an-anime-team/an-anime-game-launcher/commit/8da7e3efcc152e972018d6dabcec84ac4647eaa3

Anime Game Core library, nowadays: https://github.com/an-anime-team/anime-game-core/blob/main/src/genshin/game.rs#L44-L112

Bet you misconfigured launcher's `config.json`

**Comment by saepurusass** [comment]
I can't really understand from looking the code what file is actually read. Can't understand what `globalgamemanagers` refers to. I think it should resolve to actual filename.

Well, there isn't really any kind of documentation to aid non-default configuration. Like moving game to some other location.
At least not that I can find it. Have to figure out it by trial and error.

I have 2.4.5 installed and working. Just downloaded 3.x and expected it to pick up/migrate the configuration and just work too. Nope. Does not even see the game or anything else.

There are three similar name configuration files `config.json`, `conf.json` and `config.yaml`. That just adds to confusion. Not sure which ones are used by 2.x and which ones by 3.x.

I changed game location in `config.json` - because that was the only place I could find that references game location.
```
/.../
  "game": {
    "path": "/mnt/game-disk/Genshin Impact/Genshin Impact game",
    "voices": [
      "en-us"
    ],
/.../
```

That at least made it go further and detect the game, but detected ~~wrong~~ verision.

------------------------------
While writing all this, and double/triple checking everything, I figured out that there is something fishy with my setup.
And there is probably nothing wrong with detecting the game version.

Turns out that 2.4.5 does not use my game from `/mnt/game-disk/Genshin Impact/Genshin Impact game` like I expected to. And that game probably really is 3.4.0. I was pretty sure I managed to point my 2.4.5 to `/mnt/game-disk/Genshin Impact/Genshin Impact game` but not sure how it ended up not using it.

Game binary that actually runs is in `~/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact/`
But looks like the 3.x branch uses `~/.local/share/anime-game-launcher/prefix/drive_c/Program Files/Genshin Impact/` instead for whatever reason. And that is probably the reason why upgrading from 2.4.5 to 3.3.0 did not work for me.


**I guess it all comes down to a question:**
Which files and how should you change to move your game to another disk?
I would expect it to be a simple change of path in GUI.

Right now I think the easiest thing might be to move `~/.local/share/anime-game-launcher/` and replace it with symlink. Then there is no need to dive into configuration files. If the symlink actually works and does not backfire in some weird way.

**Comment by krypt0nn** [comment]
1) Never ever use symlinks. If you don't know exactly - better ask devs. Symlinks in general are real pain in ass and require additional efforts to properly work

2) About specifying installation and other paths

2.1) Launcher has extremely little hardcoded values. It's good for people who know what they do, and bad for everyone else. Same applies to installation paths. You can configure any of them, including path to temp directory where launcher will store pre-downloaded updates and other stuff

2.2) If you run launcher for the first time it shows initial setup window where user can easily select default installation path, and modify some other minor stuff. This window can be "manually called" by creating `.first-run` file in the launcher's folder if you want to look at it

2.3) It's pretty common question so I wrote large instruction in our discord server and just refer everybody to it

2.4) In the `next` branch I already started work on installation migration feature. I plan to add some button to settings which will open the same window as during initial setup, but in addition to changing paths it'll also move already downloaded data there, so *migrate* it. I expect it to pretty much solve any similar questions

2.5) I honestly can't understand what's so strange in changing paths in `config.json` file but here's small instruction in razor language:

- Close launcher
- Create new folder for launcher-related things anywhere you want. Let's say it's `/run/media/example/anime-game-launcher`
- Move every *folder* from current launcher folder (you said it's `$HOME/.local/share/anime-game-launcher` to you) to `/run/media/example/anime-game-launcher` **(so keep `config.json` in old folder, don't move it)**
- Open `$HOME/.local/share/anime-game-launcher/config.json`
- Press Ctrl+R (open text replacing dialog)
- Set "From" as "/home/[your username]/.local/share/anime-game-launcher"
- Set "To" as "/run/media/example/anime-game-launcher"
- Press "Replace all"
- Save file and open launcher. Done

3) We changed default paths recently. Now the game's installation is separate from the wine prefix. That was done for better proton-like builds support
