### ISSUE TITLE
[Issue]: Flatpak missing dependency (requires the runtime org.gnome.Platform/x86_64/42 which was not found)

### ISSUE THREAD

**Issue by Nyamiou** [an-anime-team/an-anime-game-launcher#12]
### Distro

SteamOS Beta on Steam Deck

### Installation Type

Flatpak

### Describe the issue

When trying to install the game on the Steam Deck (beta channel if that matter) I got the following error: 

`error: The application com.gitlab.KRypt0n_.an-anime-game-launcher/x86_64/master requires the runtime org.gnome.Platform/x86_64/42 which was not found`

It was working before but it seems it's not working anymore. I also reproduce the issue on my Arch desktop PC.

Thank you in advance.

### Reproduction Steps

Try to install the game Flatpak on an up to date Steam Deck on the beta channel using:

`flatpak remote-add --if-not-exists --user launcher.moe https://gol.launcher.moe/gol.launcher.moe.flatpakrepo`

`flatpak install launcher.moe com.gitlab.KRypt0n_.an-anime-game-launcher --user`

Get the error.

**Comment by Nyamiou** [comment]
Nevermind, I guess I shouldn't use "--user" on the second step "flatpak install launcher.moe com.gitlab.KRypt0n_.an-anime-game-launcher --user".

**Comment by ajburley** [comment]
I'm getting exactly the same error, and I already didn't use "--user"

**Comment by ajburley** [comment]
To fix it I just needed to run

`flatpak install org.gnome.Platform/x86_64/42`

then run the launcher install again and it worked

**Comment by Renari** [comment]
I also ran into this using the Discover app, oddly enough just running:
```
flatpak install moe.launcher.an-anime-game-launcher-gtk
```
In the terminal instead, works.
