### ISSUE TITLE
[Question] [Suggestion]Honkai impact launcher?

### ISSUE THREAD

**Issue by DarkenLX** [an-anime-team/an-anime-game-launcher#120]
Any possibility of a honkai impact launcher being worked on? Or this launcher supporting both I assume the issues running honkai on steam deck are caused by the same thing as genshin anti cheat but im not familiar with the games to state it is. Just curious if there's any possibility. Thanks anyway for the great work.

**Comment by androgynousRose** [comment]
There used to be a Honkers launcher, but due to anti-cheat changes it no longer works. Anime game uses a different anti-cheat.

**Comment by Mar0xy** [comment]
As explained above there used to be one but it no longer works due to AC changes.
