### ISSUE TITLE
When I log in the account and prepare to enter the game, it shows "Data error, please log in again."

### ISSUE THREAD

**Issue by hokchoi** [an-anime-team/an-anime-game-launcher#121]
As in the title, I tried to change the system voice to English, and restarted many times, but I still can’t log in.

**Comment by ATKghost** [comment]
Check and disable your http proxy

**Comment by xe5700** [comment]
same problem

**Comment by R29kTA** [comment]
同样的问题

**Comment by AndreaElijha** [comment]
same issue, i have two account, however the problem only occur on one of them, the other one can successfully login and play

**Comment by AndreaElijha** [comment]
> 

i had just deleted the bak file for there already has a mhypbase.dll file, however it didnt work

**Comment by zss192** [comment]
> Same problem, this problem popped up suddenly yesterday

By the way, I can log in normally with my friend's account, and I can log in with my mobile phone

**Comment by jfichen** [comment]
Same problem here, China Server..

**Comment by Faiayali** [comment]
I am the same. After the game update on the afternoon of the 13th, it showed abnormal data on the morning of the 14th, and I was unable to enter the game. After downloading and installing again, I still couldn't enter.

**Comment by ITACHIMnM** [comment]
Same problem

**Comment by c02y** [comment]
Related: 
https://github.com/an-anime-team/an-anime-game-launcher/issues/159

**Comment by CHN-beta** [comment]
Same issue.

**Comment by XDwanj** [comment]
同样的问题

**Comment by KXCAESAR** [comment]
Tested with steam proton experimental, edit config.ini with sub_channel=3 worked for me.
NOT sure it's safe for account.

**Comment by c02y** [comment]
> Tested with steam proton experimental, edit config.ini with sub_channel=3 worked for me. NOT sure it's safe for account.

I've tested weeks ago, after the game is launched, the `sub_channel` value will be restored to 0 automatically, the data error window is the same.

CN edition.

**Comment by onevcat** [comment]
In my case, the `sub_channel` was set to 1 when installing the game and the problem happens. After changing it to `0` today, I can enter the game without problem.

**Comment by CHN-beta** [comment]
The game of version 3.8 could be run on linux without patch. Just disable "apply main patch" in the launcher settings and the game works.

**Comment by xe5700** [comment]
Game can running without patch, but still data error.

**Comment by viewv** [comment]
I have the same issue, CN server.

**Comment by CHN-beta** [comment]
> I have the same issue, CN server.

same issue.

Hope the patches to become works again in upcoming 4.0.

**Comment by lingzs13** [comment]
I have the same issue, CN server.

**Comment by c02y** [comment]
> > I have the same issue, CN server.
> 
> same issue.
> 
> Hope the patches to become works again in upcoming 4.0.

This is not the patches issue, since the info sent to the server by wine/proton is different from Windows, the CN server maintainers are playing with CN Linux/macOS users. Your connection of the account on the Linux/macOS device is put into the blacklist temporarily, you cannot play the game on the Linux/macOS device, other devices are fine, unless they remove the blacklist in the new version. Then after days, they will again put you into the blacklist until the new version. It happens multiple times, I'm guessing they are really enjoying it.

**Comment by KXCAESAR** [comment]
Refer to https://notabug.org/Krock/dawn/issues/401 for same issue.
In my case "data error" pop up again about a week ago.

**Comment by CHN-beta** [comment]
> the info sent to the server by wine/proton is different from Windows

Is there any way to make wine mimic the behavior of windows?

A while back, the star-rail patches also had a problem of account blocking. The kindly developers finally successful to fix it. Does it the same with the problem this game currently meeting?

**Comment by c02y** [comment]
> > the info sent to the server by wine/proton is different from Windows
> 
> Is there any way to make wine mimic the behavior of windows?
> 
> A while back, the star-rail patches also had a problem of account blocking. The kindly developers finally successful to fix it. Does it the same with the problem this game currently meeting?

Not sure.

But I can play the new v4.0 in Steam without any patch, again, so I won't be surprised when I see the data error window in some day later.
