### ISSUE TITLE
I can't switch the game dir that i've already downloaded

### ISSUE THREAD

**Issue by SUFandom** [an-anime-team/an-anime-game-launcher#122]
![image](https://user-images.githubusercontent.com/70519093/230717359-5eee17f2-a134-4902-8aa3-5babeb5e3b9d.png)

Here's the image from my external drive, sadly i cant move it due to stuck at m.2 SATA 128GB 

ive downloaded this and ran the whole thing from windows 11 and was fully working,  but then windows decided to nuke my braswell gpu by forcing to install a broken drivers even i forced it not to on regedit and group policy (it felt personal btw from M$) after installing an update yet here we are, i can't run it because i cant set the game dir

![image](https://user-images.githubusercontent.com/70519093/230717470-e5820d8d-5397-4470-99c1-5c6123ad8964.png)

Debian 12.0 Bookworm
Intel Celeron N3060, Braswell GPU 400

**Comment by SUFandom** [comment]
NEVER MIND I SYMLINKED IT INSTEAD

**Comment by SUFandom** [comment]
Sorry for the bother, also if you have issues like this (whart i mean are the people struggling to play genshin on external drive, go to discord zarya_moonwolf_7#8205, ill help

**Comment by SUFandom** [comment]
`sudo ln -s <game external drive dir> <aimegamelauncher local dir>`

thats how you do it

**Comment by Mar0xy** [comment]
You can also just edit the config file as it has path settings for the game

**Comment by SUFandom** [comment]
> You can also just edit the config file as it has path settings for the game

No you can't , it wont recognize removable media storage, or rather, outside the home/<user>/.local area
at least in debian bookworm (sid) tho

maybe i should try this again but with another distro

> `sudo ln -s <game external drive dir> <aimegamelauncher local dir>`
> 
> thats how you do it

(also forgor that this may also not recognize standard symlinks so you may have to relaunch the launcher multiple times until it get recognized or restart debian, but the best way is to do hardlink folder dir
