### ISSUE TITLE
[Question] Migration from an-anime-game-launcher-gtk-bin

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#124]
I'm currently using `an-anime-game-launcher-gtk-bin 1.2.5-1` from Archlinux AUR.

Since this version of the package is archived according to [v3.0.0 release note](https://github.com/an-anime-team/an-anime-game-launcher/releases/tag/3.0.0), the package is also deleted from AUR, I'm going to update it to the latest 3.3.0 version for the coming game v3.6.

My questions:
- Is there anything I need to do for the migration, like configuration or location of the game or anything else?
- After I install [the latest AUR package](https://aur.archlinux.org/packages/an-anime-game-launcher-bin), do I need to delete the `~/.local/share/anime-game-launcher` and redownload the game from the beginning?

**Comment by Mar0xy** [comment]
just install the package it migrated to it will figure itself out
