### ISSUE TITLE
[Question] Space Requirements

### ISSUE THREAD

**Issue by NaiveInvestigator** [an-anime-team/an-anime-game-launcher#125]
Do I actually need that much space to install? But it worked last time but for some reason i had to uniinstall and reinstall and now i'm greeted witht this message.

![image](https://user-images.githubusercontent.com/72654596/231439309-ea0d02b8-6d1a-4bb1-8e28-8e05c23568ef.png)

**Comment by krypt0nn** [comment]
Yes you have to
