### ISSUE TITLE
[Issue]: No patch repository is available

### ISSUE THREAD

**Issue by yousae** [an-anime-team/an-anime-game-launcher#13]
### Distro

manjaro kde

### Installation Type

AUR

### Describe the issue

I can't get the patch
The following is log information

[23:31:30.827][Cache.get]
 - Resolved unexpired hot cache record
 - [name] Patch.getPatchInfo.3.0.0.origin
 - [value] {"available":false,"error":"origin patch repository is unreachable"}
[23:31:30.827][Cache.get]
 - Resolved unexpired hot cache record
 - [name] Patch.getPatchInfo.3.0.0.additional
 - [value] {"available":false,"error":"additional patch repository is unreachable"}
[23:31:30.827][thread: 8273][State.update] Updated state: game-launch-available
[23:31:42.472][thread: 4771][Process/Stream] Opened process 732730 stream

### Reproduction Steps

Download the patch

**Comment by krypt0nn** [comment]
Clear cache (button in settings / delete `.cache.json` file from the launcher's folder) and try again

**Comment by yousae** [comment]
Thank you very much. I have installed the patch according to your suggestion
