### ISSUE TITLE
Steam deck can't update from discover store?

### ISSUE THREAD

**Issue by TheFeri** [an-anime-team/an-anime-game-launcher#131]
I'm very new to linux, haven't even played genshin even so this is my forst setup, installed using the commands and after that discover lists an update, but I can't
![errorr](https://user-images.githubusercontent.com/114937939/232330085-3b4db7a1-ade9-48dd-b994-f9bda6a0d840.png)

I tried installing what it wants but apperently I already have it so I'm kinda lost.

**Comment by Gecko05** [comment]
Had the same issue and updated from the terminal and it worked, unfortunately afterwards I had an issue the game saying I don't have enough storage to download the update in-game.

The command is
`flatpak update moe.launcher.an-anime-game-launcher`

**Comment by Gecko05** [comment]
If you encounter the storage issue like me, just check https://github.com/an-anime-team/an-anime-game-launcher/issues/105#issuecomment-1499049391
