### ISSUE TITLE
Gentoo install instructions incorrect due to repository name mismatch

### ISSUE THREAD

**Issue by esibun** [an-anime-team/an-anime-game-launcher#132]
Cutting this so this doesn't get buried in #dev:

The installation instructions for Gentoo don't work as written.  `emaint sync` requires that the repository name configured in /etc/portage/repos.conf matches the repository name given in profile/repo_name.  That name is configured [here](https://github.com/an-anime-team/aagl-ebuilds/blob/main/profiles/repo_name) as `The-Anime-Game`, however the installation instructions use `an-anime-team` as the name.

This is a quick two-second documentation fix but I am unable to make a PR for wiki and only contributors are able to edit.

[fix-gentoo-install-instructions.patch.txt](https://github.com/an-anime-team/an-anime-game-launcher/files/11243240/fix-gentoo-install-instructions.patch.txt)

**Comment by Mar0xy** [comment]
it is meant to be an-anime-team and most likely wasnt update in the gentoo repo to avoid breakage as the-anime-game doesnt fit with the fact that there are multiple launchers

**Comment by esibun** [comment]
Yeah, that makes sense.  The other option as you point out would be to update the name in the Gentoo repo, though obviously this would cause sync errors until end users update their repo.conf.  Such an update would require an announcement hence why I suggested updating docs instead.

If the latter is still preferred I'll open a bug over there.  As is, this is and will likely continue to cause confusion from Gentoo end users who aren't aware of the validation from `emaint`.

(As an aside, this really isn't well documented in Gentoo documentation either, I'll try to improve that as well.)

**Comment by Mar0xy** [comment]
We have now fixed the issue by just swapping the repos so that the old repo will still work while people can move to the new repo
