### ISSUE TITLE
Launcher fails due to config filepath whitespace

### ISSUE THREAD

**Issue by Solemark** [an-anime-team/an-anime-game-launcher#136]
As can be seen in this discord support thread:

https://discord.com/channels/910869215857217596/1097352251649036308/1097352251649036308

The launcher seems to be failing when config file paths have spaces in them ie. /file/path/to/genshinimpact is fine but /file/path/to/genshin impact will fail and say that the launcher cannot find the filepath /file/path/to/genshin:

There are two temp fixes:
1. remove all whitespace from your filepath and update the config file
2. rollback to 3.4.1

**Comment by krypt0nn** [comment]
Already fixed in 3.5.2: https://github.com/an-anime-team/an-anime-game-launcher/releases/tag/3.5.2

**Comment by Solemark** [comment]
Mint!
