### ISSUE TITLE
Game stutters in cutscene

### ISSUE THREAD

**Issue by 1-minute-to-midnight** [an-anime-team/an-anime-game-launcher#138]
The game runs just fine during gameplay. Usually the cutscenes are the part where the PC shouldn't have any problems rendering because it's essentially just a video. But here it's quite the opposite. Is there a fix to this is?

**Comment by Mar0xy** [comment]
Quite odd no one ever had this here but I highly doubt there is a fix the only things you could try is changing wine versions.

also since this is something we can't do anything about this issue will be closed.

**Comment by 1-minute-to-midnight** [comment]
do you have any troubleshooting steps for this? I have tried everything....changed kernel, changed proton version etc. This issue isn't there with starrail so it probably isn't the fault of my PC.

**Comment by 1-minute-to-midnight** [comment]
I'm running Garuda Linux (basically arch), with GTX 1650 Mobile and AMD Ryzen 7 3750H.
