### ISSUE TITLE
Telemetry issue 

### ISSUE THREAD

**Issue by kasinadhsarma** [an-anime-team/an-anime-game-launcher#139]
![image](https://user-images.githubusercontent.com/81065703/233311622-ecbd0727-4ec3-4107-b262-61aad75b16a2.png)

[Screencast from 2023-04-20 14-16-26.webm](https://user-images.githubusercontent.com/81065703/233311941-14c9262c-8c2a-4e07-97aa-309fdecfb313.webm)

i have done full as you given information but getting telemetry issue

**Comment by jimmon89** [comment]
you forgot
```
0.0.0.0 log-upload-os.hoyoverse.com
```
