### ISSUE TITLE
[feature]: command line option to specify path where AAGL will store all files

### ISSUE THREAD

**Issue by legluondunet** [an-anime-team/an-anime-game-launcher#142]
Hello,
it will be very practice if we could specify path were AAGL will store or will find all his files: config, game etc.... instead of .local/share/an-anime-game-launcher. It could be a command-line option, similar to this one:
an-anime-game-launcher --path=/home/legluondunet/games/aagl

Thank you for your help.

**Comment by Pulecz** [comment]
Have you tried editing ~/.local/share/an-anime-game-launcher/config.json

There are set paths for each component.

**Comment by legluondunet** [comment]
the idea is to have all "[an-anime-game-launcher" files in the same path, even ~/.local/share/an-anime-game-launcher/config.json. But this can help.

**Comment by krypt0nn** [comment]
Noted, will be integrated into the core library later, but use `LAUNCHER_FOLDER` environment variable instead

**Comment by krypt0nn** [comment]
Done: https://github.com/an-anime-team/anime-launcher-sdk/commit/3b1bae948dae4051ca1b3f106278d3eb8c23eca9
