### ISSUE TITLE
Lutris now supports an anime game launcher :)

### ISSUE THREAD

**Issue by MrDisguised** [an-anime-team/an-anime-game-launcher#143]
https://lutris.net/games/genshin-impact/ - 

![image](https://user-images.githubusercontent.com/128170542/235075300-4985b870-a0eb-4988-ac42-27d5fbb6d89c.png)

https://forums.lutris.net/t/found-a-way-to-install-genshin-impact-on-linux/17715

**Comment by Mar0xy** [comment]
This has a issue of:

What would happen if someone who doesn't have the dependencies tries to run it? it would simply not open and this would mostly happen on debian/ubuntu

**Comment by MrDisguised** [comment]
> This has a issue of:
> 
> What would happen if someone who doesn't have the dependencies tries to run it? it would simply not open and this would mostly happen on debian/ubuntu

That means you have never used lutris. Try to install the genshin impact game with lutris the installer will show errors and will prompt users to install the dependencies first which are not installed on the system. Only after installing the dependencies the installer will run.

**Comment by Mar0xy** [comment]
Thanks for the explanation I do use lutris but only for windows games. We also got 2 more launchers Honkers and Honkers Railway which you might find interesting to look at.

**Comment by Mar0xy** [comment]
The installation instructions were added now into the `next` branch and wiki.
