### ISSUE TITLE
[Support] PopOS, LIBADWAITA error when trying to launch

### ISSUE THREAD

**Issue by Shaddox** [an-anime-team/an-anime-game-launcher#146]
Good evening! 

I'm trying to use this, but I'm currently getting this error when trying to open it : 

```
shaddox@pop-os:/usr/share/applications$ '/media/shaddox/Jupiter/Games/genshin-impact/anime-game-launcher' 
/media/shaddox/Jupiter/Games/genshin-impact/anime-game-launcher: symbol lookup error: /media/shaddox/Jupiter/Games/genshin-impact/anime-game-launcher: undefined symbol: adw_about_window_set_release_notes, version LIBADWAITA_1_0
```

I am on Pop! OS 22.04 . Any ideas on how to go about this?

**Comment by Mar0xy** [comment]
Please use flatpak for pop os, debian or ubuntu as the dependencies required for the binary are not available on those.

**Comment by Shaddox** [comment]
> Please use flatpak for pop os, debian or ubuntu as the dependencies required for the binary are not available on those.

This did it for me. Thank you for the support!

**Comment by sALTaccount** [comment]
I had to do `flatpak install flathub org.gnome.Platform//43` as well before I was able to install
