### ISSUE TITLE
Please add xdg-desktop-portal to the dependencies

### ISSUE THREAD

**Issue by asas1asas200** [an-anime-team/an-anime-game-launcher#154]
Since some people only install window managers instead of the entire desktop environment, `xdg-desktop-portal` may not be installed. If it is not installed, clicking the button to choose the default path will not respond and there will be no corresponding debug information. I traced back to the original source code and package library and found this issue [1].

[1] https://docs.rs/rfd/latest/rfd/#xdg-desktop-portal-backend

**Comment by Mar0xy** [comment]
xdg-desktop-portal has now been added as a dep by the AUR maintainer.
