### ISSUE TITLE
Missing launcher icon in dash and activities overview in gnome

### ISSUE THREAD

**Issue by saikat0511** [an-anime-team/an-anime-game-launcher#155]
Launcher is installed from AUR
![Screenshot from 2023-05-06 19-55-02](https://user-images.githubusercontent.com/57610828/236630212-d210aa11-3804-4c8b-9584-bd2bc9c68bef.png)

**Comment by krypt0nn** [comment]
@xstraok hi qq hello

**Comment by xstraok** [comment]
works fine on my system, even after reinstall

**Comment by xstraok** [comment]
what is the output of `ls /usr/share/icons | grep moe.launcher` @saikat0511

**Comment by saikat0511** [comment]
> what is the output of `ls /usr/share/pixmaps | grep an-anime` @saikat0511

```
~ $ ls /usr/share/pixmaps | grep an-anime
an-anime-game-launcher.png
```

**Comment by xstraok** [comment]
icon should be visible. Does it show up in other desktop environments?
And just in case, show output of `ls -l /usr/share/pixmaps/an-anime-game-launcher.png` and `cat /usr/share/applications/an-anime-game-launcher.desktop`

**Comment by saikat0511** [comment]
Experimented a bit. It seems it works fine on X11 session but broken on wayland

**Comment by saikat0511** [comment]
Seems like gnome wayland session handles desktop files and icons differently. Here's a similar issue from another project which was fixed, might help...

https://github.com/nextcloud/desktop/issues/1435#issuecomment-534696771

**Comment by saikat0511** [comment]
Renaming the desktop file from `an-anime-game-launcher.desktop` to `moe.launcher.an-anime-game-launcher.desktop` fixes the issue. Gnome wayland expects desktop file and icon to be similarly named I guess...

**Comment by saikat0511** [comment]
@xstraok Can you please update the desktop filename in AUR?

**Comment by saikat0511** [comment]
Why was the change reverted? I tested it on plasma just to be sure and there were no issues

**Comment by xstraok** [comment]
the reason why i reverted it is because i realized that many people (including myself) have the launcher pinned on their panels/dashes/taskbars/etc... 

By renaming the desktop file, it would render those old pinned launchers unusable, requiring users to re-pin. 

I feared that this would cause lots of confusion, opened github issues, discord support threads and it would be a hassle to deal with all of that.

Besides, it's a gnome issue.
