### ISSUE TITLE
Unable to login for first time due to Puzzle Captcha not showing up

### ISSUE THREAD

**Issue by PopataPotato** [an-anime-team/an-anime-game-launcher#156]
Basically what the title says. I'll provide a [screenshot](https://media.discordapp.net/attachments/711356555962089485/1104662151332896888/image.png). Running on Steam Deck.

Clicking the x button to try and close the white window freezes the game. The only way out is to force kill the process.

**Comment by Mar0xy** [comment]
Change wine version to one that is below 8

**Comment by PopataPotato** [comment]
Problem solved! I'll know to try that kind of stuff from now on. Thank you!
