### ISSUE TITLE
数据异常，请重新登录游戏。 Data error, please log in again. (China edition)

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#159]
Yesterday, I cannot log into the China edition of the game.
- Reinstalling the whole game won't work
- `Verify file integrity now` on the login window won't work
- `Repair game`  in the launcher's setting won't work
- My account is not banned since I can login on my smartphone.
- Global edition is working fine

In case anyone else has this issue as well, here is a workaround:
- open the terminal
- `cd ~/.local/share/anime-game-launcher/*** && bash ../patch/360/patch_revert.sh && bash ../patch/360/patch.sh`
- `WINEARCH="win64" WINEFSYNC="1" WINEPREFIX="$HOME/.local/share/anime-game-launcher/prefix" bash -c "'$HOME/.local/share/anime-game-launcher/runners/lutris-GE-Proton7-43-x86_64/bin/wine64' launcher.bat"` to launch the game.

So it seems the key here is "do not use `patch_anti_logincrash.sh`"

Not sure this issue is permanent, but this is the solution for now.

FYI: (Link Removed) and my platform is Arch Linux

screenshots:
![2023-05-10_18-56](https://github.com/an-anime-team/an-anime-game-launcher/assets/2135996/e4ba16e6-1295-44eb-9fc2-7387227f415d)
![2023-05-11_07-19](https://github.com/an-anime-team/an-anime-game-launcher/assets/2135996/a6c38391-244f-4d19-b949-6a0d2637ad69)

**Comment by c02y** [comment]
-------------
**UPDATE**:
Or according to https://github.com/an-anime-team/anime-game-core/blob/main/src/games/genshin/linux_patch/patches.rs#L424
```
impl_patch!(UnityPlayerPatch, false, "UnityPlayer.dll", "patch.sh");
impl_patch!(XluaPatch, true, "Plugins/xlua.dll", "patch_anti_logincrash.sh");
```
Uncheck the `Apply xlua patch` in the launcher's settings, it is the same as the manual steps.

**Comment by mkrsym1** [comment]
Not a launcher issue. There is an issue open about it on the patch repo.

**Comment by c02y** [comment]
> FYI: [Reference](https://notabug.org/Krock/dawn/issues/401) and my platform is Arch Linux

I know, the patch issue link is already here.

Just in case if any launcher user has this issue and don't know how to fix it.

**Comment by c02y** [comment]
Closing it for now since 3.7 also doesn't need `Apply xlua patch`

**Comment by c02y** [comment]
> the problem appears to be back after playing several days on 3.7. xlua patch is diabled

It's always OK for me.

**Comment by Icarus-Xu** [comment]
> > the problem appears to be back after playing several days on 3.7. xlua patch is diabled
> 
> It's always OK for me.

yeah seems weird, today its ok. dont know why, probably due to the game update
