### ISSUE TITLE
Failed to login in an anime game: 数据异常

### ISSUE THREAD

**Issue by YisuiDenghua** [an-anime-team/an-anime-game-launcher#160]
Device: Lenovo Legion Y9000X IAH7 (2022)
CPU: 12th Gen Intel Core i7-12700H × 20
GPU1: Intel Graphics (ADL GT2)
GPU2: NVIDIA GeForce RTX 3060 Mobile
System: Linux x86_64, NixOS 23.05.20230509.4487c14, 
Kernel: Linux 6.3.1-zen1

Game Version: 3.6.0, Chinese version.
Wine version: Wine-GE-Proton 8.4
DXVK version: 2.1

Error type: "数据异常，请重新登录游戏。"
![genshinfail](https://github.com/ezKEa/aagl-gtk-on-nix/assets/102890144/cc3ce65a-016a-4ace-9e4e-c46e1b7911d1)

**Comment by Mar0xy** [comment]
#159
