### ISSUE TITLE
Dualshock 4 is defined as the Xbox controller in the game

### ISSUE THREAD

**Issue by DTarxan** [an-anime-team/an-anime-game-launcher#162]
After a fresh reinstallation of the game and launcher, I ran into the problem that my Dualshock 4 is being recognized as an Xbox controller in the game. If you try in another application, then everything is in order.
Launcher version (not Flatpak) 3.6.0, in general, as in the game

**Comment by Ilia1** [comment]
Do you have original DS4 controller or chinese replica?

**Comment by DTarxan** [comment]
> Do you have original DS4 controller or chinese replica?

the original, but up to a certain point everything was fine, but then bam, and it doesn’t work

> Do you have your distribution's package of [steam-devices](https://github.com/ValveSoftware/steam-devices/) installed?

I turn off steam for the duration of the game through an anime game launcher

**Comment by quazar-omega** [comment]
The steam app is a separate thing from steam-devices, that package just provides the udev rules that allow your controller to be recognized correctly and it is always "active" (it's not an application that runs, it's more like a configuration), although I'm wondering how it was working for you before and then somehow stopped.  
What distro are you using?

**Comment by quazar-omega** [comment]
Hmm ok, so there was a change in your system, can you run these commands?

If not enabled Nonfree repository already do so with (from official [docs](urlhttps://docs.fedoraproject.org/en-US/quick-docs/setup_rpmfusion/))
```
sudo dnf install https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
```
Then install steam-devices:
```
sudo dnf install steam-devices
```

**Comment by DTarxan** [comment]
![изображение](https://github.com/an-anime-team/an-anime-game-launcher/assets/94784342/1bb58e19-0436-4a52-b5f8-43332a311bd8)
Everything is already included and installed

**Comment by quazar-omega** [comment]
Oh, hmm I have no clue at this point I was going off my previous [experience](https://discussion.fedoraproject.org/t/ps4-controller-shows-up-as-xbox/78761/10).  
Dud you save the list of user installed packages you had on your previous install? Maybe we can find the difference between the points where it worked and when it stopped working with that. Also, does it happen on every game?

**Comment by DTarxan** [comment]
Unfortunately, I did not have the previous list of packages, but Steam was also there. Speaking of other games 
![изображение](https://github.com/an-anime-team/an-anime-game-launcher/assets/94784342/7c3e3723-d7f7-4a70-8d5a-7901b8989b85) , everything is fine in Minecraft with a special mod, but alas, I can’t test other games, since they are all installed via Steam

**Comment by DTarxan** [comment]
![изображение](https://github.com/an-anime-team/an-anime-game-launcher/assets/94784342/8d72ea12-1dbc-45c8-bad7-4a9890955d34) Okay... well, magically the controller was identified as Dualshock... but I didn't do anything

**Comment by quazar-omega** [comment]
That's very weird hahah, did you reboot or something?
