### ISSUE TITLE
Downloading game data failed: "minreq error: was redirectged to an absolute url with an invalid protocol"

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#165]
- Delete the `~/.local/share/anime-game-launcher` directory
- Open anime-game-launcher
- Download the components and restart the launcher
- `Download` button
- Downloading failed: `minreq error: was redirected to an absolute url with an invalid protocol`

log:
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/11551566/debug.log)

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/2135996/251f12a4-affe-4eff-b710-ee70a23842c4)

FYI:
- an-anime-game-launcher-bin 3.6.0-3
- Arch Linux 6.3.2-zen1-1-zen

**Comment by skrunkly** [comment]
Same issue here

**Comment by Starsdust2004** [comment]
我也遇到了，请问有解决吗？
I have also encountered it. Is there a solution?

**Comment by Mar0xy** [comment]
Fixed in 3.7.0

**Comment by c02y** [comment]
Thank you, it works. :+1:
