### ISSUE TITLE
minreq error 

### ISSUE THREAD

**Issue by kasinadhsarma** [an-anime-team/an-anime-game-launcher#168]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/81065703/9836d1c1-2cd2-447b-a028-b66277bc8d06)

how to fix this error 
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/81065703/b956acc7-7c5c-4e3a-9693-d6c8b835199d)
and i am using ubuntu 23.04 thats why error got

**Comment by krypt0nn** [comment]
Update the launcher

**Comment by krypt0nn** [comment]
Your launcher is not updated. Perhaps because pacstall package is not updated yet

**Comment by chrystom** [comment]
pacstall package has been updated, you should be able to update it now with `pacstall -Up`

**Comment by kasinadhsarma** [comment]
tq
