### ISSUE TITLE
[Feature Request]Add "Pause/Resume" button on Downloading window

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#169]
When I try to download the game data which is around 50GB, in the beginning, the downloading speed is around 30MB/s, but after a while the speed becomes 3MB/s (This is an old issue actually, I noticed this months ago), so I would usually kill and reopen the program to download it again, but now it says that my disk space is not enough since it needs disk space for zip file and extracted data files, I have to remove the partial downloaded data file and redownload from the beginning.

Could you please add an `Pause/Resume` button when downloading the data?

BTW:
Since the launcher needs disk space that is big enough to store the zip file and the extracted game directory, is it possible to download the game data files directly so it doesn't need that big disk space or extracting step, just wondering?

**Comment by krypt0nn** [comment]
> is it possible to download the game data files directly so it doesn't need that big disk space or extracting step

Sorry that noticed this question so late. It is, you can use game repairer in launcher. It downloads all the files directly from the game API. But of course will work *extremely long*

About issue itself - it's already planned, but I can't say when you should await this feature to come
