### ISSUE TITLE
[Issue]: Loading part closes the game

### ISSUE THREAD

**Issue by StrangerGithuber** [an-anime-team/an-anime-game-launcher#17]
### Distro

Manjaro

### Installation Type

AUR

### Describe the issue

When I am starting the game then it works fine until loading the game after clicked to the door. On the 3rd icon the game crashes or just closing itself.
![image](https://user-images.githubusercontent.com/1939827/193102894-303bb6b8-4251-4503-893c-0be2ef7c8223.png)

I installed these 3 too when I saw it doesn't want to work:
<html>
<body>

<body>

Name | Description
-- | --
MangoHud | To use MangoHud
vkBasalt | To use shaders
GameMode | To use GameMode (performance optimization)

</body>
</html>

I used this command too:
`sudo pacman -Syu unzip tar git curl xdelta3 cabextract libnotify`

But nothing works. What can be the problem then?

### Reproduction Steps

1. Installing the game via Add and Remove Software
2. Starting the launcher
3. Clicking to the Update button
4. Clicking to the Apply test patch button
5. Clicking to the Launch button
6. Login with your account, wait until downloading the updates and whatever can be more
7. Click to the door
8. Waiting to loading the game

**Comment by Mar0xy** [comment]
As this issue isn't launcher related it will be closed since we don't deal with game issues on github nor can we link to the repo which patches it on github out of trust reasons.
