### ISSUE TITLE
error 9907 not enough storage free

### ISSUE THREAD

**Issue by alexou2** [an-anime-team/an-anime-game-launcher#172]
I get an error saying that i don't have enough storage free, but i still have more than 100gb in task manager. I'm running kubuntu 22.04 and installed the launcher from flatpak.

**Comment by darkwolf1000** [comment]
I had the same error on Arch on launcher version 3.6.0 but an update to 3.7.0-1 fixed it for me.

**Comment by alexou2** [comment]
I installed it today on 2 different pcs and i get the same error on both

**Comment by c02y** [comment]
AFAIK, you need around 130GB, 100GB is not enough, I believe there is error message window saying that how much disk space you need, the launcher needs disk space for both downloaded zip file and the extracted directory of the game.

**Comment by alexou2** [comment]
I managed to fix the bug
1 go to settings
2 go to the bottom of the list, then click on wine tools
3 click on configuration
4 in the wine popup, go to the Drives menu
5 click add, then ok
6 click on the drive you created
7 click browse and go to the location where the game is
8 click ok and launch the game
