### ISSUE TITLE
Error "undefined symbol: adw_about_window_set_release_notes, version LIBADWAITA_1_0" thrown on launch

### ISSUE THREAD

**Issue by EvilSupahFly** [an-anime-team/an-anime-game-launcher#176]
Using Native Anime Launcher 3.7.0 on Linux Mint 21.1 x86_64 with Cinnamon 5.6.8, running Kernel 6.2.7-060207-generic, and unable to launch due to the titular error.

Initially, I got `error while loading shared libraries: libadwaita-1.so.0: cannot open shared object file: No such file or directory` so I installed `libadwaita-1-0` from the official repo and now I get `undefined symbol: adw_about_window_set_release_notes, version LIBADWAITA_1_0` instead.

Since Cinnamon is technically a stripped-down, less bloated fork of Gnome 3, what else do I need to install for this to work properly?

** Edit ** I'm running the pre-compiled `native` version from [/releases](https://github.com/an-anime-team/an-anime-game-launcher/releases), not compiling from source myself, though I'm open to trying, just to see what happens.

**Comment by Mar0xy** [comment]
Ever thought of looking through closed issues?

#174 #146  #74

**Comment by EvilSupahFly** [comment]
Now that you mention it, I did overlook these. Thanks!
