### ISSUE TITLE
Opensuse repo dead

### ISSUE THREAD

**Issue by homayk228** [an-anime-team/an-anime-game-launcher#179]
Repository "aatrepo" is invalid.
[aatrepo|https://download.opensuse.org/repositories/home:Maroxy:AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] No valid metadata found at the specified URL
Story:
 - [aatrepo|https://download.opensuse.org/repositories/home:Maroxy:AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Repository type can't be determined.

**Comment by Mar0xy** [comment]
Please update to url to `https://download.opensuse.org/repositories/home:Maroxy:AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo`
