### ISSUE TITLE
shiny textures in-game emit a neon glow 

### ISSUE THREAD

**Issue by worlds-end** [an-anime-team/an-anime-game-launcher#180]
haven't found anything about the bug i'm experiencing elsewhere - but for some reason almost all shiny surfaces glow and look very out of place in game. I ran the launcher in a console and as i'm playing the console is flooded with "03ec:err:d3d:wined3d_debug_callback 000000003C6EBD90: "GL_INVALID_OPERATION error generated. Texture is already resident for this context.".", I don't have much experience with wine debugging so I was wondering if anyone here has dealt with this kind of issue and would be able to help me debug it.

For reference I'm running fedora 37, using the rpm version of the launcher.

**Comment by cybik** [comment]
No DXVK?

**Comment by worlds-end** [comment]
Looks like it's using vanilla2.2, I'll try a different version and report back.

**Comment by worlds-end** [comment]
looks like switching from vanilla 2.2 to async 2.0 fixed the issue for me, thanks for the guidance.
