### ISSUE TITLE
On Steam Deck, keyboard is invisible.

### ISSUE THREAD

**Issue by LeMemeDream** [an-anime-team/an-anime-game-launcher#181]
As the title says, on the Steam Deck, the keyboard is invisible and the cursor either becomes invisible or unmovable upon clicking the text box on the login screen. Of course, this is only a one time issue if you save your login, but it's a pretty major issue to try and overcome if you're just installing the game on your Steam Deck for the first time. Any idea what could be up? The keyboard is definitely THERE, since pressing R2 will (occasionally) type the default "G", and X *_does_ backspace, but...

**Comment by krypt0nn** [comment]
Can't nothing to do with it. I'll keep this issue open for a while so maybe somebody else could help you, but in general I recommend to visit our discord server which has separate steam deck users channel. Perhaps they could answer your questions
