### ISSUE TITLE
Touch screen doesn't work on the steam deck.

### ISSUE THREAD

**Issue by gezawatt** [an-anime-team/an-anime-game-launcher#183]
I just re-installed my entire steamOS.. Re-installed the game with default settings..

When I launch it in game mode, with controller input enabled, the touch screen doesn't work at all. It does work if I run the game from my windows install.

I wasn't able to fix this.

**Comment by krypt0nn** [comment]
Sorry, I have nothing to do with it. GTK/libadwaita apps aren't supposed to be used this way, so of course you'll have input issues

Can only recommend to use `--run-game` flag to avoid starting launcher at all and just run the game

**Comment by gezawatt** [comment]
> Sorry, I have nothing to do with it. GTK/libadwaita apps aren't supposed to be used this way, so of course you'll have input issues
> 
> Can only recommend to use `--run-game` flag to avoid starting launcher at all and just run the game

The touch scnreen works fine in the app itself. It works fine in the welcome screen of the game. 

It only stops working when I enable the controller mode in the game itself. And it's not how it behaves in windows. In windows the touch screen works even when the controller mode is enabled.
