### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by rootmelo92118** [an-anime-team/an-anime-game-launcher#184]
I got an error message when I launched the game.

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/32770959/aeba358f-0dee-432b-93c5-2cfc877f1a17)

How to fix it?

**Comment by lemisora** [comment]
Well, I ran into a problem like this one before, and even it has been solved in issues posted before here, the solution should be editing the config file of the game and move the folder of the game to ~/.var/app/moe.launcher.an-anime-game-launcher/data/anime-game-launcher/prefix/drive_c/Program Files

If you installed it as a Flatpak then the files should be in ~/.var/app/moe.launcher.an-anime-game-launcher/data/anime-game-launcher/

**Comment by lemisora** [comment]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/114361039/b4e84316-3918-4d0d-a50f-5974f118c8ab)
The file you should edit is this one in the screenshot

**Comment by lemisora** [comment]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/114361039/2136c251-1068-48f7-bdcf-d60ab28cfcf9)
And you should change the line resalted in the following screenshot

**Comment by rootmelo92118** [comment]
What is the part I should edit?

**Comment by lemisora** [comment]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/114361039/b0553363-710f-4a5f-86da-ff46bd2d73c3)
And you should move the "Genshin Impact" directory to the path it says on the global field on the config.json file c:

**Comment by lemisora** [comment]
https://github.com/an-anime-team/an-anime-game-launcher/issues/105#issuecomment-1495138880

There is the solution of this exact same issue c:, I think that this can be the solution, if it's the same issue

**Comment by rootmelo92118** [comment]
> [#105 (comment)](https://github.com/an-anime-team/an-anime-game-launcher/issues/105#issuecomment-1495138880)
> 
> There is the solution of this exact same issue c:, I think that this can be the solution, if it's the same issue

Thanks. But after I do this operation. My launcher doesn't work.

**Comment by rootmelo92118** [comment]
I move the `Genshin Impact` directory into `prefix/drive_c/Program Files` and also edit the configuration. I doesn't work any more.

**Comment by rootmelo92118** [comment]
> [#105 (comment)](https://github.com/an-anime-team/an-anime-game-launcher/issues/105#issuecomment-1495138880)
> 
> There is the solution of this exact same issue c:, I think that this can be the solution, if it's the same issue

Thanks.
