### ISSUE TITLE
[UI] Make switching of account to be a button instead of a dropdown so that it could work on Steam Deck Game Mode

### ISSUE THREAD

**Issue by rairulyle** [an-anime-team/an-anime-game-launcher#185]
Hello,

I was able to run it well but the issue I have right now is it is really hard to switch an account. I have to go to desktop mode to switch an account since the drop-down doesn't work on Steam Deck Game Mode. 

It would be better to remove the section with the drop-down and just add a button to switch an account at the profile section near the delete and reset button.

**Comment by krypt0nn** [comment]
1. I expect people to use `--run-game` flag on steam deck
2. I won't remove active section selection due to how things supposed to work
3. It's already planned to add a button to apply specific session and make it active. Expect it to appear in future updates

**Comment by rairulyle** [comment]
@krypt0nn , yeah maybe not remove it but this is how I imagine the new UI:

BEFORE:
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/12708526/a4576caa-21ee-40fe-b6f0-fa56601fd0d5)

AFTER
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/12708526/c7e2c140-7f0c-4070-98c7-25a4c7f73eb9)

Glad to know that this will be in the future updates!

**Comment by krypt0nn** [comment]
Await this change in the next release. Closed

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/29639507/a839b240-7f8b-44a7-b22b-be4a7264b1a5)

**Comment by rairulyle** [comment]
Love it!
