### ISSUE TITLE
[Issue]: Nothing changes after "apply patch"

### ISSUE THREAD

**Issue by NEsanya** [an-anime-team/an-anime-game-launcher#19]
### Distro

Arch linux x86_64 5.19.13-zen1-1-zen

### Installation Type

AUR

### Describe the issue

I press "apply patch" button in launcher, and then i see "apply patch" again.

**Comment by icedgreen** [comment]
Are you using a WM? If you don't have `polkit` installed and configured properly, you won't be able to see the password prompt for changing the hosts file.

**Comment by NEsanya** [comment]
I use i3wm

**Comment by icedgreen** [comment]
You also need an authentication agent. See the arch wiki: https://wiki.archlinux.org/title/Polkit

**Comment by NEsanya** [comment]
Yep, that's works!
