### ISSUE TITLE
Stuck at TOS Violation Warning

### ISSUE THREAD

**Issue by p0c0k** [an-anime-team/an-anime-game-launcher#194]
I installed the launcher and I cannot move forward because there is no button to do so. I changed language to English and removed the launcher's folder and now it works. I'm using the Hungarian translation.
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/88557395/c4f0504c-540a-4371-81c3-87a0d92f2a32)

**Comment by krypt0nn** [comment]
Thanks for report. Will be fixed today in 3.7.2
