### ISSUE TITLE
pacstall and RPM versions outdated

### ISSUE THREAD

**Issue by chrystom** [an-anime-team/an-anime-game-launcher#201]
not really urgent but could someone on Ubuntu and Suse/Fedora please **update** the according packages. I personally would if i didn't move back to arch :/

**Comment by Mar0xy** [comment]
RPM will be updated within the next few hours for all launchers.
for Ubuntu please ask @Henryws

**Comment by Henryws** [comment]
Done!

**Comment by Mar0xy** [comment]
The RPM packages are now all updated as well.
