### ISSUE TITLE
"Failed to install wine"

### ISSUE THREAD

**Issue by remivamp** [an-anime-team/an-anime-game-launcher#202]
The launcher is freezing at the download components stage with a "Failed to install wine: Timeout of the package has been reached" error.
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/11788586/debug.log)

**Comment by Nebula-Developer** [comment]
Having the same issue. Sorry if there's a solution somewhere that I can't find. Did you ever find a way of fixing this?
