### ISSUE TITLE
Failed to find wine path

### ISSUE THREAD

**Issue by randomarchuser** [an-anime-team/an-anime-game-launcher#203]
I'm trying to install on macOS with M1 cpu. In the Download Components page of the setup process, it says Failed to apply DXVK and Failed to find wine path. 
<img width="784" alt="Screenshot 2023-06-19 at 15 47 18" src="https://github.com/an-anime-team/an-anime-game-launcher/assets/110524712/40c878f5-a620-471e-ba43-b63815a6bd7a">
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/11788768/debug.log)

**Comment by Mar0xy** [comment]
This launcher is not intended for MacOS please check YAAGL instead https://github.com/3Shain/yet-another-anime-game-launcher

**Comment by randomarchuser** [comment]
That is unfortunate, but thanks for informing me.
