### ISSUE TITLE
Not an issue more of a question: OpenGL option

### ISSUE THREAD

**Issue by Speyll** [an-anime-team/an-anime-game-launcher#205]
In my quest to get the launcher working on an Intel Graphics HD 4400 (HSW GT2) with its limited Vulkan support, I considered the feasibility of disabling DXVK or configuring the launcher to employ OpenGL. Despite the anticipated performance decline, Could you enlighten me on the process, if indeed possible?

**Comment by Mar0xy** [comment]
With games by the company it is not at all possible to use no DXVK as it doesn't just cause performance downgrades it straight up also causes immense graphical glitches like lighting going all rainbow and etc.
