### ISSUE TITLE
Data use shows up as 281.5TB on fedora storage section, which is false

### ISSUE THREAD

**Issue by WilliamHarrisonGB** [an-anime-team/an-anime-game-launcher#206]
its also coincidentally related to this 
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/125414146/5c3b8bfd-dcc7-4c7e-9c74-cc7260ae92dd)

**Comment by Mar0xy** [comment]
And what are we suppose to do about an issue with Fedora? We are not the Fedora developers and can't do anything about Fedora bugs

**Comment by WilliamHarrisonGB** [comment]
idk im dumb
