### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Albert753258** [an-anime-team/an-anime-game-launcher#209]
![Screenshot from 2023-06-28 22-36-35](https://github.com/an-anime-team/an-anime-game-launcher/assets/56261876/5122657c-a123-4b27-9a99-5139b36d255e)
![Screenshot from 2023-06-28 22-34-39](https://github.com/an-anime-team/an-anime-game-launcher/assets/56261876/731c1270-2ebe-406e-af97-305e0a0f736a)
![Screenshot from 2023-06-28 22-32-40](https://github.com/an-anime-team/an-anime-game-launcher/assets/56261876/6e0090f1-7458-49af-8217-95120e34924e)

**Comment by Mar0xy** [comment]
Please switch DXVK versions as this should fix the issue.
