### ISSUE TITLE
Apply patch not work

### ISSUE THREAD

**Issue by rootmelo92118** [an-anime-team/an-anime-game-launcher#212]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/32770959/fbca6bfa-1ee5-4495-838d-5e765c6de4b2)

How to fix it?

**Comment by BlackOutedMind** [comment]
The game was updated, while who makes the patches didn't updated yet so only thing we have to do is wait while the patch is out

**Comment by TheFlagCourier** [comment]
You can also risk *not* applying the patch. (YMMV, wait if you can.)

**Comment by c02y** [comment]
Quote from somewhere:
> Many of the players in the AAGL discord are reporting completely unpatched, untouched and unrenamed installs worked instantly. 3.8 might (I stress MIGHT) be the first unpatched-on-release version.

If your old game data is already patched, maybe you should `patch_revert` it first.

There is a `Data error` window for me on the 3.7 version BTW.

So here is what I run to not use this launcher to launch the game successfully:
```
WINEARCH="win64" WINEFSYNC="1" WINEPREFIX="$HOME/.local/share/anime-game-launcher/prefix" bash -c "'$HOME/.local/share/anime-game-launcher/runners/lutris-GE-Proton8-8-x86_64/bin/wine64' YuanShen.exe"
```
run this in yyy game data directory, yyy is the game data directory in `$HOME/.local/share/anime-game-launc/`, change the xxx.exe with the game exe file of your game in `$HOME/.local/share/anime-game-launc/yyy/xxx.exe`

**Comment by gfififid** [comment]
what i know to start play today:

1) I recomend completly delete game folder and reinstall game compleatly
2) 3.8 can work without any patch on linux(apply patch only if it needed). To run game trough launcher you need create launcher.bat file with this inside:

@echo off
start GenshinImpact.exe %*
 
3) driver error stil exist(but game work), so it's recomended to still block error reports with hosts file
4) do not use youre main account for around a week, and then check git for ban reports, we don't know will be accounts baned or not(you may use main account if you are not afraid of the ban. i use my main and no permoment ban)
