### ISSUE TITLE
Can't change install directory with an-anime-game-launcher-bin

### ISSUE THREAD

**Issue by aaannestad** [an-anime-team/an-anime-game-launcher#215]
I'm trying to use `an-anime-game-launcher-bin` on Manjaro (after trying and failing to use the Lutris version), and I'm unable to change the default install directory - 'migrate install' gives me a list of buttons to click to change various directories, but clicking them does nothing. I need to change the install directory because there's not enough space for the enormity of this game on my home partition, and if I just leave them at the default the launcher complains about this and gives me no option to install the game elsewhere.

This is kernel version 6.1.31-2-MANJARO and the newest version of the Anime Game Launcher.

What can I do here? How can I point the launcher to install on my secondary drive, where there's space?

**Comment by Mar0xy** [comment]
On first run the launcher will ask if you want to change the launcher folder directory you simply just change that.

**Comment by aaannestad** [comment]
@Mar0xy I had the same problem then; clicking the buttons showing the various install paths had no effect, and I wasn't given any text entry field to put in an alternative path.

**Comment by justxxtx** [comment]
same problem

**Comment by krypt0nn** [comment]
> And I did try to uninstall and reinstall, but apparently the uninstall process doesn't remove the settings for where the install directory is

```sh
flatpak uninstall --delete-data <flatpak app id>
```

> clicking the buttons showing the various install paths had no effect

Your system lacks `xdg-open` script, which is part of freedesktop specification. No idea why, but it's relatively common issue. Perhaps some manjaro moment

Paths can be changed in the config file as well, which will require understanding of what you do

**Comment by constantitus** [comment]
> Your system lacks `xdg-open` script, which is part of freedesktop specification. No idea why, but it's relatively common issue. Perhaps some manjaro moment
Can you please elaborate on that ? I'm having the exact same issue on gentoo and I don't even know where to start throubleshooting

**Comment by krypt0nn** [comment]
Start by reading the terminal output, because the errors are written there -_-

**Comment by parthen-github** [comment]
> Start by reading the terminal output, because the errors are written there -_-

I have same problem, but terminal doest output anythin while I click. except GTK warnings on startup.

```
(process:32246): Gtk-WARNING **: 13:18:52.024: Unknown key gtk-modules in /home/parthen/.config/gtk-4.0/settings.ini

(process:32246): Adwaita-WARNING **: 13:18:52.050: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.

```

EndervaousOS (Arch Linux) with KDE

**Comment by AryanAD** [comment]
> > Start by reading the terminal output, because the errors are written there -_-
> 
> I have same problem, but terminal doest output anythin while I click. except GTK warnings on startup.
> 
> ```
> (process:32246): Gtk-WARNING **: 13:18:52.024: Unknown key gtk-modules in /home/parthen/.config/gtk-4.0/settings.ini
> 
> (process:32246): Adwaita-WARNING **: 13:18:52.050: Using GtkSettings:gtk-application-prefer-dark-theme with libadwaita is unsupported. Please use AdwStyleManager:color-scheme instead.
> ```
> 
> EndervaousOS (Arch Linux) with KDE

We have the same DE and I am receiving the same errors

**Comment by chaoscollie** [comment]
Hi, I'm using EndeavourOS (Arch Linux) and KDE Plasma as well, after some tinkering, it looks like installing the `xdg-desktop-portal-kde` package and rebooting allows the launcher to open the file browser.

It isn't an issue with this project, it's just an issue with some systems not having this package installed alongside the KDE Plasma DE.

@AryanAD @parthen-github this may help you two in particular.

Apologies for replying to a long since closed issue, but I figured it may help some people.
