### ISSUE TITLE
Can't apply the patch in flatpak 

### ISSUE THREAD

**Issue by ChaoticChrono** [an-anime-team/an-anime-game-launcher#219]
I have installed the flatpak but for some reason it leaves me this error when I try to patch the game 
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/130445844/95f4ad9c-63ec-437d-a9c6-e76410e57d4b)

**Comment by gfififid** [comment]
3.8 can work without any patch on linux. To run game trough launcher you need create launcher.bat file in genshin game folder with this inside:

@echo off
start GenshinImpact.exe %*

Or you can wait for launcher update

**Comment by ChaoticChrono** [comment]
Thanks for your reply it seems you are right the game does work well without the patch
