### ISSUE TITLE
[Issue]: Insufficient storage space problem

### ISSUE THREAD

**Issue by yxtj** [an-anime-team/an-anime-game-launcher#22]
### Distro

Steam Deck. Steam OS 3.3.2.
Game Version: 3.1.

### Installation Type

Flatpak

### Describe the issue

I am using the launcher on Steam deck. I installed it following the guide.
I changed the folders-game option in the config.yaml file to be "/home/deck/.var/app/com.gitlab.KRypt0n_.an-anime-game-launcher/data/Genshin Impact". (removing the "driver_c/Program Files" part)
The game installs and starts successfully.

When it pulls the in-game updates, the game shows an error box saying: "Insufficient storage space. Please ensure sufficient space and try again. Code:-9907"
The download progress bar shows "0.27% 26.86 MB / 9883.41 MB".

My device still has 200+GB available space.

**Comment by Mar0xy** [comment]
This happens due to the game checking the Z; drive that wine also includes by default which links to your main linux drive content the easiest way to fix this is by going into settings > winecfg > drives and removing the Z drive

**Comment by Dennoquellovero** [comment]
Removing the Z: drive makes the game unable to start, I fixed this by adding the path to the game folder next to the Z drive.

**Comment by zzgtyouka** [comment]
> Removing the Z: drive makes the game unable to start, I fixed this by adding the path to the game folder next to the Z drive.

can u describe more details on adding the path，tks.
