### ISSUE TITLE
can't get past basic installation

### ISSUE THREAD

**Issue by NitroDIon** [an-anime-team/an-anime-game-launcher#220]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/79161255/7b59f24e-1c83-4f90-b154-ffc5ad7e912a)
after i click download it just crashes

**Comment by krypt0nn** [comment]
Something is wrong with your internet, launcher couldn't sync components repository. You can do it yourself by cloning https://github.com/an-anime-team/components repo to the launcher folder

**Comment by NitroDIon** [comment]
thanks this fixed my issue it seems it might be an issue with the flatpak but i wasn't able to load any of the other install options for my distro (linux mint) so i was left with the flatpak as my only option

**Comment by NitroDIon** [comment]
Never mind now i'm getting a failed to mount path option every time

**Comment by NitroDIon** [comment]
neve

**Comment by NitroDIon** [comment]
nevermind i'm still having issues
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/79161255/380e215a-5d56-49d0-89d3-1db77704596c)

**Comment by NitroDIon** [comment]
ok i just decided to put it in my home directory and it's working now i know this isn't exactly a fix so i'll leave this issue open

**Comment by krypt0nn** [comment]
`/run/user/1000/<random value>` is not a correct path. Replace it with an actual one in the config file

**Comment by NitroDIon** [comment]
> `/run/user/1000/<random value>` is not a correct path. Replace it with an actual one in the config file. You can access it from the launcher's hamburger menu. Don't forget to close the launcher before updating config file values

seems this fix doesn't work for some reason looks like the issue need to be reopened cause when i try to install the actual game this shows up (don't worry about the home directory name it's a fake name i gave my home directory)
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/79161255/822794ff-32af-458f-918d-1b0c22664e81)

**Comment by krypt0nn** [comment]
Not a launcher bug. Check all the paths and, if you use flatpak, its filesystem permissions

**Comment by NitroDIon** [comment]
> Not a launcher bug. Check all the paths and, if you use flatpak, its filesystem permissions

i see thank you i had no idea
