### ISSUE TITLE
[SteamoOS] 3.8.0 Can't apply patch and game won't start

### ISSUE THREAD

**Issue by PsCitofono** [an-anime-team/an-anime-game-launcher#224]
I can't apply the 3.8 patch via the launcher and installing it manually doesn't seem to work either
I've already set the read+write, if i start the game without the patch i get a data error code: 31-4302 and can't get past the "door" screen
is there a way to fix this or the patch is still not out yet?

**Comment by TheFlagCourier** [comment]
3.8 does not require a patch. (See #219, #212, and the README)
Make sure that your launcher is up-to-date, and disable the patch in the launcher's settings.
![Step2](https://github.com/an-anime-team/an-anime-game-launcher/assets/2712890/69944e36-ba6b-431d-a0da-0a9f5e57bcd6)

If you're getting a 31-4302, **you need to re-install**. I had the same issue, and "Repair Game" wouldn't fix it. My solution was to uninstall the Flatpak, clean up leftover data via Discover, and then reinstall everything from scratch.

**Comment by Gamertech** [comment]
Don't need to reinstall. Just search for disabled files (.exe.bak and .dll.bak) and remove the .bak. There were three iirc?
Do disable the patch first though.
