### ISSUE TITLE
Launcher takes long time to start up

### ISSUE THREAD

**Issue by labo-China** [an-anime-team/an-anime-game-launcher#225]
The launcher (latest version) takes a long time to start up.
It prompt nothing in the terminal before the window appears and prompt things below when the window pops up:

>   2023-07-24T02:32:02.472691Z  WARN anime_launcher_sdk::games::genshin::states: Failed to check telemetry servers: failed to lookup address information: 未知的名称或服务(which means 'Unknown name or service'). Assuming they're disabled
    at /var/home/observer/.cargo/git/checkouts/anime-launcher-sdk-72c1eacede3fc588/2740eae/src/games/genshin/states.rs:161

>  2023-07-24T02:32:02.489744Z  WARN anime_launcher_sdk::games::genshin::sessions: Session file doesn't exist. Returning default value
    at /var/home/observer/.cargo/git/checkouts/anime-launcher-sdk-72c1eacede3fc588/2740eae/src/games/genshin/sessions.rs:38

>  2023-07-24T02:32:02.489763Z  WARN anime_launcher_sdk::games::genshin::sessions: Session file doesn't exist. Returning default value
    at /var/home/observer/.cargo/git/checkouts/anime-launcher-sdk-72c1eacede3fc588/2740eae/src/games/genshin/sessions.rs:38

When I attempt to start the launcher, the title bar appears immediately and the mask of the window can be seen on XFCE`s workspace switcher while nothing is actually visible on screen. During this period, no messages are printed in the terminal, and I can receive 'The window is not responding' from WM when trying to close the window. I guess there is something blocking during the process. After the window pops up, everything works fine.

BTW, I am currently lived in China and have potential issues connecting Github so I used a software to boost the process. The issue does not get resolved with the software off. By using the task manager, it is seemed that the `git fetch origin` phase passes quickly. So it maybe has nothing to do with my network.

Here is the log file. 
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/12141418/debug.log)

**Comment by krypt0nn** [comment]
Nothing to do with the launcher. Almost all the startup time takes patch repo status fetching, which is hosted in codeberg. It's having bad time this month and such issues are expected

**Comment by tiankaima** [comment]
Also worth noticing: If you live in mainland CN, using a VPN would help.
