### ISSUE TITLE
[Issue]: "server: cn" and "server: global"

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#23]
### Distro

Arch Linux x86_64

### Installation Type

AUR

### Describe the issue

I've beening play the `server: global` version for quite some time, it works fine, then I changed `server: global` to `server: cn` in `~/.local/share/anime-game-launcher/config.yaml` and started the launcher, the launcher redownloaded and repatched the game and the game works fine using my cn account.

After a few hours of playing the `server: cn` version, I decided to switch back to `server: global` so I edited the config file, start the launcher, and launcher doesn't redownload/repatch the game, and the game launched is still "server: cn" version.

FYI: `revert patch` or `re-apply patch` won't work in setting, the game won't be launched in the end using the `Launch` button, I managed to delete the `~/.local/share/anime-game-launcher` directory and do the process to download/patch the game from the first start.

### Reproduction Steps

1. Change the `server: global` to `server: cn`, open the launcher
2. wait the launcher to redownload and repatch the game
3. open the game and close it
4. Change the `server: cn` to `server: global`, open the launcher
5. launch the game

**Comment by Mar0xy** [comment]
Since there is a duplicate issue #24 this will be closed and locked. All conversation related to this should be done in #24
