### ISSUE TITLE
lutris version doesn't set executable

### ISSUE THREAD

**Issue by waffleboi9000** [an-anime-team/an-anime-game-launcher#230]
Did a fresh install of lutris on openSUSE Tumbleweed, then installed AAGL from Lutris. After clicking launch, the launcher reopens. Terminal output says that there was no executable set for the anime game/file was not found. I navigated to the installation folder in my file explorer, and directly opened the exe of the game with wine, and that worked with no issue, so it seems like the installation somehow didn't set the exe? In any case I also tried redownloading everything, swapping wine versions between Wine GE, Soda, and Lutris wine, as well as vanilla or async dxvk. I noticed that I also wasn't prompted to install wine-mono on the initial installation. The default wine used was Lutris GE 5-13, but i managed to get the wine mono prompt by swapping to the regular Lutris wine 7.2.2. I'll be swapping to flatpak for now, but I'd prefer for the Lutris version to work.

**Comment by Mar0xy** [comment]
Please check this part of the wiki:
https://github.com/an-anime-team/an-anime-game-launcher/wiki/Installation#-opensuse-tumbleweed-rpm

**Comment by waffleboi9000** [comment]
I tried adding the repo from the wiki, but got the error:
Repository 'aatrepo' is invalid.
[aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Valid metadata not found at specified URL
History:
 - [aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'aatrepo' because of the above error.

I navigated to the actual url, downloaded the .repo file, and used that, and that worked, but running sudo zypper refresh gave the error:
Repository 'aatrepo' is invalid.
[aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Valid metadata not found at specified URL
History:
 - [aatrepo|https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/openSUSE_Tumbleweed/home:Maroxy:AAT-Apps.repo] Repository type can't be determined.

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'aatrepo' because of the above error.

I was able to install the launcher from the repo still, but it seems like the launcher crashed instantly.

Well, this is embarrassing.

anime-game-launcher had a problem and crashed. To help us diagnose the problem you can send us a crash report.

contents of the TOML:
name = "anime-game-launcher"
operating_system = "openSUSE 20230811 [64-bit]"
crate_version = "3.8.0"
explanation = """
Panic occurred in file 'src/main.rs' at line 78
"""
cause = "Failed to create launcher folder: Os { code: 17, kind: AlreadyExists, message: \"File exists\" }"
method = "Panic"
backtrace = """

   0: 0x55bd44f4097b - <unresolved>
   1: 0x55bd44e39568 - <unresolved>
   2: 0x55bd44f3bf3c - <unresolved>
   3: 0x7fb5d61b0bf0 - __libc_start_call_main
   4: 0x7fb5d61b0cb9 - __libc_start_main@GLIBC_2.2.5
   5: 0x55bd44df0055 - <unresolved>
   6:        0x0 - <unresolved>"""
Anyways, my main issue is that the executable isn't being set on the lutris version, so when you hit launch, wine doesn't know what to do.

**Comment by Mar0xy** [comment]
> Failed to create launcher folder: Os { code: 17, kind: AlreadyExists, message: "File exists" }

Like it says the folder for the launcher already exists in .local/share just delete it

>  my main issue is that the executable isn't being set on the lutris version

We don't provide support for the lutris version anymore as it also is not being updated to the latest version.
