### ISSUE TITLE
Cant patch.

### ISSUE THREAD

**Issue by sheesh42j** [an-anime-team/an-anime-game-launcher#231]
Everytime i click the patch button it wont patch. i click and nothing happens.

**Comment by krypt0nn** [comment]
There's no patch for genshin anymore. Just disable its apply in settings. If the situation won't change, I'll remove patches support entirely

**Comment by sheesh42j** [comment]
that fixed it, thanks!

**Comment by EvilBoi123** [comment]
> There's no patch for genshin anymore. Just disable its applying in settings. If the situation won't change, I'll remove patches support entirely

weird, it can't run for me, it does run the login screen but as soon i log in, it says i need to reinstall the game.
