### ISSUE TITLE
can't run the game without patch

### ISSUE THREAD

**Issue by EvilBoi123** [an-anime-team/an-anime-game-launcher#232]
idk why, today i receive: 
![apply patch](https://github.com/an-anime-team/an-anime-game-launcher/assets/102599991/31585f5d-8e5b-4736-ac53-b64d659beeb2)

So i tried to apply the patch button but it didn't work. But i heard that 3.8 does not need patch so might as well just disable patch in settings but i got this problem: 

![genshin_error1](https://github.com/an-anime-team/an-anime-game-launcher/assets/102599991/82e9541f-5f51-4b46-baa2-5a8b694291f2)

I can't run without patches unlike everyone told me to.

**Comment by Albert753258** [comment]
I got absolutely same issue

**Comment by itistimetogo** [comment]
Same here.

**Comment by celiacheff** [comment]
Seems like the 400 patch is detected too early. Renaming it remove the apply patch warrning, but the game doesn't start after. Didn't try to revert the 400 patch, but it may solve the problem.

**Comment by EvilBoi123** [comment]
Hey guys, i ran the recent genshin impact by using genshin impact's launcher through lutris. it ran this time. 

I symlink the genshin impact's data directory to the launcher so i wouldn't need to redownload the genshin. No patch further patch were required. 

So i might as well use this as temporary solution until this problem resolved

**Comment by AlphaCraft9658** [comment]
@EvilBoi123 
> So i tried to apply the patch button but it didn't work. But i heard that 3.8 does not need patch so might as well just disable patch in settings but i got this problem:

Where did you hear the game should run without the patch?

**Comment by Albert753258** [comment]
> Hey guys, i ran the game by using game's launcher through lutris. it ran this time.
> 
> I symlink the game's data directory to the launcher so i wouldn't need to redownload the game. No patch further patch were required.
> 
> So i might as well use this as temporary solution until this problem resolved

Just do game repair in the official launcher, It will solve this problem

**Comment by itistimetogo** [comment]
> > Hey guys, i ran the game by using game's launcher through lutris. it ran this time.
> > I symlink the game's data directory to the launcher so i wouldn't need to redownload the game. No patch further patch were required.
> > So i might as well use this as temporary solution until this problem resolved
> 
> Just do game repair in the official launcher, It will solve this problem

Did you only click on "Repair game"? When I clicked on it, all files were verified but it jumped back to the initial window demanding to "apply patch". :\

**Comment by EvilBoi123** [comment]
Hello, today i ran the game through this launcher again with no patch, it worked, but the color is all wrong and it won't fix itself by changing wine version. idk why tho.

**Comment by krypt0nn** [comment]
Everyone, listen:

1. Disable patch applying in settings - both main and additional (mhypbase)
2. If you used flatpak, then run `cd "$HOME/.var/app/moe.launcher.an-anime-game-launcher/data/anime-game-launcher/Genshin Impact" && bash ../patch/380/patch_revert.sh`. If you used anything else, then run `cd "$HOME/.local/share/anime-game-launcher/Genshin Impact" && bash ../patch/380/patch_revert.sh`
3. Restart the launcher, run files repairer in its settings
4. Now you should be able to run the game

**Comment by labo-China** [comment]
I encountered the issue before and fixed it by reverting the patch.

**Comment by EvilBoi123** [comment]
i reverted the patch and disable the patch in the launcher, but now i encountered weird color glitch, but i'm closing this issue for now. 

![20-03](https://github.com/an-anime-team/an-anime-game-launcher/assets/102599991/cdd66bcc-6b51-419f-b7e2-2270979bb244)

Anyway, anyone know how to fix this one?

**Comment by EvilBoi123** [comment]
Oh nvm, i fix it by reinstalling dxvk. The issue is truly close now
