### ISSUE TITLE
Allow to use custom startup script

### ISSUE THREAD

**Issue by CHN-beta** [an-anime-team/an-anime-game-launcher#236]
Currently the launcher directly call `YuanShen.exe` to launch game. While there are some other useful tools to use with the game, for example the tools to remove additional bokeh effect in CN version from https://discord.gg/QACXBwP7.
Is there anyway to let the launcher call `launcher.bat` to launch the game, even without the patch is applied? So that users could freely use these tools under the hood.

**Comment by krypt0nn** [comment]
Can't you use game launching command setting in the launcher for this purpose?

```
%bash_command% <path to your script>
```

Although this will break some settings because e.g. borderless window setting applies additional arguments to the binary, but you can put them yourself

**Comment by krypt0nn** [comment]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/29639507/f4f9f8f9-daf9-4e52-8f52-69b6a404b44e)

**Comment by CHN-beta** [comment]
> Can't you use game launching command setting in the launcher for this purpose?
> 
> ```
> %bash_command% <path to your script>
> ```
> 
> Although this will break some settings because e.g. borderless window setting applies additional arguments to the binary, but you can put them yourself

Thanks, I did not know `%bash_command%` before.
