### ISSUE TITLE
Nobara 38 can't install the RPM

### ISSUE THREAD

**Issue by gforke97** [an-anime-team/an-anime-game-launcher#239]
Nobara 38 (Fedora 38) doesn't have the required GLIBC_2.38 version availabe because that is only released for Fedora 39 and up.
Is it possible to require a lower GLIBC Version?

**Comment by Mar0xy** [comment]
Please note that it says Fedora Rawhide and not Fedora 38 or 37 as this is intended due to the fact that we always tend to use bleeding edge stuff. If you want it on Fedora 38 please use flatpak
