### ISSUE TITLE
unable to install via flatpack error

### ISSUE THREAD

**Issue by jcv99** [an-anime-team/an-anime-game-launcher#243]
[org.gnome.Platform/x86_64/43](error: The application moe.launcher.an-anime-game-launcher/x86_64/master requires the runtime org.gnome.Platform/x86_64/43 which was not found) I don't find any solution in the internet.

Operating System: Fedora Linux 37
KDE Plasma Version: 5.27.6
KDE Frameworks Version: 5.108.0
Qt Version: 5.15.9
Kernel Version: 6.4.11-100.fc37.x86_64 (64-bit)
Graphics Platform: X11
Processors: 16 × Intel® Core™ i7-10700KF CPU @ 3.80GHz
Memory: 15.5 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070/PCIe/SSE2
Manufacturer: ASUS

**Comment by krypt0nn** [comment]
```sh
flatpak install org.gnome.Platform//43
```
