### ISSUE TITLE
Can't install on Feodra 38 with rpm command

### ISSUE THREAD

**Issue by xiaozhangup** [an-anime-team/an-anime-game-launcher#245]
[xiaozhangup@xiaozhangup Downloads]$ sudo rpm -i an-anime-game-launcher-3.8.0-1.5.x86_64.rpm
Error: Dependency check failed:
	libm.so.6(GLIBC_2.38)(64bit) is needed by an-anime-game-launcher-3.8.0-1.5.x86_64

**Comment by Mar0xy** [comment]
https://github.com/an-anime-team/an-anime-game-launcher/issues/239#issuecomment-1681335644
