### ISSUE TITLE
Is the patch not necessary anymore?

### ISSUE THREAD

**Issue by AlphaCraft9658** [an-anime-team/an-anime-game-launcher#246]
I have read that someone said, they heard the patch wasn't necessary since 3.8, but is that true? Is that why the references on this repository have been removed? Is it safe to play the game without patching it? What is the exact reasoning for this, as I haven't found any official statement on this?

**Comment by ch4og** [comment]
The patch integration has been removed from the v3.9 launcher, so it's pretty obvious that you don't need to patch.

**Comment by Mar0xy** [comment]
As the previous comment sent the screenshot I will close this issue and pin it for anyone who might ask in the future.
