### ISSUE TITLE
Launcher stuck at 3.7.4 with Lutris AAGL installation

### ISSUE THREAD

**Issue by NicksQ69** [an-anime-team/an-anime-game-launcher#249]
Greetings, I found the launcher by chance from the Lutris catalog. However, during the installation it seems that I don't get the latest version of the launcher. After checking, it seems that on the Lutris site the script provided downloads version 3.7.4, which is hard-coded. Is there a way to upgrade the launcher directly from Lutris, or do I have to start the installation all over again, adapted to my Linux distribution (and perhaps without using Lutris) ?
I'm asking because I find Lutris really useful, and I'd like to learn how to use it properly.

Thank you in advance and see you soon!

https://lutris.net/games/install/37358/view

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/47458849/754c7324-656e-4790-b0d3-7a3c30a94fc4)

**Comment by krypt0nn** [comment]
We don't contact with lutris scripts maintainers, so the project lives its own life there. Such issues are expected and we can't and won't affect them.
