### ISSUE TITLE
FR: Option to choose Steam proton prefixes

### ISSUE THREAD

**Issue by psydvl** [an-anime-team/an-anime-game-launcher#251]
For example, heroic launcher allow you to set installed in steam proton versions to launch games 
So, I'd like proton experimental to be used here

**Comment by Mar0xy** [comment]
We generally advise against using normal Proton here as it is meant to only be used via steam and not via any other launcher.

Please instead use Wine-GE (Normal wine meant for all applications with proton patches) or Proton-GE (same applies to Proton-GE as above)
