### ISSUE TITLE
[Bug] Release notes on "What's New" is not working

### ISSUE THREAD

**Issue by cassiofb-dev** [an-anime-team/an-anime-game-launcher#254]
Yo, thanks for making this amazing project! I'm using this for almost a year and this is the first bug I found. This really is an awesome work, hope it can keep going.

## Steps to reproduce

1. Open the launcher
2. Click on the 3 bars icon
3. Click on "About"
4. Click on "What's New"
5. The error on the image bellow appears

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/61878987/2406cf8c-c4cd-4fbd-9c50-9f7cb842be91)

## App Info

- Version: 3.9.0
- Source: Flatpak

```txt
Anime Launcher SDK: 1.11.0
Anime Game Core: 1.15.0

gtk: 4.8.3
libadwaita: 1.2.5
pango: 1.50.14
cairo: 1.16.0
```

## System Info

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/61878987/23729bbb-9058-43af-8a47-bc4aad8bda1b)

**Comment by Mar0xy** [comment]
This is not really a bug this is more so krypton being dumb dumb and doing this

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/8841466/bc0cfe92-ffd9-4e72-bbce-134255681143)

Which broke the parser instead of doing `(name)`.
