### ISSUE TITLE
游戏报数据异常

### ISSUE THREAD

**Issue by CleMooling** [an-anime-team/an-anime-game-launcher#257]
如题，未测试更换账号后是否会同样无法登录。
另外启动器提供了一个禁止监测数据的选项，并向系统执行了一个需要root权限的脚本，不知道能不能撤销，之前直接用wine启动游戏能正常登录，怀疑是这个脚本的问题。
If need, you can use Google Translate.

**Comment by mkrsym1** [comment]
The action that requires root just adds a couple lines to your `/etc/hosts`, which you can manually remove. However, I really doubt that it will help: I assume that you are talking about "数据异常，请重新登录游戏" specifically, and no one has figured out how to deal with it yet.

**Comment by CleMooling** [comment]
I changed a account not used for a long time, and it works, then I found this.&nbsp;





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月6日(周三) 下午5:53
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [an-anime-team/an-anime-game-launcher] 游戏报数据异常 (Issue #257)




 
The action that requires root just adds a couple lines to your /etc/hosts, which you can manually remove. However, I really doubt that it will help: I assume that you are talking about "数据异常，请重新登录游戏" specifically, and no one has figured out how to deal with it yet.

**Comment by CleMooling** [comment]
![Screenshot_2023-09-06-18-09-04-98_470b4cb16301e0e](https://github.com/an-anime-team/an-anime-game-launcher/assets/93636342/b4a0caae-dd0e-4253-8067-f996aef7378b)

**Comment by CleMooling** [comment]
"(Wine (The Wine Project))"

**Comment by mkrsym1** [comment]
That looks like a regular login notification. If you are concerned about "The Wine project", we are pretty sure that they do not care about it. However, this is not supposed to happen on Wine 8.0+, so you should upgrade.

**Comment by c02y** [comment]
This is a known issue for CN server players for quite a few months, after the second half banner is unlocked, CN server account will be banned to login on the Linux/macOS computer, you have to wait until the new version is released, then after the second banner is unlocked, your account will be banned again. I cannot take this anymore, since it happened to me today once again, so I gave up this game once for all.

Your account is fine, you can still play it on other platform such as Windows computer or mobile device. 

You can use another account on the Linux/macOS computer, but it is likely will also be banned.

**Comment by BakaJzon** [comment]
Same issue too!
It seems I can't login Genshin CN until 4.1, right?

So, What may happen if I remove mihoyo.com entries in `/etc/hosts`?

**Comment by c02y** [comment]
> Same issue too! It seems I can't login Genshin CN until 4.1, right?
> 
> So, What may happen if I remove mihoyo.com entries in `/etc/hosts`? A quick ban?

I play GI with Steam, without any patch or third-party launcher, no server related info in my `/etc/hosts`, I got banned as well.

**Comment by c02y** [comment]
@CleMooling Someone says `You should switch to Wine-Staging instead of a vanilla Wine, it reports your motherboard data correctly.`, not sure if you can do that in the AAGL, but you can check it out in the AAGL's settings.

**Comment by tilsgee** [comment]
> I play GI with Steam

teach me your ways. or is this just as simple as connect GI executable to proton?

**Comment by c02y** [comment]
> > I play GI with Steam
> 
> teach me your ways. or is this just as simple as connect GI executable to proton?

Very simple, load the official game setup exe file (downloaded from GI website) into Steam as non-steam game into your steam library, make it compatible using `Proton Experiemental`, run it, it will install the official launcher, then open the official launcher, download the game data, then, change the path of the setup exe file to the installed game exe file. Done, run and play it.

**Comment by mack-w** [comment]
> This is a known issue for CN server players for quite a few months, after the second half banner is unlocked, CN server account will be banned to login on the Linux/macOS computer, you have to wait until the new version is released, then after the second banner is unlocked, your account will be banned again. I cannot take this anymore, since it happened to me today once again, finally, I gave up this game once for all.
> 
> Your account is fine, you can still play it on other platform such as Windows computer or mobile device.
> 
> You can use another account on the Linux/macOS computer, but it is likely will also be banned.

May I infer from your reply that if I'm with CN server and I've logined once on Linux, the second time I try to login I would be banned on that device? This question is so annoying I've been searching for this problem with no good for ages

**Comment by c02y** [comment]
> > This is a known issue for CN server players for quite a few months, after the second half banner is unlocked, CN server account will be banned to login on the Linux/macOS computer, you have to wait until the new version is released, then after the second banner is unlocked, your account will be banned again. I cannot take this anymore, since it happened to me today once again, finally, I gave up this game once for all.
> > Your account is fine, you can still play it on other platform such as Windows computer or mobile device.
> > You can use another account on the Linux/macOS computer, but it is likely will also be banned.
> 
> May I infer from your reply that if I'm with CN server and I've logined once on Linux, the second time I try to login I would be banned on that device? This question is so annoying I've been searching for this problem with no good for ages

I may not be the `second time`, maybe the first day, or maybe a few days later after the second banner is unlocked, I don't know, I'm not even sure whether everyone on Linux/macOS is banned. 

What I know is you may be banned, sooner or later.

**Comment by BakaJzon** [comment]
Actually, It not a REAL ban. You can still play on smartphone, ps4, Windows and so on. You can't send email to mihoyo, "Hey, I'm just playing Genshin normally, let me play!".
Sadly, there's no solution, can't and won't fix, until the game is updated to next version (earlier/later).

I think this issue could be closed and pinned, no body can solve it. 👀
