### ISSUE TITLE
Endless game download

### ISSUE THREAD

**Issue by dasehak** [an-anime-team/an-anime-game-launcher#259]
I'm trying to download Genshin Impact, but the installation stops at 100%. If I open the archive, it appears to be corrupted. I tried re-downloading it 3 times.
[debug.log](https://p.darklab.sh/?cf04821f5965f493#6H2Jr1y7fPgnmwU6wDNf9axQ9WAn9teABc8DAabLopoE)

**Comment by HasbersHz** [comment]
same

**Comment by dasehak** [comment]
> same

You can download with wget the archive and unzip it. If the download hangs, you can try enabling VPN (I personally used Japanese).
