### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by Michaelpalacce** [an-anime-team/an-anime-game-launcher#26]
### Distro

Ubuntu 22.10

### Installation Type

Flatpak

### Describe the issue

After Upgrading to 22.10 for some reason I cannot launch the game. I press launch on the launcher, the button disappears and nothing happens

**Comment by Mar0xy** [comment]
Please provide some more information like launcher logs

**Comment by Michaelpalacce** [comment]
I've tried reinstalling it all, but to no avail

**Comment by Mar0xy** [comment]
> > Please provide some more information like launcher logs
> 
> How can I get the logs?

Enable show hidden files in your explorer then navigate to `.var/app/com.gitlab.KRypt0n_.an-anime-game-launcher/data/anime-game-launcher/logs` they are timestamped

**Comment by Originalimoc** [comment]
Same problem. On SteamOS Canary/Preview channel. There is no log created.
```.var/app/com.gitlab.KRypt0n_.an-anime-game-launcher/``` is created but no file inside.

**Comment by Mar0xy** [comment]
This issue will be marked as stale and closed as there has been no comment well over 2 months
