### ISSUE TITLE
stuck while configuring a prefix

### ISSUE THREAD

**Issue by msprestigepro** [an-anime-team/an-anime-game-launcher#263]
![Snapshot_2023-09-18_15-40-13](https://github.com/an-anime-team/an-anime-game-launcher/assets/114784063/607f504d-0fae-46ad-a469-4bef069e5186)
Stuck, and I don't know what to do to provide more details.

**Comment by frak0d** [comment]
had same issue, just kill all wine processes after about 5 minutes, it worked for me that way

**Comment by chenzhekl** [comment]
I am having the same problem and I cannot even see the Wine window.
