### ISSUE TITLE
stuck on 100%

### ISSUE THREAD

**Issue by gmankab** [an-anime-team/an-anime-game-launcher#265]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/73340745/380cf453-18c0-4d79-a733-88e1902636bd)

arch, package from aur

**Comment by fluffur** [comment]
you should just restart an anime game launcher 

at least it worked for me (also downloaded it from aur)

**Comment by DiCarl0** [comment]
How did you restart it?

I am doing the flatpak version following: https://www.youtube.com/watch?v=LBskaMC4b3Y

**Comment by gmankab** [comment]
i did not remember
