### ISSUE TITLE
Error unpacking zip archives, help pls!!!

### ISSUE THREAD

**Issue by legonnexon** [an-anime-team/an-anime-game-launcher#267]
```
  2023-09-27T03:05:55.960128Z ERROR anime_game_launcher::ui::main::download_diff: Unpacking failed: invalid Zip archive: Could not find central directory end       
    at src/ui/main/download_diff.rs:36

```

im using archlinux and i install from lutris.

**Comment by Razuuu** [comment]
debian trixie user, installed it from lutris too, have the same issue

**Comment by Foxushka** [comment]
Previously there was workaround to download zip from https://autopatchhk.yuanshen.com/client_app/download/pc_zip/20230916101725_v2XCKuuvzCVh3BdI/GenshinImpact_4.1.0.zip, but mihoyo decided (?) to no upload full zip this time. So only way now is manually download all 7 (.001, .002, .007) files and extract to your game folder via `7z x GenshinImpact_4.1.0.zip.001`  (and voice later, all links are available in https://sdk-os-static.hoyoverse.com/hk4e_global/mdk/launcher/api/resource?key=gcStgarh&launcher_id=10)

**Comment by legonnexon** [comment]
I clicked in repair and worked, thanks.
