### ISSUE TITLE
Error while loading shared libraries: libadwaita-1.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TheCheddarCheese** [an-anime-team/an-anime-game-launcher#274]
When running the launcher (installed through any means) I get this error, when I try to install through Flatpak I get 
```
Program moe.launcher.an-anime-game-launcher/x86_64/master requires runtime org.gnome.Platform/x86_64/45 which wasn't found
``` 
OS: Linux Mint 21 Cinnamon

**Comment by jakobfridesjo** [comment]
Try installing the runtime manually with `flatpak install org.gnome.Platform/x86_64/45`

**Comment by TheCheddarCheese** [comment]
alright it worked, thanks
