### ISSUE TITLE
Exact copy of #274 - can't see libadwaita-1.so.0, fails to launch main launcher exec.

### ISSUE THREAD

**Issue by MC26Paradox** [an-anime-team/an-anime-game-launcher#276]
Sorry to make another report about this less than 24 hours after you close it for someone else - I have what appears to be an identical problem to #274, but without the same solution.

Notably, we had the following in common: (extra detail is my own)
- Linux Mint 21.2, Cinnamon desktop, x86_64 system
- `Error while loading shared libraries: libadwaita-1.so.0: cannot open shared object file: No such file or directory` as the exact error
- Issue persists across sources, tested installing via Lutris and the Flatpak repo listed in the GitHub wiki -> Installation

Not sure where the Flatpak logs are, Lutris log had little of note - found the actual error via starting the launcher directly (in a terminal), going by the Lutris launch location.

> (Note: install via Lutris was hardcoded to 3.9.1 a bit under 3 days before install, newer than #249 reports, and is latest for the last 2 weeks as of writing)

> (edited: wrote 45 here instead of 44, both are installed)

`flatpak install org.gnome.Platform/x86_64/44` reported it was already installed, and the actual library does exist in:
`/var/lib/flatpak/runtime/org.gnome.Platform/x86_64/44/active/files/lib/x86_64-linux-gnu/libadwaita-1.so.0`

I also have a version on 45 instead of 44 (unsure what it refers to, I don't use Flatpak much), an i386 compat version for some reason, and `libadwaita.so` in both Lutris and `/usr/lib/` that appear to be part of `gtk-2.0` (probably not relevant)

The... "correct" one at the full path above is R/W by the root user, and read-only by the root group, and is marked executable.

I would imagine said permissions is the root cause - worth having the extra info available after this is closed for the next person searching here, and I can't exactly blindly trust running the launcher as root, nor making that library visible to more than default, so it's still unsolved from my end.

**Comment by jakobfridesjo** [comment]
What happens if you launch the flatpak version with `flatpak run moe.launcher.an-anime-game-launcher`?

**Comment by MC26Paradox** [comment]
Guess my notifs weren't working, oops

That launches fine, which i'm betting is related to the needed lib being available in my local Flatpak.

Reinstalled both Flatpak and Lutris versions, Lutris has the same issue as before.

Only relevant error in the Lutris log is `Failed to register: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown`, but i'm not sure that's actually related

So I guess the actual problem is "Native install can't see Flatpak library dependency" - tested via the direct exec I didn't notice before, and got the same.

I'll leave it up to you if we close this as Flatpak works (as long as I go manually make a shortcut for easier access), or we rename the issue to the quote above and try to figure out why native builds can't read Flatpak libs.

**Comment by MC26Paradox** [comment]
Update: I got around to installing Genshin on the working Flatpak version, only to find out i'm affected by flatpak/flatpak-builder#550 (bwrap can't get namespace perms within Flatpak, even when allowed system-wide)

So I can't sandbox (via the launcher) within Flatpak, and native versions of the launcher can't see the library within Flatpak from the outside...

Guess I need to either get `libadwaita` installed natively, or we figure out one of those problems.

**Comment by krypt0nn** [comment]
Sandboxing feature is the same as what flatpak does by itself. You don't need to use it in flatpak builds
