### ISSUE TITLE
Error 10351-4001： 机器环境异常，请重启机器

### ISSUE THREAD

**Issue by BakaJzon** [an-anime-team/an-anime-game-launcher#284]
CN server

When I played this game for about 30s-1min (which means I can login and open the door), it popped out to tell me reboot my computer. Still, it prevents me playing this game after I reboot my computer again and again. (SINCE today)
![图片](https://github.com/an-anime-team/an-anime-game-launcher/assets/55239052/86367bc9-759c-46f1-aabf-c1246e3d50f1)
[config.json](https://github.com/an-anime-team/an-anime-game-launcher/files/12984794/config.json)
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/12984795/debug.log)

**Comment by krypt0nn** [comment]
First time seeing this error code. Try to run the game repairer. Also people report that latest wine-ge-proton builds create broken wine prefixes, so you can try to delete the prefix folder and create it with older builds (download and select another wine version, close the launcher, delete `prefix` folder from the launcher's folder, open launcher again and.let it recreate the prefix)

**Comment by c02y** [comment]
I'm plaything the game under Steam which is nothing related to this launcher, it happens every time (about 3 times in recent days) around 30s-1min after I login the game, but when I'm back to the login window (without rebooting my computer or closing the game window), I login again, the game runs without any issue.

**Comment by kamikaze211** [comment]
> I'm plaything the game under Steam which is nothing related to this launcher, it happens every time (about 3 times in recent days) around 30s-1min after I login the game, but when I'm back to the login window (without rebooting my computer or closing the game window), I login again, the game runs without any issue.

Same as you.
I got this issue since yesterday, but what I should say is that, it seems to be an issue only happens with CN server?
Another issue about CN server before 4.1 is that, when the second gacha comes in every big version of Genshin, the game will give you a "Data error", and prevent you to log in.
Now, everything is OK, but it changes to "Error 10351-4001", even though, we can still play Genshin on linux.

**Comment by c02y** [comment]
> > I'm plaything the game under Steam which is nothing related to this launcher, it happens every time (about 3 times in recent days) around 30s-1min after I login the game, but when I'm back to the login window (without rebooting my computer or closing the game window), I login again, the game runs without any issue.
> 
> Same as you. I got this issue since yesterday, but what I should say is that, it seems to be an issue only happens with CN server? Another issue about CN server before 4.1 is that, when the second gacha comes in every big version of Genshin, the game will give you a "Data error", and prevent you to log in. Now, everything is OK, but it changes to "Error 10351-4001", even though, we can still play Genshin on linux.

Yeah, I was playing both the CN server and other server, this issue happens on the CN server, I haven't played the non-CN server for a while, not sure about the situation on the non-CN server, but I'm sure about that the `Data error` window only occurs on the CN server.

About the `Data error` window, it happens right after or a few days delayed once the second banner is unlocked. Let's wait for a few days. I sincerely hope that the CN server maintainers of the game show some mercy for the Linux/macOS players, since they already repeatedly banned our Linux/macOS device for quite a few months, I was even thinking that they are enjoying playing with CN server Linux/macOS players.

**Comment by kamikaze211** [comment]
It seems to be fixed by 4.2 version.
I have played 4.2 for 2 days, no longer to see this error.
But still cannot confirm if the "data error" will come back.

**Comment by c02y** [comment]
> It seems to be fixed by 4.2 version. I have played 4.2 for 2 days, no longer to see this error. But still cannot confirm if the "data error" will come back.

Wait for the phase 2 banner.

**Comment by kamikaze211** [comment]
OK, after 3days , I got this message "Error 10351-4001： 机器环境异常，请重启机器" again.

**Comment by BakaJzon** [comment]
The (temporary) resolution still helps:
1. DON'T restart anything 
2. press the button and back to door
3. login again and have fun! Aha

At least, we can play this game.

**Comment by redapple0204** [comment]
I am concerned about the possibility of being banned after this error message pops up while attempting to continue playing the game. After all, the error clearly indicates that there is an abnormality with the machine, which could provide a legitimate reason for a ban. If I were banned for 10 years because of this, I feel like it would not be worth it. It would be better to play on Windows or on a smartphone instead.

**Comment by c02y** [comment]
> I am concerned about the possibility of being banned after this error message pops up while attempting to continue playing the game. After all, the error clearly indicates that there is an abnormality with the machine, which could provide a legitimate reason for a ban. If I were banned for 10 years because of this, I feel like it would not be worth it. It would be better to play on Windows or on a smartphone instead.

AFAIK no such kind of ban is reported so far just because you run the game on Linux/macOS.

**Comment by BakaJzon** [comment]
It seems to be fixed by 4.3 version.
I have played 4.3 for 3 days, no longer to see this error.
But still cannot confirm if the "data error" will come back.

**Comment by Kimiblock** [comment]
Weird, still happens to me.

What changed is that the popup comes up later than previous versions

**Comment by kamikaze211** [comment]
> It seems to be fixed by 4.3 version. I have played 4.3 for 3 days, no longer to see this error. But still cannot confirm if the "data error" will come back.

Need more time to confirm that if this report message will come back or not.
As our experience before, the report message will not show in several days after a new big version update, but ater some days, it always came back.

**Comment by Kimiblock** [comment]
Yeah, the popup doesn't go away even after I entered the door twice.

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/61745317/9d9dc4f6-0f65-4c8f-a069-648228d2b779)

**Comment by aaaaaQIE** [comment]
I encountered this issue when using the latest Proton and DXVK. The problem was resolved when I switched the Wine version to Wine-GE-Proton 8-20 and the DXVK version to dxvk-2.1.

**Comment by kamikaze211** [comment]
Now it is happening on CN server linux players.
I recieved several reports today at #archlinux-cn-genshin group on telegram.
We tried to change to ge-proton, and rebuild the prefix, but not work at all.
It seems that we (CN players) have to use Windows to play GI.
We are back to this time : https://notabug.org/Krock/dawn/issues/401

**Comment by c02y** [comment]
> Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401

It is always cn server issue, global servers never have any kind of this.
We thought it is finally fixed in previous patches, but now it seems, cn server maintainers are saying: "Miss me? We miss you."

**Comment by CHN-beta** [comment]
> Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401

same issue

**Comment by 940842546** [comment]
> Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401

the same issue, it happens every several minutes

**Comment by littlewu2508** [comment]
> > Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401
> 
> the same issue, it happens every several minutes

I have posted a potential solution at https://notabug.org/Krock/dawn/issues/401#issuecomment-40652

**Comment by CHN-beta** [comment]
> > > Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401
> > 
> > 
> > the same issue, it happens every several minutes
> 
> I have posted a potential solution at https://notabug.org/Krock/dawn/issues/401#issuecomment-40652

works on my machine

**Comment by 940842546** [comment]
> > > Now it is happening on CN server linux players. I recieved several reports today at #archlinux-cn-genshin group on telegram. We tried to change to ge-proton, and rebuild the prefix, but not work at all. It seems that we (CN players) have to use Windows to play GI. We are back to this time : https://notabug.org/Krock/dawn/issues/401
> > 
> > 
> > the same issue, it happens every several minutes
> 
> I have posted a potential solution at https://notabug.org/Krock/dawn/issues/401#issuecomment-40652

worked for me too

**Comment by StarChenPy** [comment]
Today is 2024/1/18, and I haven't encountered this issue.

**Comment by kamikaze211** [comment]
> Today is 2024/1/18, and I haven't encountered this issue.

It was fixed on 2024/1/17.
Seems that many windows users also got the same error report, so Mihoyo fixed it.

**Comment by TsubakiDev** [comment]
If you encounter this problem again in the future, please direct the 4 URLs reported by Genshin Impact to 0.0.0.0, which should solve the problem.

**Comment by BakaJzon** [comment]
Any new ban?

**Comment by redapple0204** [comment]
Does it seem like the issue has resurfaced again?

**Comment by c02y** [comment]
> Does it seem like the issue has resurfaced again?


It happens twice a few days ago, works normally without this issue after that.

But It can't be launched using Steam anymore since yesterday which is weird, I've been launching it using Steam for quite some time. It is OK if you are using https://github.com/an-anime-team/anime-games-launcher

**Comment by kamikaze211** [comment]
There are now about 2 ways to bypass the 4001 error.

One is to reconnect the network when login in to the big world after opening the door.
Here is a way to STOP the game and CONTINUE, then you will reconnect the network.
You can simply bind this shell script as a hotkey to use it.

```
kill -STOP $(pgrep YuanShen.exe) && \
    sleep 90 && \
    kill -CONT $(pgrep YuanShen.exe)
```

Another one is, add the cloud game parameter, to get a MOBILE UI.
But notice that you need a gamepad to change the controlling device from the mobile tapping screen to the keyboard or gamepad.
```
use_mobile_platform -platform_type CLOUD_THIRD_PARTY_MOBILE -is_cloud 1
```

**Comment by kamikaze211** [comment]
the newest one is 
```
 -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
```

**Comment by c02y** [comment]
> the newest one is
> 
> ```
>  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> ```
> 
> no need to use a gamepad anymore.

How can I add this if I use Steam?

**Comment by kamikaze211** [comment]
> > the newest one is
> > ```
> >  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > no need to use a gamepad anymore.
> 
> How can I add this if I use Steam?

```
%command%  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
```

**Comment by tuwibu** [comment]
> > > the newest one is
> > > ```
> > >  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > no need to use a gamepad anymore.
> > 
> > 
> > How can I add this if I use Steam?
> 
> ```
> %command%  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> ```

its work for me, tks

**Comment by 1ryb** [comment]
> the newest one is
> 
> ```
>  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> ```
> 
> no need to use a gamepad anymore.

Sorry I'm not very tech savvy, but can you explain a bit about exactly what this does? Is it related to the [cloud gaming version of the game](https://cloudgenshin.hoyoverse.com/en-us)? Because as far as I'm aware that version costs extra to play and you have to wait in queue sometimes to play it.

I'm having this error too and this does seem to work, I'm just curious why it's happening and how it bypasses the problem.

**Comment by feltryzyke** [comment]
How about when using an anime game launcher?

**Comment by AhanafRASHID** [comment]
> > the newest one is
> > ```
> >  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > no need to use a gamepad anymore.
> 
> Sorry I'm not very tech savvy, but can you explain a bit about exactly what this does? Is it related to the [cloud gaming version of the game](https://cloudgenshin.hoyoverse.com/en-us)? Because as far as I'm aware that version costs extra to play and you have to wait in queue sometimes to play it.
> 
> I'm having this error too and this does seem to work, I'm just curious why it's happening and how it bypasses the problem.

I won't go that far. I believe you barely understood the driver and detection process. The thing is we are just identifying as Cloud Users Instead of Windows users. There is no crime identifying since we are not actually using cloud services. This makes the server ignore the environment difference between wine and windows.

**Comment by Av4nz** [comment]
> How about when using an anime game launcher?

Go to the launcher setting. Click the "Enhancements" tab at the top of the settings window. Click the "Environment" in the Options section. Then paste the command into the "Game command" field.

use this command as mentioned above
`%command%  -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1`

**Comment by feltryzyke** [comment]
Hi, 
Happy Holidays! 
Just wanted to thank you @Affan Arfani Arifin. Your instruction works perfectly fine to me. I can now play GI again on my deck countless hours. 
Thank you again. 

Regards, 
feltryzyke

Yahoo Mail: Search, Organize, Conquer 
 
  On Wed, Dec 25, 2024 at 11:25 pm, Affan Arfani ***@***.***> wrote:   



How about when using an anime game launcher?


Go to the launcher setting. Click the "Enhancements" tab at the top of the settings window. Click the "Environment" in the Options section. Then paste the command into the "Game command" field.

use this command as mentioned above
%command% -platform_type CLOUD_THIRD_PARTY_PC -is_cloud 1

**Comment by kamikaze211** [comment]
目前5.5版本初期，在archlinux系统上无需断网启动（之前几个版本不断网无法运行游戏），无需修改hosts（之前某个版本不屏蔽dispatch域名无法运行游戏），无需添加云游戏参数（之前多个版本会弹窗10351-4001/15-4001），可以正常游戏。
目测是版本初期没有进行云控，不知道能持续到什么时候，此回复仅作留档参考。

**Comment by go11001100** [comment]
可能有转机了，今天测试没弹窗
之前弹10351-4001我这边是sd用户，今天测试发现没有弹窗了，麻烦测试一下？
不过我这边是断网启动的。

**Comment by kamikaze211** [comment]
6月19~20日，开始陆续有15-4001弹窗报错，表现和上版本（5.6）一致。
这两天关注一下，是否会和上版本一样，第二天就不继续弹了。
