### ISSUE TITLE
Cant use existed installation (os error 2)

### ISSUE THREAD

**Issue by NaufalF22** [an-anime-team/an-anime-game-launcher#286]
so i just copy paste existed genshin installation from my windows PC and gave me error like screenshot (os error 2)
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/63091744/5bcc0173-1122-43bb-a38b-6840e438959e)
I use yay AUR version 

here the debug log
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/13194154/debug.log)

Also you can open game folder from the launcher

**Comment by frak0d** [comment]
i have the same issue after i used official launcher to update the game (event update was failing with this launcher)

**Comment by NaufalF22** [comment]
Change config file (what i highlight) to "Genshin Impact game" because this is old instalaltion
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/63091744/3bbbefda-00ce-4b2d-9831-131616976e4e)
