### ISSUE TITLE
When i open aagl, its size isint like my display

### ISSUE THREAD

**Issue by liyaowhen** [an-anime-team/an-anime-game-launcher#289]
I use laptop btw, and this only happened after I connected it to a TV then disconnected it.

![1699320788321292074499865618582](https://github.com/an-anime-team/an-anime-game-launcher/assets/72400519/4d256f3f-0f7a-4701-8738-0cd817cb92e9)

As you can see it is a little less wide than my display and too tall to be displayed.

I tried many things like adding border to the window but still no good result

**Comment by krypt0nn** [comment]
Alt + Enter

**Comment by liyaowhen** [comment]
Thx, it works now
