### ISSUE TITLE
[Issue]: Doesn't work after added to Steam Libarary

### ISSUE THREAD

**Issue by lexiangmeng** [an-anime-team/an-anime-game-launcher#29]
### Distro

Steam OS/ Arch Linux

### Installation Type

Flatpak

### Describe the issue

The launcher works well in Desktop mode.
However, after adding it to Steam Library, it doesn't work neither start through desktop mode steam or gaming mode steam.
The launcher could start, but after pressing start the game, the launcher disappear. Few seconds later, the launcher is back but game hasn't been started.

I have tried reapply the patch and fix game, but doesn't work.

Server: cn
Wine-GE Proton ver. 29
DXVK 1.10.3
All other settings keep default

Thanks!

### Reproduction Steps

Install via flatpak
Change server to cn
Download wine and the game
Apply the patch
Add "An anime game launcher" to steam in desktop mode
Start it in Desktop Steam or Gamemode Steam.

**Comment by lexiangmeng** [comment]
After reimage the Steam OS and reinstall Launcher.
Neither desktop nor gamemode works.
After pressing Start in launcher, I could see the process of Yuanshen.exe. But the process disappear soon. It seems that the game crashed, but there is no error log in game directory.
Launcher log as attached.

[latest.log.txt](https://github.com/an-anime-team/an-anime-game-launcher/files/9884536/latest.log.txt)

**Comment by Bluefissure** [comment]
For CN client:

1. Open `~/.steam/steam/ubuntu12_32/steam-runtime/run.sh`, scroll to the last line, add `LC_CTYPE=en_US.utf8 LC_ALL=en_US.utf8 ` to the front
2. Open the propoties of AAGL in steam, add `LC_CTYPE=en_US.utf8 LC_ALL=en_US.utf8 %command% ` to the front of launching arguments

**Comment by Mar0xy** [comment]
As Bluefissure instructions show this should let the steam deck launch the CN version of the game having to edit the `run.sh` file though shows that this is mainly an issue on Steam's part not being able to handle the CN locale properly.
