### ISSUE TITLE
Prevent cursor from leaving game window on multimonitor setup

### ISSUE THREAD

**Issue by ShiftHackZ** [an-anime-team/an-anime-game-launcher#295]
I have a desktop computer with triple monitor setup (every monitor has 1920x1080 resolution), game runs at the main monitor located between other two at center (it is monitor marked as "3" on the scheme below):

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/41302477/a754bb4e-062c-4764-a48d-5dc7e8e25883)

### Issue description 

Sometimes occasionally cursor is able to leave the bounds of game window and appear either on the left or right monitor, and if I press Left Mouse Button (for example to attack the enemy in game) then game window will minimize. 

It is the most problematic while trying to complete weekly boss, because there is no way to pause the fight, and I have to quickly Alt+Tab to game window again and hope that I did not lost HP or killed by one-shot at the time when game was minimized.

Please, suggest is there any way to fix this, for example by somehow preventing mouse cursor to leave the game window bounds? 

### OS Details

```
OS: EndeavourOS 
DE: GNOME 45.1 running on Wayland
Kernel: 6.1.62-1-lts
```

### Hardware

```
CPU: Intel i9-10850K (20) @ 5.200GHz
GPU: AMD Radeon RX 6750 XT
```

### Launcher
```
Version: AUR v3.9.2
Game (Genshin) v4.2.0 Global PC
Wine-GE-Proton 8.22
DXVK 2.3 (Vanilla)
```

**Comment by krypt0nn** [comment]
Will be fixed in the next update

**Comment by KremlinDusk** [comment]
This issue is recurring. Can this be looked into?
