### ISSUE TITLE
[Issue]: 

### ISSUE THREAD

**Issue by NeetXuu** [an-anime-team/an-anime-game-launcher#30]
### Distro

SteamOS 3.3.2 on SteamDeck

### Installation Type

Flatpak

### Describe the issue

Game can't work without terminal on and can't work at all at gaming mode
wine error code:

Unhandled exception: page fault on read access to 0xffffffffffffffff in 64-bit code (0x00000001816be2bb).
Register dump:
 rip:00000001816be2bb rsp:000000000011a1a0 rbp:0000000000000000 eflags:00010202 (  R- --  I   - - - )
 rax:0000000000000001 rbx:0000000000000000 rcx:0000000000000005 rdx:0000000000000000
 rsi:0000000000000000 rdi:0000000000000000  r8:0000000000000000  r9:0000000000000000 r10:00000000002603d0
 r11:0000000170088cd8 r12:000000000011ac70 r13:000000000011ae30 r14:0000000000000000 r15:000000000011acf0
Stack dump:
0x000000000011a1a0:  0000000000000578 00000000003c0050
0x000000000011a1b0:  0000000181bd9978 00000001816e0ba4
0x000000000011a1c0:  0000000000000000 00000001816be252
0x000000000011a1d0:  0000000181bd9978 0000000000000000
0x000000000011a1e0:  0000000181bd9978 00000001816dde51
0x000000000011a1f0:  0000000000000000 000000a800000000
0x000000000011a200:  000000000011ad00 00000001816be26d
0x000000000011a210:  0000000181bd9978 000000000011a840
0x000000000011a220:  000000000011a8c8 0000000181bd9978
0x000000000011a230:  0000000000000000 000000000011a270
0x000000000011a240:  000000000011f900 00000001816ecad8
0x000000000011a250:  9cb0046730422fad 68a5bf0ebac02a9d
Backtrace:
=>0 0x00000001816be2bb UnityMain+0x5eb40b() in unityplayer (0x0000000000000000)
  1 0x00000001816be252 UnityMain+0x5eb3a2() in unityplayer (0x0000000000000000)
  2 0x00000001816be26d UnityMain+0x5eb3bd() in unityplayer (0x000000000011a840)
  3 0x00000001816ecad8 UnityMain+0x619c28() in unityplayer (0x000000000011a840)
  4 0x00000001816def65 UnityMain+0x60c0b5() in unityplayer (0x000000000011a840)
  5 0x00000001816bebf1 UnityMain+0x5ebd41() in unityplayer (0x000000000011a840)
  6 0x00000001816be312 UnityMain+0x5eb462() in unityplayer (0x000000000011a840)
  7 0x00000001816c1871 UnityMain+0x5ee9c1() in unityplayer (0x000000000011a840)
  8 0x00000001809bded7 in unityplayer (+0x9bded7) (0x0000000000000005)
  9 0x00000001809be0da in unityplayer (+0x9be0da) (0x000000017006ca70)
  10 0x00000001810c26bf in unityplayer (+0x10c26bf) (0x000000017006ca70)
  11 0x000000007b013a45 AccessCheckByTypeAndAuditAlarmW+0x7cf5() in kernelbase (0x000000017006ca70)
  12 0x0000000170025a22 A_SHAFinal+0x3a52() in ntdll (0x000000017006ca70)
  13 0x0000000170060155 A_SHAFinal+0x3e185() in ntdll (0x000000017006ca70)
  14 0x000000017005a411 A_SHAFinal+0x38441() in ntdll (0x000000017006ca70)
  15 0x000000017005ab29 A_SHAFinal+0x38b59() in ntdll (0x000000017007c8c9)
  16 0x00000001700586ae A_SHAFinal+0x366de() in ntdll (0x000000000011bac0)
  17 0x00000001816be2bb UnityMain+0x5eb40b() in unityplayer (0x0000000000000000)
  18 0x00000001816be252 UnityMain+0x5eb3a2() in unityplayer (0x0000000000000000)
  19 0x00000001816be26d UnityMain+0x5eb3bd() in unityplayer (0x000000000011c180)
  20 0x00000001816ecad8 UnityMain+0x619c28() in unityplayer (0x000000000011c180)
  21 0x00000001816def65 UnityMain+0x60c0b5() in unityplayer (0x000000000011c180)
  22 0x00000001816bebf1 UnityMain+0x5ebd41() in unityplayer (0x000000000011c180)
  23 0x00000001816be312 UnityMain+0x5eb462() in unityplayer (0x000000000011c180)
  24 0x00000001816c1871 UnityMain+0x5ee9c1() in unityplayer (0x000000000011c180)
  25 0x00000001809bded7 in unityplayer (+0x9bded7) (0x0000000000000005)
  26 0x00000001809be0da in unityplayer (+0x9be0da) (0x000000000011c299)
  27 0x00000001810ce06e in unityplayer (+0x10ce06e) (0x000000000011c299)
  28 0x00000001811eaee4 UnityMain+0x118034() in unityplayer (0x000000017006ca70)
  29 0x00000001811ead61 UnityMain+0x117eb1() in unityplayer (0x000000017006ca70)
  30 0x00000001810c2710 in unityplayer (+0x10c2710) (0x000000017006ca70)
  31 0x000000007b013a45 AccessCheckByTypeAndAuditAlarmW+0x7cf5() in kernelbase (0x000000017006ca70)
  32 0x0000000170025a22 A_SHAFinal+0x3a52() in ntdll (0x000000017006ca70)
  33 0x0000000170060155 A_SHAFinal+0x3e185() in ntdll (0x000000017006ca70)
  34 0x000000017005a411 A_SHAFinal+0x38441() in ntdll (0x000000017006ca70)
  35 0x000000017005ab29 A_SHAFinal+0x38b59() in ntdll (0x000000017007c8c9)
  36 0x00000001700586ae A_SHAFinal+0x366de() in ntdll (0x000000000011ef80)
  37 0x00000001816be2bb UnityMain+0x5eb40b() in unityplayer (0x0000000000000000)
  38 0x00000001816be252 UnityMain+0x5eb3a2() in unityplayer (0x0000000000000000)
  39 0x00000001816be26d UnityMain+0x5eb3bd() in unityplayer (0x000000000011f640)
  40 0x00000001816ecad8 UnityMain+0x619c28() in unityplayer (0x000000000011f640)
  41 0x00000001816def65 UnityMain+0x60c0b5() in unityplayer (0x000000000011f640)
  42 0x00000001816bebf1 UnityMain+0x5ebd41() in unityplayer (0x000000000011f640)
  43 0x00000001816be312 UnityMain+0x5eb462() in unityplayer (0x000000000011f640)
  44 0x00000001816c1871 UnityMain+0x5ee9c1() in unityplayer (0x000000000011f640)
  45 0x00000001809bded7 in unityplayer (+0x9bded7) (0x0000000000000005)
  46 0x00000001809be0da in unityplayer (+0x9be0da) (0x000000000011faa0)
  47 0x0000000180a99e07 in unityplayer (+0xa99e07) (0x000000000011faa0)
  48 0x0000000180a99f98 in unityplayer (+0xa99f98) (0x000000000011faa0)
  49 0x0000000180888136 in unityplayer (+0x888136) (0x000000000011fc99)
  50 0x00000001810d23eb in unityplayer (+0x10d23eb) (0x000000000011fe00)
  51 0x00000001810d2ebb UnityMain+0xb() in unityplayer (0x0000000000000000)
  52 0x0000000140001207 ÁuÿNêÄ•åÀÅPÎÇte]]x «ä·Ù(Ëís(áû—J5Û¥*ö­^•ƒpäý«\iMø»zÕÌ&ý“•âJ¹¿£ìêx­`[V|äæ‰b¯>pDº§GñW'VW0ÍŽ$ãŒîDÙo:ÏŠvV'·Lb*ŸØ¬)8MJÓÇGSy­ÑÎßü½ÕØ$TI®6w•i­1¦·˜B}o
Î_ñ˜ËAîºÓÀ–ßîU¦¬gYÂÜö~ì¼¼wÇ~¢Ú0ÄÊDðºc©Ù/ÿV"
{íRC|â”³Í’×45^Á
k¹h÷ßWÏÊò¨WãyK<dvçwPfß)+0x1207() in yuanshen (0x0000000000000000)
  53 0x000000007b62c629 ActivateActCtx+0x21315() in kernel32 (0x0000000000000000)
  54 0x000000017005fb57 A_SHAFinal+0x3db87() in ntdll (0x0000000000000000)
0x00000001816be2bb unityplayer+0x16be2bb: int	$0x29
Modules:
Module	Address					Debug info	Name (58 modules)
PE	0000000001e70000-00000000039c2000	Deferred        mhypbase
PE	0000000011dd0000-000000001d30d000	Deferred        userassembly
PE	000000007a850000-000000007a854000	Deferred        opengl32
PE	000000007b000000-000000007b0da000	Export          kernelbase
PE	000000007b600000-000000007b816000	Export          kernel32
PE	0000000140000000-0000000140521000	Export          yuanshen
PE	0000000170000000-00000001700a4000	Export          ntdll
PE	0000000180000000-0000000182262000	Export          unityplayer
PE	00000001c69e0000-00000001c7321000	Deferred        shell32
PE	00000001c8b40000-00000001c8b60000	Deferred        msacm32
PE	00000001c8db0000-00000001c8e46000	Deferred        msvcrt
PE	00000001d97a0000-00000001d97a7000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	00000001dd3f0000-00000001dd4bd000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec2d5000	Deferred        ws2_32
PE	00000001f51e0000-00000001f51f0000	Deferred        hid
PE	00000001fdfd0000-00000001fdff8000	Deferred        wintrust
PE	0000000215450000-0000000215457000	Deferred        api-ms-win-security-systemfunctions-l1-1-0
PE	000000021a7e0000-000000021a857000	Deferred        setupapi
PE	0000000226310000-0000000226317000	Deferred        api-ms-win-core-string-l1-1-0
PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4
PE	000000023d820000-000000023da6d000	Deferred        user32
PE	0000000240030000-000000024005e000	Deferred        iphlpapi
PE	000000024dc40000-000000024dc48000	Deferred        api-ms-win-appmodel-runtime-l1-1-1
PE	000000025cf30000-000000025cf38000	Deferred        api-ms-win-core-winrt-string-l1-1-0
PE	000000026b4c0000-000000026b53b000	Deferred        gdi32
PE	00000002739c0000-0000000273af7000	Deferred        oleaut32
PE	000000028dfa0000-000000028dfac000	Deferred        nsi
PE	000000028ebe0000-000000028ebe8000	Deferred        api-ms-win-core-sysinfo-l1-2-1
PE	0000000297900000-0000000297912000	Deferred        aclui
PE	000000029cfc0000-000000029cfd6000	Deferred        dnsapi
PE	000000029ea80000-000000029ea87000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	00000002a4090000-00000002a409e000	Deferred        wtsapi32
PE	00000002ba290000-00000002ba298000	Deferred        api-ms-win-core-winrt-l1-1-0
PE	00000002bb750000-00000002bb891000	Deferred        comctl32
PE	00000002bc640000-00000002bc650000	Deferred        imagehlp
PE	00000002d4d40000-00000002d4d57000	Deferred        bcrypt
PE	00000002de970000-00000002de9a2000	Deferred        rsaenh
PE	00000002e3540000-00000002e3591000	Deferred        shlwapi
PE	00000002e8f10000-00000002e902b000	Deferred        ole32
PE	00000002f1fa0000-00000002f1fad000	Deferred        version
PE	00000002fa030000-00000002fa037000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	000000030c980000-000000030c988000	Deferred        api-ms-win-core-synch-l1-2-0
PE	00000003126f0000-0000000312709000	Deferred        shcore
PE	0000000316370000-000000031637b000	Deferred        psapi
PE	0000000316ce0000-0000000316ce9000	Deferred        api-ms-win-core-com-l1-1-1
PE	0000000327020000-0000000327073000	Deferred        combase
PE	000000032a700000-000000032a72a000	Deferred        sechost
PE	0000000330260000-000000033029f000	Deferred        advapi32
PE	0000000346ba0000-0000000346bc1000	Deferred        jsproxy
PE	0000000351680000-0000000351688000	Deferred        api-ms-win-core-localization-l1-2-1
PE	0000000358120000-0000000358164000	Deferred        winhttp
PE	0000000375610000-0000000375648000	Deferred        win32u
PE	0000000399110000-000000039911c000	Deferred        wlanapi
PE	00000003af670000-00000003af72f000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd1a000	Deferred        imm32
PE	00000003b8f00000-00000003b8fc1000	Deferred        winmm
PE	00000003be590000-00000003be606000	Deferred        dbghelp
PE	00007fa059dc0000-00007fa059dc4000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000020 start.exe
	["C:\windows\system32\start.exe" /exec explorer /desktop=animegame,1280x800 launcher.bat -screen-fullscreen 0 -popupwindow]
	00000024    0
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0
	00000040    0
	0000004c    0
	0000005c    0
	00000078    0
	000000a0    0
	000000c0    0
	000000e8    0
	00000108    0
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0
	00000054    0
	00000058    0
	00000068    0
	000000f4    0
00000060 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000064    0
	00000090    0
	00000094    0
00000070 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000074    0
	0000007c    0
	00000080    0
	00000084    0
	00000088    0
	0000008c    0
	000000b0    0
	000000b4    0
	000000b8    0
	000000bc    0
	000000e0    0
	000000e4    0
000000a8 plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000ac    0
	000000c4    0
	000000c8    0
	000000cc    0
	000000d0    0
000000d4 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000d8    0
	000000ec    0
	000000f0    0
000000f8 tabtip.exe
	["C:\windows\system32\tabtip.exe"]
	000000fc    0
	00000124    0
	00000128    0
00000100 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	00000104    0
	0000010c    0
	00000110    0
	00000114    0
	00000118    0
	0000011c    0
	00000148    0
	00000320    0
	00000324    0
0000012c explorer.exe
	["C:\windows\system32\explorer.exe" /desktop=animegame]
	00000130    0
	00000134    0
	00000138    0
	00000144    0
0000024c (D) Z:\run\media\mmcblk0p1\genshin\game\YuanShen.exe
	["Z:\run\media\mmcblk0p1\genshin\game\YuanShen.exe" -screen-fullscreen 0 -popupwindow]
	00000250    0 <==
	00000254    0
	0000026c    0
	00000270    0
	00000274    0
	00000278    0
	0000027c    0
	00000280    0
	00000288    0
	0000028c    0
	00000290    0
	00000294    0
	00000298    0
	0000029c    0
	000002a0    0
	000002a4    0
	000002a8    0
	000002ac    0
	000002b0    0
	000002b4    0
	000002b8    0
	000002bc    0
	000002c0    0
	000002c4    0
	000002c8    0
	000002cc    0
	000002d0    0
	000002d4    0
	000002d8    0
	000002dc    0
	000002e0    0
	000002e4    0
	000002e8    0
	000002ec    0
	000002f0    0
	000002f4    0
	000002f8    0
	000002fc   -1
	00000300    0
	0000030c    0
00000310 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000314    0
	00000318    0
	0000031c    0
System information:
    Wine build: wine-7.2-1-g29075a2e575 (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 5.13.0-valve21.3-1-neptune

**Comment by Mar0xy** [comment]
This was already reported on the Discord in a very extensive forum thread and up to this point no one has figured out why the **CN** version does this. So far other people think that this is an issue on Steam's end
