### ISSUE TITLE
[feature request] optional enable anticheat

### ISSUE THREAD

**Issue by gmankab** [an-anime-team/an-anime-game-launcher#308]
hello

since 3.8 game version, anticheat supports proton

can you please add optional ability to run game with anti cheat enabled, to 100% eliminate the possibility of ban

**Comment by Caliel666** [comment]
this is already the case, the current patch does nothing other than adding the telemetry block in the hosts files, you can just turn the patch off

**Comment by gmankab** [comment]
thank you
