### ISSUE TITLE
Fps Unlocker

### ISSUE THREAD

**Issue by YuryenUcahh** [an-anime-team/an-anime-game-launcher#310]
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/51506997/40787a3e-4951-491f-837e-67d199c1a7d2)

as a workaround I use the new fps unlocker version by adding it to lutris

**Comment by Sycko47** [comment]
Im also getting this same error

**Comment by KyroOW** [comment]
some details on how to achieve that would be appreciated, tried for a few hours but couldn't get the new version to detect the game via Lutris, also tried to replace AAGL' bundled .exe but it automatically redownloads it

**Comment by YuryenUcahh** [comment]
> can u explain in detail how u did that

i updated my game to 4.3 and fps unlocker getting this error  now i use fps unlocker version 2.2.0 as a workaround

**Comment by KyroOW** [comment]
> > can u explain in detail how u did that
> 
> i updated my game to 4.3 and fps unlocker getting this error now i use fps unlocker version 2.2.0 as a workaround

do you mind sharing how you did it in details ? i did add the latest version of fps unlocker through Lutris but it doesn't detect the game

**Comment by YuryenUcahh** [comment]
> > > can u explain in detail how u did that
> > 
> > 
> > i updated my game to 4.3 and fps unlocker getting this error now i use fps unlocker version 2.2.0 as a workaround
> 
> do you mind sharing how you did it in details ? i did add the latest version of fps unlocker through Lutris but it doesn't detect the game

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/51506997/96a2ffd2-dfb7-4395-ba72-b19458386138)

I put the new version next to the old one and now it uses the config file of the old version, it should probably detect it now

**Comment by krypt0nn** [comment]
Issue should be resolved now
