### ISSUE TITLE
Software not opening once installed

### ISSUE THREAD

**Issue by wispophobia** [an-anime-team/an-anime-game-launcher#312]
I've installed the launcher and it shows as an application in the application menu but when I open the shortcut nothing happends.

**Comment by wispophobia** [comment]
I'm using linux mint cinnamon, and I installed the launcher using the Pacstall method.

**Comment by krypt0nn** [comment]
We don't maintain pacstall installation script. Unfortunate to hear that is doesn't work but we can't do anything with it. Please consider using flatpak version instead.
