### ISSUE TITLE
Mouse not captured by game when using FPS Unlocker

### ISSUE THREAD

**Issue by Sonixier** [an-anime-team/an-anime-game-launcher#313]
When using fps unlocker, the mouse is not properly captured by the game and moves to the second screen. This makes the game unplayable. Works fine without fps unlocker however

**Comment by gdhsnlvr** [comment]
same

**Comment by hyperstown** [comment]
Same issue here. I haven't seen any issue similar to this on fps unlocker github repo so it could be only wine/proton thing. I don't have Windows machine to test it though.

**Comment by gdhsnlvr** [comment]
tried to run on hyprland with gamescope (run ok but 60fps ehh..). 

then with enabling fps unlocker found that it is tried to launch fps_unlocker.bat which is located in game folder with gamescope and it worked wrong, sound of game was playing but nothing showed. 

seems like it is trying to run gamescope ...args... fps_unlocker.bat 

any chance to separatly run game with gamescope and separatly run fps unlocker after game running? 

may be it will help to fix this on gnome where i have same problem

seems like fps unlocker injects into running process so what if we run game as if fps unlocker option is off, delay, and run fps unlocker to inject fps unlocking?

**Comment by Sonixier** [comment]
There seems to be some work ongoing to replace the fps unlocker with a new one:
https://github.com/an-anime-team/an-anime-game-launcher/pull/314
Maybe this will fix the issue

**Comment by gdhsnlvr** [comment]
> There seems to be some work ongoing to replace the fps unlocker with a new one: #314 Maybe this will fix the issue

just replacing exe fixed problem with mouse. works perfect on hyprland

**Comment by Sonixier** [comment]
The new fps unlocker fixes the problem. It just needs to get merged and new aagl version released
