### ISSUE TITLE
FPS Unlocker frequently trigger error 10351-4001

### ISSUE THREAD

**Issue by qwe795138426** [an-anime-team/an-anime-game-launcher#316]
CN server

When I enable FPS unlocker, it frequently trigger error 10351-4001, just like the duration that is triggered when starting the game. It cannot be eliminated by restarting the game. 
[config.json](https://github.com/an-anime-team/an-anime-game-launcher/files/13810337/config.json)
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/13810338/debug.log)

**Comment by mkrsym1** [comment]
I do not think that the unlocker is to blame here (see #284), but if you do, leave an issue on the unlocker repository: https://codeberg.org/mkrsym1/fpsunlock

**Comment by qwe795138426** [comment]
> I do not think that the unlocker is to blame here (see #284), but if you do, leave an issue on the unlocker repository: https://codeberg.org/mkrsym1/fpsunlock

I agree your idea, because after I reinstall the game, this problem has not been solved. But it actually appeared after I use the unlocker. I guess it maybe triggered a strange risk control mechanism. I 'll leave the issue.

**Comment by kamikaze211** [comment]
It had been reported at #archlinux-cn-genshin group on telegram.
We solved this by rebuild the prefix.
But on my experience, I suggest you to use ge-proton instead of wine or proton experimental.
I got this issue in last 3days, but I changed to ge-proton and deleted the prefix, then everything goes well now, just as before.

**Comment by kamikaze211** [comment]
Now it is happening on CN server linux players.
I recieved several reports today at #archlinux-cn-genshin group on telegram.
We tried to change to ge-proton, and rebuild the prefix, but not work at all.
It seems that we (CN players) have to use Windows to play GI.
We are back to this time : https://notabug.org/Krock/dawn/issues/401

coppied from 

[[me-launcher/issues/284](https://github.com/an-anime-team/an-anime-game-launcher/issues/284)
](https://github.com/an-anime-team/an-anime-game-launcher/issues/284)
