### ISSUE TITLE
[Feature Request]: Add a close button to close setting page

### ISSUE THREAD

**Issue by Bluefissure** [an-anime-team/an-anime-game-launcher#32]
### What the feature is suppose to do

Add a button to close the setting page and return to the launcher home page.

### Describe the reason behind the request

In steam deck game mode, there's no title bar for windows, and since there's only one window when we're on the setting page, there's no way to close the window but only to exit the whole game/application.

So it would be nice if we can add a close button to the bottom left corner of the setting page.

**Comment by krypt0nn** [comment]
![image](https://user-images.githubusercontent.com/29639507/199910579-9cea70c6-1455-494c-9d16-45595d6e5636.png)

**Comment by Bluefissure** [comment]
Completed in https://github.com/an-anime-team/an-anime-game-launcher/pull/21 but not released yet.
