### ISSUE TITLE
Game does not run well with `--run-game`, when predownload available

### ISSUE THREAD

**Issue by blmarket** [an-anime-team/an-anime-game-launcher#327]
https://github.com/an-anime-team/an-anime-game-launcher/blob/main/src/main.rs#L232

Because I didn't use `--just-run-game`, it will fall through match and go with `app.run()` which does not understand `--run-game` option and fails.

Can we add another match case when predownload available && run_game flag, and panic with some helpful message such as "hey, predownload available, do something other than --run-game (or --just-run-game if you really don't want to see the ui)"?

**Comment by krypt0nn** [comment]
This behavior is expected. Launcher should start if `--run-game` provided but some additional action is available

**Comment by krypt0nn** [comment]
Mkrsym explained the problem to me a bit, the launcher crashing issue will be fixed in the next update

**Comment by blmarket** [comment]
Can't find the fix from `next` branch. Let me know if you would welcome PR.
