### ISSUE TITLE
[Issue]: Download fail, but installation complete

### ISSUE THREAD

**Issue by NepPure** [an-anime-team/an-anime-game-launcher#33]
### Distro

Steam Deck

### Installation Type

Flatpak

### Describe the issue

![image](https://user-images.githubusercontent.com/12379907/199960480-a25eb6bd-77fa-4c27-84e2-9832c5cefb81.png)

Download fail, but installation complete.

I don't know much about Flatpack, is it possible to add some network retries.

### Reproduction Steps

Just install in high loss network.

Of course, after this, it will always be stuck on startup.

![2022-11-04_17-46](https://user-images.githubusercontent.com/12379907/199961091-693b481d-3bcb-4019-9838-9c6a51227394.png)

**Comment by krypt0nn** [comment]
I mean, if it launched and in the end of settings window you see latest available version - obviously it succeeded
Flatpak reduces amount of data needed to be downloaded by using already downloaded parts (previous app version). The same do applications on mobile phones
