### ISSUE TITLE
probably a dumb issue 

### ISSUE THREAD

**Issue by davidistheverybest** [an-anime-team/an-anime-game-launcher#330]
New to linux! My steam deck is struggling to install the game files for the launcher. It says that it requires 213.27 GB of storage to be free which is crazy! any help would be appreciated. I've added the debug log because thats what chatgpt said to do. Thank you for any help understanding and fixing this problem.

**Comment by Caliel666** [comment]
the launcher downloads the game in a zip file from their servers, and it needs space to extract it, so basically double the game size, there is a new downloader that isn't in the launcher yet that will fix it, but for now the only thing you can do is copy the game files from another pc, or clean up some space in the deck

**Comment by krypt0nn** [comment]
> it requires 213.27 GB of storage to be free which is crazy!

Welcome to the genshin impact. 

> I've added the debug log

You didn't. And it's not needed.
