### ISSUE TITLE
Error to start in deepin V23 Beta3

### ISSUE THREAD

**Issue by Mooling0602** [an-anime-team/an-anime-game-launcher#337]
Log:
/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by an-anime-game-launcher)
System info:
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/147964268/c12c81bd-67a5-499f-97b4-1f411be37258)
Other versions of deepin haven't tested yet.

**Comment by krypt0nn** [comment]
Use flatpak version instead.

**Comment by WRXinYue** [comment]
Glibc is a library that the entire operating system and almost all packages depend on, with its version fixed and all packages compiled against that version. In contrast, Flatpak packages do not depend on system libraries and have their own separate dependencies.
