### ISSUE TITLE
How i use different Session

### ISSUE THREAD

**Issue by Rajala1404** [an-anime-team/an-anime-game-launcher#338]
I have 3 Accounts i have created a session for each of them.
1. I logged into my 1. Account and then closed the Game and clicked on the Refresh (or something like that) icon for that session after this i switched to the 2. Session and have done the same thing but if i switch back to the 1. Session i am still logged in with the Account from the 2. Session So how i use this Feature

**Comment by krypt0nn** [comment]
This is misunderstanding from your side. What this "refresh" button does is updated your currently selected session from the wine prefix files, so basically overwrites your session by whatever account you used recently to play the game. You change your game account when you select the session in a dropdown menu. You don't need to press any other button

![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/29639507/54a5dbe9-1d0d-47ba-b298-358ac4815e4c)

**Comment by Rajala1404** [comment]
@krypt0nn Even if i do as you say, it still wouldn't work. i just get back logged in into my previous account.
