### ISSUE TITLE
Gtk Switches are in OFF position but with ON colours.

### ISSUE THREAD

**Issue by Samega7Cattac** [an-anime-team/an-anime-game-launcher#339]
Every switch that should be Active is in the OFF position but with ON colors.
Installed from AUR (bin package).

## Debug info
Anime Launcher SDK: 1.12.5
Anime Game Core: 1.17.4

gtk: 4.12.5
libadwaita: 1.4.4
pango: 1.52.0
cairo: 1.18.0

## Image
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/25128554/1a9312bb-d44d-4fd4-8d51-ae05ad94e35b)

**Comment by krypt0nn** [comment]
This is a known GTK bug and is not related to the launcher. If not mistaken the real state depends on the switch's color

**Comment by Samega7Cattac** [comment]
Is there any bug report I could look?
Bc I had a similar issue with one project and it was the signal being blocked on a callback
