### ISSUE TITLE
[Issue]: Game Mode Launch Not Working

### ISSUE THREAD

**Issue by Soggy-Pancake** [an-anime-team/an-anime-game-launcher#35]
### Distro

Steam Deck (SteamOS)

### Installation Type

AppImage

### Describe the issue

Launching the appimage through the game mode flashes the launcher for a split second then exits. I have no launch options at all.

https://user-images.githubusercontent.com/54160598/200152105-e7a35ad3-ec92-450b-95f1-7d9844bd9bdf.mp4

### Reproduction Steps

Add the appimage to steam then go into game mode and press play

**Comment by Mar0xy** [comment]
Please use the Flatpak as the AppImage doesn't work with Steam Deck.
