### ISSUE TITLE
Game downloading failed due to "no free space"

### ISSUE THREAD

**Issue by XJ-9Olev** [an-anime-team/an-anime-game-launcher#352]
I'm wanting to install the game to my secondary hard drive. I created a file for the game there during the first stage of the install, then set up a symlink to `$HOME/.local/share/` since the installer doesn't seem to want to actually respect where I tell it to install (although I do see that the proper installation path has been set in the config file). However, the installer claims that I don't have enough free space despite having over 500GB free.

The installer seems to not respect symlinks, in other words, nor does it actually let you migrate your installation folder. I hope something can be done about this.

I'm running EndeavourOS and am using the AUR installer.

**Comment by krypt0nn** [comment]
Do not use symlinks. Launcher doesn't respect them when counting free space (although I though I've added their support...). Edit `config.json` file in the launcher's folder instead to change installation path
