### ISSUE TITLE
Runtime org.gnome.Platform/x86_64/45 required by application moe.launcher.an-anime-game-launcher/x86_64/master was not found

### ISSUE THREAD

**Issue by JeanNong** [an-anime-team/an-anime-game-launcher#355]

**Comment by Rewarp** [comment]
@JeanNong You need to add a description for where you encountered this issue.

version: 3.9.4, Flathub
OS: openSUSE Tumbleweed

Via the Discover Software Centre in openSUSE Tumbleweed, when attempting to update, the error:

> The application moe.launcher.an-anime-game-launcher/x86_64/master requires the runtime org.gnome.Platform/x86_64/45 which was not found

I installed the program via the Flathub repository through the CLI. Curiously, running `sudo flatpak update` shows nothing to update. The game still runs fine for now.

**Comment by Rewarp** [comment]
I solved my issue by uninstalling and reinstalling the program following the commands at Flatpak GitHub page:

https://github.com/an-anime-team/flatpak-builds

Seems to be working fine now at the latest version.

**Comment by JeanNong** [comment]
> I solved my issue by uninstalling and reinstalling the program following the commands at Flatpak GitHub page:
> 
> https://github.com/an-anime-team/flatpak-builds
> 
> Seems to be working fine now at the latest version.

thank，i soved it by reinstall from console of Linux
