### ISSUE TITLE
Launcher is not able to properly start/install the Game

### ISSUE THREAD

**Issue by Rajala1404** [an-anime-team/an-anime-game-launcher#356]
The Launcher is not able to properly install the Game if you Download the Game there are 2 Cases.
Case 1: Some important Files are missing and the Game can't launch at all
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/115874847/d850ca04-7ca8-4bbf-b9b0-c9ba5d6ec94e)
If you repair the Game you come to Case 2
Case 2: The Game is totally corrupted (i had this issue in the past but it was fixed by reinstalling):
![Video (In Game)](https://github.com/an-anime-team/an-anime-game-launcher/assets/115874847/61e39c3e-6d61-44f5-b3c7-5357fff9d5c2)

I tried reinstalling Everything, only the Game and also tried repairing in both cases doesn't help leads all to case 2

This issue makes the Game unplayable. 

I'm currently trying to merge case 1 into case 2 i will edit this with the result
![image](https://github.com/an-anime-team/an-anime-game-launcher/assets/115874847/88f2ea24-2af9-4fc6-a18b-e5ede0755a79)

Edit: Merging 1 in 2 results in Case 2

**Comment by Rajala1404** [comment]
After installing an Version with the Official launcher (via wine-staging 8.21) and overwrite and merge the Files from the Launcher it still results in Case 2 even after deleting and creating the same issue for testing i launched the Game via the Official Launcher and it worked just fine.

I though maybe its an Issue with the Wine Version so i tried (created after each Version switch an new Prefix):
Wine-GE-Proton 8-26 (Case 2)
Wine-GE-Proton 8-25 (Case 2)
Wine-GE-Proton 8-21 (Case 2)
Soda 8.0-2 (Black Screen)
Lutris 7.2-2 (Black Screen)
GE-Proton (Failed to launch game: No such file or directory (os error 2))

None worked so I'm curious that its maybe an Issue with the Launcher because exact the same Game files are working with the Official Launcher (wine-staging 8.21)  and the Game Files downloaded with the AAG Launcher are sometimes missing crucial Files (Case 1) and i tested to start the exact Game Installation (used for Prefix testing with AAG Launcher) with my default wine Prefix and it worked just fine so its not an Issue with the Game Files.

**Comment by Rajala1404** [comment]
After some research in the Discord Server i saw that its a Problem with DXVK

**Comment by IdkAnythin07** [comment]
> After some research in the Discord Server i saw that its a Problem with DXVK

how did you fix

**Comment by Rajala1404** [comment]
Switch between DXVK versions
