### ISSUE TITLE
[Issue]: Failed to decompress the file after downloading it

### ISSUE THREAD

**Issue by danyi** [an-anime-team/an-anime-game-launcher#36]
### Distro

steamos holo
steamdeck

### Installation Type

Flatpak

### Describe the issue

Failed to decompress the file after downloading it

After extracting to 4%, it gets stuck

I'm not sure what the problem is

I went into the file directory and saw the compression problem

When I manually unzip it and put it in the corresponding folder

The game is up and running normally

So I'm sure it's a bug

**Comment by Mar0xy** [comment]
This is too little information to deal with anything as we depend on the logs file generated by the launcher in the logs folder where the config is located to find issues.

**Comment by Mar0xy** [comment]
This issue will be closed and marked as stale as it's been a full month without response
