### ISSUE TITLE
crash in steam deck recently

### ISSUE THREAD

**Issue by CuSO4Gem** [an-anime-team/an-anime-game-launcher#369]
genshin impact crash in steam deck recently. It is work well just befor 1 week ago. I have re image system but it does not work.
# base information
- language: Chinese  
- game version: China  
- Components: Win-staging-TKG 9.8, dxvk-2.3.1
- system: steamdeck 2.3.19
- kernal: 6.1.52-valve16-1-neptune-61
[crash.txt](https://github.com/an-anime-team/an-anime-game-launcher/files/15367898/crash.txt)
![IMG20240519130647](https://github.com/an-anime-team/an-anime-game-launcher/assets/37165760/5f40293f-154a-4499-8323-61ab0fa76198)
![IMG20240519130636](https://github.com/an-anime-team/an-anime-game-launcher/assets/37165760/be9a2a89-b4be-41f5-bba8-f76f677c5d5a)

**Comment by c02y** [comment]
Check out all the comments in https://github.com/an-anime-team/an-anime-game-launcher/issues/368

**Comment by CuSO4Gem** [comment]
successed
