### ISSUE TITLE
[Issue]: Can't login via Twitter. Browser crashes.

### ISSUE THREAD

**Issue by Originalimoc** [an-anime-team/an-anime-game-launcher#37]
### Distro

SteamOS 3

### Installation Type

Flatpak

### Describe the issue

Illegal instruction error reported by wine.

### Reproduction Steps

Try login via Twitter.

**Comment by Mar0xy** [comment]
The in-game Browser is borked and doesn't work properly due to a Wine issue. Nothing we can do on our end.
