### ISSUE TITLE
game launcher took forever to download genshin resource

### ISSUE THREAD

**Issue by tloc241** [an-anime-team/an-anime-game-launcher#371]
yes, it download like 10kb/s, way way wayyyyyyyyy slower compare to honker launcher
can any help me fix this?
OS: Lubuntu 24.04
Kernel: 9.8.9-10
Download via pacstall, pacstall version: 5.1.1 Indigo
launcher ver: 3.9.6
;-;

**Comment by krypt0nn** [comment]
Unrelated to the launcher. Code is literally the same.
