### ISSUE TITLE
[Feature Request] Request to add support for the game Wuthering Waves

### ISSUE THREAD

**Issue by WRXinYue** [an-anime-team/an-anime-game-launcher#372]
Being an [open world](https://en.wikipedia.org/wiki/Open_world) [gacha game](https://en.wikipedia.org/wiki/Gacha_game), Wuthering Waves has been compared to other titles such as [Genshin Impact](https://en.wikipedia.org/wiki/Genshin_Impact), but it aims to emphasize combat more than its predecessors. I believe it could become a popular game now or in the future. Shouldn't we consider supporting Wuthering Waves, especially since I've already seen Punishing: Gray Raven mentioned in the documentation?

**Comment by AozoraDev** [comment]
There's already a progress on [Discord](https://discord.gg/ck37X6UWBp) for this but it's still.... still far away from stable enough due to the complexity of the anticheat.

**Comment by AozoraDev** [comment]
Oh. and close this issue if this answer your question enough.

**Comment by WRXinYue** [comment]
> Oh. and close this issue if this answer your question enough.

Thank you for your answer.
