### ISSUE TITLE
Not generating log file

### ISSUE THREAD

**Issue by Parsa-GP** [an-anime-team/an-anime-game-launcher#374]
so I've installed it via flatpak because the compiled one requires `GLIBC_2.38` and the launcher got error when opening the app and in the terminal (because i ran it via `flatpak run moe.launcher.an-anime-game-launcher --debug` command) it says `anime-game-launcher had a problem and crashed.` and the it provides an log file named `/tmp/report-b4ebd53f-edcc-42ad-ba3e-45b7fca6252d.toml` and then the file is not there even when i close the launcher.

The crash is when i hit download and for some reason it crashes without any useful data written on the terminal.

in the attachment there's a dump of my terminal info provided by the launcher using --debug parameter.
[launcher-dump.txt](https://github.com/an-anime-team/an-anime-game-launcher/files/15451509/launcher-dump.txt)
(the `<USERNAME>` on the dump is not generated by launcher, I've decided to replace it for privacy reasons)

**Comment by Equivocal90** [comment]
You could  run `flatpak run --command=/bin/bash moe.launcher.an-anime-game-launcher` to enter a shell and then run `moe.launcher.an-anime-game-launcher --debug` when it crashes you should be able to see the file in `/tmp/` within the shell.

**Comment by Parsa-GP** [comment]
oh, i get it why, thanks.
[crashreport.txt](https://github.com/an-anime-team/an-anime-game-launcher/files/15477448/crashreport.txt)

(for dudes that have the same problem, flatpacks have a sandbox kinda system to put app files and libraries in the correct place so they not interfere with your host system's libraries and made a mess, and with the first command, you "chroot"-ing into the sandbox folder)
