### ISSUE TITLE
an-anime-game-launcher: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by an-anime-game-launcher)

### ISSUE THREAD

**Issue by Muffinmaker2** [an-anime-team/an-anime-game-launcher#377]
Hello gamers, i tried installing this over the pacstall thingi cause that seemd to be the right one for min 21.3 but now trying to run the launcher it throws this error in the title:( the installation has gone flawless and finished without a error

Anyone know what this could cause :O?

**Comment by Mar0xy** [comment]
Hello Gamers, how about we check the issue literally on the front page https://github.com/an-anime-team/an-anime-game-launcher/issues/373

**Comment by Mar0xy** [comment]
The latest comment states how to install it without compiling it yourself

**Comment by Muffinmaker2** [comment]
The Flatpack installation throws the same error. uninstalling the pacstall one and doing it with flatpack

**Comment by Muffinmaker2** [comment]
I have found the error :O Flatpak was silently not installing because an other process was blocking the file from being accessed. I killed the process reinstalled everything using flatpak and now the launcher opened. 
:)
