### ISSUE TITLE
[Issue]: launcher folder button not opening the folder

### ISSUE THREAD

**Issue by seanzhang98** [an-anime-team/an-anime-game-launcher#38]
### Distro

SteamOS 3

### Installation Type

Flatpak

### Describe the issue

launcher folder button not opening the folder so not able to change config file

### Reproduction Steps

Click launcher folder in the setting
Noting happen

**Comment by Mar0xy** [comment]
This is a general steam deck issue with the xdg-portal and requires a restart of the xdg-portal for xdg functions to work properly. [See this comment on Yuzu](https://github.com/yuzu-emu/yuzu/issues/4455#issuecomment-1166518033)
