### ISSUE TITLE
i cant run my launcher...

### ISSUE THREAD

**Issue by Ihsans840** [an-anime-team/an-anime-game-launcher#392]
<img width="1031" alt="Screenshot 2024-07-02 at 22 43 39" src="https://github.com/an-anime-team/an-anime-game-launcher/assets/63180405/6377183d-6d1c-4a59-adcb-6b97e568405c">

i somehow cant open my launcher, can anyone tell how do i open the launcher

**Comment by xXMacMillanXx** [comment]
I had this issue too, but just a few minutes ago the update of the flatpak popped up. See if the update is now available for you too.

**Comment by PopCat19** [comment]
try `flatpak update` after reboot

**Comment by Kamui96** [comment]
Thank you guys you made my day. I didn't even think about just trying to update through flatpak. Many thanks.

**Comment by PopCat19** [comment]
remember to close the issue ^^

**Comment by EvilBoi123** [comment]
if this is resolved, you should close this issue now.
