### ISSUE TITLE
Help: Can't launch game

### ISSUE THREAD

**Issue by MoYingJi** [an-anime-team/an-anime-game-launcher#393]
I know it's probably not a launcher issue, but I can't find any other recourse.
After one reinstallation of my Arch Linux with this launcher and the game installed, I can't start the game but instead get the wine error screen. like this
![屏幕截图_20240704_174900](https://github.com/an-anime-team/an-anime-game-launcher/assets/64307394/a8735ecb-49c0-487e-a56a-60ce63904ff8)
When I click on details, the wine error window just crashes.
I've tried everything, including reinstalling the launcher, replacing the runner, trying many versions of all runners, and even reinstalling the system, and nothing has solved the problem. While I know something about linux, I know nothing about wine. I reinstalled the system almost exclusively with wine, wine-mono and wine-gecko and left everything else untouched.

If I can't say this here, then I'm sorry in advance for using a translator, and I'm sorry in advance for using words that are offensive。

**Comment by PopCat19** [comment]
Have you tried using the [flatpak version](https://github.com/an-anime-team/an-anime-game-launcher/wiki/Installation#-any-distribution-flatpak) of this launcher?

**Comment by MoYingJi** [comment]
非常感谢您的回复，但我的问题在刚刚的一次游戏版本更新后就解决了。我仅仅更新了游戏。也不知道之前哪里出了问题
Thank you very much for your reply, however my problem was solved with a game version update just now. I simply updated the game. I have no idea what went wrong.
我使用AUR的版本
The version I use is AUR
可能是我的问题
Maybe it's just me.
