### ISSUE TITLE
[Issue]: Missing a lot of shared libs.

### ISSUE THREAD

**Issue by Originalimoc** [an-anime-team/an-anime-game-launcher#40]
### Distro

SteamOS Canary/Preview w/ org.gnome.Platform/x86_64/43 runtime

### Installation Type

Flatpak

### Describe the issue

missing
libwebkit2gtk-4.0.so.37
libjavascriptcoregtk-4.0.so.18
libicui18n.so.72
libicuuc.so.72
libjpeg.so.8

### Reproduction Steps

What's the best way to solve this? Include in self packages?

**Comment by Mar0xy** [comment]
This was caused by the upgrade to 43 as webkit got an updated on that platform version breaking neutralino this was fixed by a downgrade that was performed recently.
