### ISSUE TITLE
feature request for SDL/Xinput

### ISSUE THREAD

**Issue by toxicfox2491** [an-anime-team/an-anime-game-launcher#400]
I recently got a new controller and was wondering if I could get it working with the anime game knowing it supports controller on PC
I didnt really think this would work and it didnt even after trying to add the xinput DLLs manually in winecfg (refused to luanch the anime game) so I was wondering if its possible to add a toggle in settings to enable or disable controller support in settings?

**Comment by nuuull** [comment]
Controllers should work right away as long as SDL supports it. What kind of new controller you have?

**Comment by toxicfox2491** [comment]
> Controllers should work right away as long as SDL supports it. What kind of new controller you have?

its a red dragon saturn controller
and so sorry Im a dumbass Ive just been told I have to manually switch the controlls from keyboard to controller lmao
