### ISSUE TITLE
Unable to download game to installation paths other than default ones

### ISSUE THREAD

**Issue by aletschfirn** [an-anime-team/an-anime-game-launcher#405]
Original issue: #366, but got closed

System info: NixOS 24.11, Linux 6.6.39, AAGL installed using NixOS module, two disks: root on / and media on /mnt, media disk has rwx for all groups, as does all folders inside it

How to reproduce (for me, I don't know how user did it in 366):
Install AAGL using NixOS Module ([Flake with module](https://github.com/gamono23/nix-dots/blob/68dde8fc36e37257b0db0bc77fa0f39274925991/flake.nix#L39))
Launch from terminal (`anime-game-launcher` as user)
Install Wine, etc...
Change config.json to point game installation to folder on other disk (since I couldn't use picker - `ERROR rfd::backend::xdg_desktop_portal: pick_folder error No such file or directory (os error 2)`, although I have xdg-desktop-portal-hyprland installed):

```json
"game": {
  "path": {
    "global": "/mnt/Games/Genshin",
  },
},
```

Launch AAGL with new config
Try to download game resources
Get error due to .local/share not having enough space to download game:
![image](https://github.com/user-attachments/assets/a85257b6-df87-4eaf-aa0c-a102520b91ee)

**Comment by aletschfirn** [comment]
Yeah, thanks for comment, helpful. I'll close it, since it is not relevant to me, nor can test it.

**Comment by mrvictory1** [comment]
In new versions of launcher, the download path is stored in launcher -> temp in the config file
