### ISSUE TITLE
[Issue]: Non of the patch repositories are available.

### ISSUE THREAD

**Issue by Tennyleaz** [an-anime-team/an-anime-game-launcher#41]
### Distro
I'm using manjaro gnome: 
`Linux leaz-c7h 5.15.76-1-MANJARO #1 SMP PREEMPT Sat Oct 29 14:22:16 UTC 2022 x86_64 GNU/Linux`

### Installation Type

AppImage

### Describe the issue

The launcher always complains "Non of the patch repositories are available." 

Logs shows:
```
[20:58:34.210][Cache.get]
 - Resolved expired hot cache record
 - [name] Patch.getPatchInfo.3.2.0.origin
 - [value] {"available":false,"error":"origin patch repository is unreachable"}
[20:58:39.504][Cache.set]
 - Caching data:
 - [ttl] 3600
 - [value] {"available":false,"error":"origin patch repository is unreachable"}
[20:58:39.548][Cache.get]
 - Resolved expired hot cache record
 - [name] Patch.getPatchInfo.3.2.0.additional
 - [value] {"available":false,"error":"additional patch repository is unreachable"}
[20:58:44.575][Cache.set]
 - Caching data:
 - [ttl] 3600
 - [value] {"available":false,"error":"additional patch repository is unreachable"}
[20:58:44.579][thread: 2744][State.update] Updated state: game-launch-available
```

I see the patch repos in `~/.local/share/anime-game-launcher/config.json` shows:
``` json
  "patch": {
    "path": "/home/leaz/.local/share/anime-game-launcher/patch",
    "servers": [
      "https://notabug.org/Krock/dawn",
      "https://codespace.gay/Maroxy/dawnin"
    ],
    "root": true
  }
```
I could browse these 2 repos in my browser.
I also tried deleting `~/.local/share/anime-game-launcher/.cache.json`, or deleting the whole `~/.local/share/anime-game-launcher/` folder.

However, I could download the patch using same appimage version, on my old laptop, which is running Pop OS. Which indicate that it is not a network issue?

Full logs here:
[latest.log](https://github.com/an-anime-team/an-anime-game-launcher/files/9997228/latest.log)

### Reproduction Steps

Just executing the appimage.

**Comment by yxtj** [comment]
Got the same problem on Steam Deck for the latest version.

FYI, at the begging of the log file, I saw: `steamos: no`

**Comment by yxtj** [comment]
The same problem remains in the latest version.

I read the latest.log file and found it loads the patch URL correctly. And I can download the patch files using a browser. Then, there are many entries reporting "original patch repository is unreachable" or "additional patch repository is unreachable"

And the launcher starts very slowly. So I guess maybe there are some bugs in the patch loading or json parsing part.

**Comment by Tennyleaz** [comment]
I think there must be something related in manjaro/arch related distros?
Yesterday I tested with latest appimage:

Tried booting a live Fedora ISO: OK
Tried booting a live POP OS ISO: OK
Tried booting a live Manjaro ISO: `Non of the patch repositories are available.`
Tried booting a live Manjaro ISO in VirtualBox: OK
Tried clean install Manjaro on another disk: `Non of the patch repositories are available.`
Tried clean install ChimeraOS on another disk: `Non of the patch repositories are available.`

**Comment by lubuoren** [comment]
> I think there must be something related in manjaro/arch related distros? Yesterday I tested with latest appimage:
> 
> Tried booting a live Fedora ISO: OK Tried booting a live POP OS ISO: OK Tried booting a live Manjaro ISO: `Non of the patch repositories are available.` Tried booting a live Manjaro ISO in VirtualBox: OK Tried clean install Manjaro on another disk: `Non of the patch repositories are available.` Tried clean install ChimeraOS on another disk: `Non of the patch repositories are available.`

I run the binary file on _AUR_ , but it can run successfully.

**Comment by NuperSu** [comment]
> I run the binary file on _AUR_ , and it can run successfully.(Manjaro)

Did you run an-anime-game-launcher-gtk-bin package or an-anime-game-launcher-bin package? Because an-anime-game-launcher-bin from _AUR_ doesn't run for me on Manjaro.

**Comment by lubuoren** [comment]
> 

I run the binary from AUR,you may can check your connect (it will connect the server which you choose in config.yaml,if you choose China it will connect mihoyo.com.If you choose Global it will connect hoyoverse.com).Or you need to try restart the binary of an-anime-game-launcher-bin.

PS:It may can't help you,because you'd better to upload an image of you computer running the program

**Comment by Mar0xy** [comment]
Outdated as of Release 3.0.0 due to complete rewrite of launcher
