### ISSUE TITLE
Why "migrate game installation" feature was removed?

### ISSUE THREAD

**Issue by NSArtem** [an-anime-team/an-anime-game-launcher#413]
Why "migrate game installation feature" was removed in the recent release?

That was actually a feature I used just recently, when I was organizing filesystem on my steamdeck, and moved the installation from dot directory to a specific games directory. It was quite convenient and worked pretty good.

This issue isn't intended as an attack on the development team, just curious of the reasoning behind :)

**Comment by mkrsym1** [comment]
Most people were interpreting it as "migrate installation from the official launcher into AAGL", and, as a result, migrating emptiness onto their installed game, which effectively deletes it. Some particularly unfortunate people even managed to somehow migrate the void onto their home folder.

You can still migrate the game manually by moving the game folder and changing the path in config.json.

**Comment by krypt0nn** [comment]
PR contained the explanation: https://github.com/an-anime-team/an-anime-game-launcher/pull/412

**Comment by NSArtem** [comment]
Got it. Thanks, closing the issue.
