### ISSUE TITLE
[Issue]:  SteamOS 3.3+ launcher only runs on desktop mode

### ISSUE THREAD

**Issue by DarkenLX** [an-anime-team/an-anime-game-launcher#42]
### Distro

Distro: SteamOS (aka. HoloOS) 3.3.2 on Steam Deck 

### Installation Type

Flatpak

### Describe the issue

Issue: both Launcher and game does not launch under SteamOS GUI just get a white screen for 5-10 seconds then crashes. It will launch and play under desktop mode however. 

### Reproduction Steps

Create a shortcut under steam in desktop mode>
Enter Game Mode (SteamOS Default GUI.. I Guess its called Big Picture Mode?) > Launch the shortcut 
Also tried force proton compatibility to "steam linux runtime" and it won't even launch with that.

Question to the issue are there some special settings to run under this mode in the launcher settings currently set to whatever default settings are.

**Comment by ShiiroSan** [comment]
I had the same issue. Fixed it by tinkering with Wine and DXVK. FYI I'm using Wine-GE-Proton 7.34 and DXVK 1.10.3. Wine-GE-Proton 7-31 crashed the game after intro video, and DXVK 2.0 seems to be the reason for whitescreen hanging and crash.

**Comment by DarkenLX** [comment]
> I had the same issue. Fixed it by tinkering with Wine and DXVK. FYI I'm using Wine-GE-Proton 7.34 and DXVK 1.10.3. Wine-GE-Proton 7-31 crashed the game after intro video, and DXVK 2.0 seems to be the reason for whitescreen hanging and crash.

I've done this but it only works in desktop mode. But Not in "gaming mode"

**Comment by ShiiroSan** [comment]
> > I had the same issue. Fixed it by tinkering with Wine and DXVK. FYI I'm using Wine-GE-Proton 7.34 and DXVK 1.10.3. Wine-GE-Proton 7-31 crashed the game after intro video, and DXVK 2.0 seems to be the reason for whitescreen hanging and crash.
> 
> I've done this but it only works in desktop mode. But Not in "gaming mode"

Try adding --run-game at the end of your Steam shortcut. That's the latest idea coming to my mind... It wasn't working since I did all info I gave you...

**Comment by DarkenLX** [comment]
> > > I had the same issue. Fixed it by tinkering with Wine and DXVK. FYI I'm using Wine-GE-Proton 7.34 and DXVK 1.10.3. Wine-GE-Proton 7-31 crashed the game after intro video, and DXVK 2.0 seems to be the reason for whitescreen hanging and crash.
> > 
> > 
> > I've done this but it only works in desktop mode. But Not in "gaming mode"
> 
> Try adding --run-game at the end of your Steam shortcut. That's the latest idea coming to my mind... It wasn't working since I did all info I gave you...

This worked thanks 👍

**Comment by gezawatt** [comment]
I have this issue as well and this worked as a workaround, thanks!
