### ISSUE TITLE
How to configure AAGL to allow running patched/earlier game version? (4.0.1)

### ISSUE THREAD

**Issue by PopCat19** [an-anime-team/an-anime-game-launcher#427]
I'm trying to configure AAGL to proxy through a private server with a custom patch. But I can't launch the game through AAGL likely due to mismatched versioning.
|
Is there a way to enable AAGL to launch an older version?

Additionally, the game does run under lutris. I'm just curious if there is an option to run it through AAGL.
![Screenshot_20240911_183928](https://github.com/user-attachments/assets/29161fb5-c799-4cdb-ba0b-fcf0943667cc)
![Screenshot_20240911_183948](https://github.com/user-attachments/assets/5e57f7a6-8691-41bb-8a80-f8494ad0d7d3)

**Comment by krypt0nn** [comment]
There's no option for it and we will never support this. You have to either heavily modify the launcher's code or run the game elsewhere.
