### ISSUE TITLE
Failed to find game diff (os error 13)

### ISSUE THREAD

**Issue by zhenhaoxiao** [an-anime-team/an-anime-game-launcher#430]
So I recently updated the launcher and then downloaded the new version. Then it got stuck at 100% and waited a while before restarting, now it’s giving me this error. Also when I try to repair the game files it gives me this:

Failed to repair game file
Failed to create output file "/run/media/deck/ 3а31495-567b-4865-93ef-cc39b34a0f8b/games/ genshin/Genshin Impact/GenshinImpact_Data/ Managed/Metadata/global-metadata.dat":
Permission denied (os error 13)

**Comment by hashelq** [comment]
`chmod +x /run/media/deck/ 3а31495-567b-4865-93ef-cc39b34a0f8b/games/ genshin/Genshin Impact/`
