### ISSUE TITLE
Launcher not working after Genshin Update

### ISSUE THREAD

**Issue by ohSystemmm** [an-anime-team/an-anime-game-launcher#439]
Hey there!
The launcher refuses to update Genshin Impact by saying "Version is too outdated and cant be updated". Please Update the launcher or provide a way do fix that problem! 
Thank you!
![image](https://github.com/user-attachments/assets/e694c113-86c8-484c-ae28-3bd431ed385b)
![image](https://github.com/user-attachments/assets/cbb8f442-d901-4ea0-bea0-5e0e535e69a8)

**Comment by dy-tea** [comment]
Your version is too outdated to be updated. This is because Mhy only stores update files for the latest 1-2 versions. You need to delete your game and reinstall.

**Comment by ohSystemmm** [comment]
Hello!
Thank you for your reply and sorry for my non detailed post.
I actually reinstalled it (3rd time) since I thought that was the case in first place, however its still there. I will try it again but I am not sure if thats the solution.

**Comment by krypt0nn** [comment]
What launcher version you use?

**Comment by YukySan** [comment]
Same issue, I just installed the launcher and the game via Lutris. In the settings, the game version is 5.1.0, and in the debug.log it says: 'INFO anime_game_launcher: Starting application (3.12.1).' I assume that's the launcher version?

**Comment by krypt0nn** [comment]
You should update to the latest launcher version as soon as it becomes available on your platform. Likely old launcher builds generate incorrect `.version` files. You could replace them manually if you know how to do this. You can ask for details on our discord server. The updated launcher should not have this problem.

**Comment by YukySan** [comment]
Thank you for your response.

I removed what was installed with Lutris and installed the launcher via: `yay -S an-anime-game-launcher-bin` to get the latest version of the launcher.
I am downloading the game again on the new version of the launcher to see if the issue occurs again.

**Comment by YukySan** [comment]
That seems to work for me with the latest version of the launcher. The issue appears to be related to the version provided by Lutris.

**Comment by ohSystemmm** [comment]
Alright Thank yall for your assistance! I think the issue is the lutris version since the AUR one works for me.
