### ISSUE TITLE
Info: runtime org.gnome.Platform branch 45 is end-of-life

### ISSUE THREAD

**Issue by cassiofb-dev** [an-anime-team/an-anime-game-launcher#443]
Gnome 45 runtime is now out of life, full message:

```txt
Looking for updates…

Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   moe.launcher.an-anime-game-launcher
```

**Comment by Opfour** [comment]
Getting the same info notice:

`david@Merovingian2:~$ flatpak update
Looking for updates…
Info: runtime org.gnome.Platform branch 45 is end-of-life, with reason:
   The GNOME 45 runtime is no longer supported as of September 18, 2024. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   it.mijorus.collector`

Does this have to do with the app itself it's referring to?

**Comment by cassiofb-dev** [comment]
@Opfour yes. It means the app you are using also didnt update the gnome runtime. You need to open an issue or contact the developer.

**Comment by lasofeli** [comment]
[It's been updated already](https://github.com/an-anime-team/flatpak-builds/pull/63), and the app is using version 47 on my machine now.

**Comment by cassiofb-dev** [comment]
@lasofeli , thanks for reminding me. It was indeed solved, I'm closing this issue.
