### ISSUE TITLE
FPS Unlocker never allows over 120fps

### ISSUE THREAD

**Issue by dylanmilesmsu** [an-anime-team/an-anime-game-launcher#446]
I have a 240hz monitor, and would like to use >120fps. Whenever I select anything above 120 in the settings, I open the game to find that it is still running at 120fps, and after closing and reopening AAGL, the setting reverts to 120 also. Even setting it manually in the config.json and making it read only does not allow the game to run over 120fps. 

Pop!_OS 22.04

An Anime Game Launcher 3.13.0

**Comment by cassiofb-dev** [comment]
@dylanmilesmsu hi, you installed it with flathub or native package? There are a few things that could be limiting your fps:

1. Your refresh rate is not set to 240hz
2. [Custom DXVK config](https://github.com/doitsujin/dxvk/blob/master/dxvk.conf)
3. [High usage cpu bug](https://github.com/an-anime-team/an-anime-game-launcher/issues/383)
4. [Custom MangoHUD config](https://github.com/flightlessmango/MangoHud/blob/master/data/MangoHud.conf)

Hope some of those are your problem, I installed the flathub package and here's how mine is running right now:
![image](https://github.com/user-attachments/assets/688408e7-926a-46c2-a1f3-14c0e444f70c)

**Comment by dylanmilesmsu** [comment]
My monitor is set to 240hz. I installed it with flathub. I do not have a custom dxvk config, my cpu usage is fine (5700x3d) and I don't have a custom mangohud either. AAGL constantly reverts it's own settings back to 120 even after I set it to 240. It's certainly not anything to do with hardware or custom configs

**Comment by dylanmilesmsu** [comment]
After setting the fps to "custom", I can now get >120fps. Not sure why the actual 240 setting doesn't work. But setting it to "custom" is a suitable workaround

**Comment by aamaanaa** [comment]
this is still a issue for me and using custom it still locks on 120
