### ISSUE TITLE
[Issue]: download game again

### ISSUE THREAD

**Issue by EXCADOGOD** [an-anime-team/an-anime-game-launcher#47]
### Distro

STEAM DECK

### Installation Type

Flatpak

### Describe the issue

My launcher can download the game(40+GB), but when it finished, the launcher ask me to download 40+GB again and again, I had download it 4 times. I'm using cn service

**Comment by runzhi** [comment]
我也遇到相同问题
same issue.
I use soft link make the launcher to external storage, downloaded twice and it asked me downloaded again

**Comment by c02y** [comment]
Did you change the default voice in the config file? If you do, do not change the voice, change it inside the game instead. I believe it is a bug.

**Comment by tigersoldier** [comment]
Can you confirm if you are using the CN version? I think I had the some issue when I accidentally chose the CN version. Need to investigate the code when I have time.

**Comment by PKC278** [comment]
Same issue.
server: cn

**Comment by EXCADOGOD** [comment]
> Can you confirm if you are using the CN version? I think I had the some issue when I accidentally chose the CN version. Need to investigate the code when I have time.

I deleted the game, then turned off the launcher in the countdown after the first time I opened it, and then entered the directory to change the server to cn, so that the problem of repeated downloading would not be triggered.

**Comment by runzhi** [comment]
> 

both voice and server are cn

voice zh-cn
server cn

**Comment by runzhi** [comment]
> 

en voice works for me
thanks

**Comment by czy-moyu** [comment]
Same issue. voice en and server cn alse cause multiple times download. And there is no button when it downloaded voice completed.
![IMG_20230205_084843](https://user-images.githubusercontent.com/45380309/216795818-e13f4b12-6234-4e55-a85b-497b59f87504.jpg)

**Comment by tigersoldier** [comment]
I can reproduce this. This is likely caused by stale cache for the global server. #61 should fix it.

To manually fix it, open the launcher folder by Gear icon -> setting dialog -> click "launcher folder" chip. It should open the launcher folder for you. Remove the `.cache.json` file and restart the launcher.

If you don't see the `cache.json` file, right click the empty space of the folder, and check "show hidden file"

**Comment by tigersoldier** [comment]
Also, the cache expires in 6 hours, so if you haven't used it for 6 hours, it should work now. I highly recommend removing all the files in the game folder before installing the right version. They are global data and will just sit there and takes 66G out of your storage.

**Comment by czy-moyu** [comment]
> Also, the cache expires in 6 hours, so if you haven't used it for 6 hours, it should work now. I highly recommend removing all the files in the game folder before installing the right version. They are global data and will just sit there and takes 66G out of your storage.

OK.Thanks.
