### ISSUE TITLE
logged out of (pc) user account when launching

### ISSUE THREAD

**Issue by mowohre** [an-anime-team/an-anime-game-launcher#48]
### Distro

6.1.3-1-MANJARO (64-bit)

### Installation Type

AUR

### Describe the issue

when the launch button is clicked i am logged out of my pc user account. same thing happens when i am trying to start up a windows vm (using vmware).
this occurred after i updated my applications.
i have tried reinstalling the launcher and game... nothing changed.
has anybody got an idea why this might be happening?
(the game used to run just fine)

**Comment by Kito-san** [comment]
i doubt this is launcher related if it a windows vm also crashes your desktop
it could be a Manjaro related issue

i would highly recommend switching Distro also manjaro is more likely to break when using AUR

i would recommend reading this
https://github.com/arindas/manjarno

**Comment by mowohre** [comment]
thank you. sadly switching the distro is not up to me as it is not my own pc...
but luckily i found a workaround. it seems like when starting it with the launcher it is running on a different layer (or something... im not that familiar with this) as when i start it with lutris (what im currently using).
