### ISSUE TITLE
[Feature Request]: Add some settings

### ISSUE THREAD

**Issue by QiE2035** [an-anime-team/an-anime-game-launcher#5]
### What the feature is suppose to do

**[Translated by Google]**

I hope, in the settings can add the following options:
1. Use the system's Wine or customize the location of Wine
2. Use the system's DXVK or customize the location of DXVK
3. Set the location of the wine prefix
4. Set the location of the game

### Describe the reason behind the request

**[Translated by Google]**

In the Arch Linux I use, [archlinuxcn](https://www.archlinuxcn.org/archlinux-cn-repo-and-mirror/) provides system-level wine _(wine-ge-custom-opt ie lutris-proton-ge)_ installation (installed to `/usr`), AUR and archlinuxcn also provide system installation of dxvk, I I also want to use them in places other than the launcher, so I hope to provide a setting item to choose the version of the system or to customize the location of these selections.

Ditto, I use Wine elsewhere, so I expected to add an option to customize the location of the wine prefix (I usually just use the default `~/.wine`)

For some reason I had to install the game on another _(NTFS)_ partition, so I would like to provide an option to freely choose where the game is installed

I know the above requirements are probably just my case, and these can also be achieved by changing `config.yaml` and creating symlinks, but I would prefer to be able to provide some advanced options in the launcher settings to change them, so Not only can it keep the original simplicity and ease of use, but it can also provide a more convenient setup solution for users with special needs like me.

**Comment by krypt0nn** [comment]
You can change paths in your `config.yaml` file. GTK version of the launcher has GUI for that

**Comment by ochure520** [comment]
Yeah, I definitely agree with these suggestions. It would make it more easy to use and configure, which would possibly drive some more users to this launcher for said ease of use.

**Comment by greenhandzdl** [comment]
Plus one, repeating download makes me confused 🤔.

**Comment by Mar0xy** [comment]
Most of these features are implemented nowadays so this will be closed now.
