### ISSUE TITLE
[Issue]: Using FPS Unlocker shows "Crucial domains are not blocked. Please re-run the patch script."

### ISSUE THREAD

**Issue by NotStepbro** [an-anime-team/an-anime-game-launcher#52]
### Distro

Fedora 37 LXDE

### Installation Type

AppImage

### Describe the issue

When launching the game. If you have "Unlock FPS" selected. A file will open which says "Crucial domains are not blocked. Please re-run the patch script." But when launching without it. The game opens and works as normal. The block domains are in /etc/hosts aswell.

### Reproduction Steps

Fresh install launcher
Download appimage
Run appimage
Use fps unlocker
Cry

**Comment by Mar0xy** [comment]
My bad I never updated the bat file used to use the new domains the issue should be fixed now.
