### ISSUE TITLE
[Issue]: Launcher goes 1200x720 on Steam Deck and doesn't display anything.

### ISSUE THREAD

**Issue by FocusBlast** [an-anime-team/an-anime-game-launcher#53]
### Distro

SteamOS 3.4

### Installation Type

Flatpak

### Describe the issue

 I'm on the latest Flatpak patch. Runs fine in Desktop Mode. Thought this might be an FSR issue, but it isn't. The resolution is set to default on Steam.

### Reproduction Steps

Dunno. It just happened on its own.
![211869231-1986753c-90cd-4b43-9a5c-440d73f83c0f](https://user-images.githubusercontent.com/41729565/214270364-9714b5b3-046d-4777-bce4-3c0df714a1ce.jpg)

**Comment by bvlinsky** [comment]
Hello, check this issue for fix, works fine for me with 3.4.

https://github.com/an-anime-team/an-anime-game-launcher/issues/42

**Comment by kakaiskidoosky** [comment]
Hi @FocusBlast ,

I'm also experiencing the same issue. Running on 3.4. Game works fine on desktop mode but not on Gaming Mode. Any chance you found a fix for this? Thanks!

**Comment by Mar0xy** [comment]
Outdated as of Release 3.0.0 due to complete rewrite of launcher
