### ISSUE TITLE
[Question]: launcher differences?

### ISSUE THREAD

**Issue by DarkenLX** [an-anime-team/an-anime-game-launcher#56]
### Distro

SteamOS / Arch

### Installation Type

Flatpak

### Describe the issue

What is the difference between this launcher and the GTK version? (please add this to faqs as its not addressed there.)

### Reproduction Steps

N/A

**Comment by Mar0xy** [comment]
This version runs in a Web Browser(Webkit) and as such mainly uses JS and lets it look more like the official one.
The GTK version meanwhile is more stable on Steam Deck and containerized systems and the better choice for non-tech savvy people as it has less issues.

> (please add this to faqs as its not addressed there.)

Thanks for the suggestion it will eventually be added when it's more fleshed out
