### ISSUE TITLE
[Issue]: Change FPS cap for FPS Unlocker

### ISSUE THREAD

**Issue by AlphaCraft9658** [an-anime-team/an-anime-game-launcher#57]
### Distro

Fedora KDE 37

### Installation Type

AppImage

### Describe the issue

I got the FPS Unlocker working and I can see there is a custom cap, but I don't understand the key combinations for setting the FPS cap. What does "HOME" in "HOME + Arrow key" mean?

### Reproduction Steps

N/A

**Comment by AlphaCraft9658** [comment]
I found out the key on my keyboard. I don't use an English keyboard, so I had to look up the key. But the issue now is, that the key combinations don't work. No keyboard input seems to work for the wine terminal. Am I doing something wrong? Do I have to press some specific buttons? Is it just not possible to change the limit?

**Comment by chicco-carone** [comment]
If you go in the game files there is the file to change the fps limit. For me (intstalled from aur) it's here `~/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact/` and i change the `fps_config.ini` and it works fine

**Comment by AlphaCraft9658** [comment]
> If you go in the game files there is the file to change the fps limit. For me (intstalled from aur) it's here `~/.local/share/anime-game-launcher/game/drive_c/Program Files/Genshin Impact/` and i change the `fps_config.ini` and it works fine

Thank you for your help! Can you also tell me, whether it is possible to completely remove the cap?

**Comment by chicco-carone** [comment]
I don't think it's a good idea and the game itself it's pretty heavy. For me on a 2060 it struggles to keep 165. You can't remove the cap but probably just put 1000 FPS and I don't think you'll get more fps

**Comment by AlphaCraft9658** [comment]
Okay. I'm not even sure whether to enable vsync or not. Maybe 75 FPS (my monitor's max. refresh rate) with vsync on? If I don't have issues (stutters or screen tearing for example) without vsync and with a high FPS cap, I could use that. It depends on what works best for me. The game was smooth at 120/121 FPS so far. Additionally, I have a 3070 Ti. I'm gonna have a look at which settings fit my needs the most. Thank you again for your help!

**Comment by AlphaCraft9658** [comment]
Oops.
