### ISSUE TITLE
[Issue]: Launcher getting stuck when trying to download game's files while repairing them

### ISSUE THREAD

**Issue by BrendoCosta** [an-anime-team/an-anime-game-launcher#58]
### Distro

Ubuntu 22.04.1 LTS

### Installation Type

AppImage

### Describe the issue

Hi, some days ago I've tried repairing game's files through the launcher, but after every installation analysis, while trying to download the mismatched files, the download hangs at an arbitrary percentage (like 5%, 20%, 75% or so). After some attemps (leave it downloading overnight and then half a day) I eventually gave up and looked the mismatched files' list and the download link in launcher's log, and successfully repaired the game downloading the files through `wget -x -nH -i <a file with the download path + file path + filename for each mismatched one>` and then `rsync -a <ScatteredFiles subfolder> <Game path>`.

Note: game got corrupted after the launcher tried to unpack the 3.4 update without enough space on SSD (I really didn't realize the storage's small free space before updating, and moved entire game's folder to another disk once I noticed, but soon it started getting stuck at a white screen once initialized). The disk had free storage space when attempting to download the mismatched files (~70 GB).

Note: tried it with and without the patch applied.

Note: launcher version 2.4.4 (AppImage).

[2023-01-29-11-30-03.log](https://github.com/an-anime-team/an-anime-game-launcher/files/10563801/2023-01-29-11-30-03.log)

### Reproduction Steps

1. Have some mismatched files
2. Go to launcher's settings
3. On "general" section click at "repair game"
4. Wait until analysis is finished
5. Wait the download

**Comment by IsaSombra** [comment]
how i find the laucher's log? i have the same problem, but i'm new in linux

**Comment by BrendoCosta** [comment]
> how i find the launcher's log? i have the same problem, but i'm new in linux

@IsaSombra, you can find the log files in `$HOME/.local/share/anime-game-launcher/logs/` path.

**Comment by Mar0xy** [comment]
The launcher normally gets stuck on the repair feature if there are a lot of mismatched files causing it to lock up this has been an issue since the repair feature has been introduced into the launcher and which the GTK version of the launcher has improved on as JS limits us in this regard.
