### ISSUE TITLE
[Issue]: Click on "Register now", its prompt me en error message

### ISSUE THREAD

**Issue by dogs-1985** [an-anime-team/an-anime-game-launcher#60]
### Distro

Fedora 37 
KDE
X11

### Installation Type

Flatpak

### Describe the issue

Not sure why I click on "Register now" in the game, it prompts me with an error. Do I miss some components that didn't install properly? I checked the flatpak all app has been latest and updated. Or is this problem related to WINE?

![image](https://user-images.githubusercontent.com/69936558/216742324-2df94acb-7ec8-4e4b-b736-376d99855339.png)

![image](https://user-images.githubusercontent.com/69936558/216742355-7b629f0f-e559-43e4-8371-b8fdca3db9d3.png)

![image](https://user-images.githubusercontent.com/69936558/216741654-55911f56-d20e-4cef-8649-7d91600ded2b.png)

Flatpak version
`com.gitlab.KRypt0n_.an-anime-game-launcher`

Sorry, I'm not a technical person, if any missed info please let me know, I try to gather it and update it here.

### Reproduction Steps

1. Install the flatpak version of "An anime game launcher".
2. Execute the game launcher.
3. Download the game,
4. Finish installing the game, and click on "Launch" on the game launcher.
5. Game running, it popup the login screen on the home screen.
6. Click on "Register now", and the error message box popup.

**Comment by Mar0xy** [comment]
This is a general Wine issue which can't be fixed on our end and it is generally recommended to create an account on the site instead of in-game.

**Comment by dogs-1985** [comment]
> This is a general Wine issue which can't be fixed on our end and it is generally recommended to create an account on the site instead of in-game.

Okay, thanks for the replied.

I still have a silly question, if I play game using controller, the screen will automatically lock after 10 mins. Seems like the system not recognise the controller input. This issue is related to game, system, WINE, or launcher itself? Is recommend to turn off the screen lock when playing the game?
