### ISSUE TITLE
[Issue]: Launcher exited with symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37

### ISSUE THREAD

**Issue by bagusNA** [an-anime-team/an-anime-game-launcher#64]
### Distro

Arch Linux

### Installation Type

AUR

### Describe the issue

When trying to launch I got the following error:
`/usr/lib/an-anime-game-launcher-bin/an-anime-game-launcher: symbol lookup error: /usr/lib/libwebkit2gtk-4.0.so.37: undefined symbol: g_power_profile_monitor_dup_default`

I've tried reinstalling `an-anime-game-launcher-bin`, `an-anime-game-launcher-git` AUR package, and AppImage release but all of them won't run with the exact same error.

It was running fine yesterday. The only thing I did was uninstalling `gnome` package group, but I don't know if it is related or not. Did a google search and thought that I needed to do full system upgrade, but to no avail.

Thank you in advance.

### Reproduction Steps

1. Install either `an-anime-game-launcher-bin` or `an-anime-game-launcher-git` AUR package
2. Run

**Comment by xgdgsc** [comment]
I also have this issue with Flatpak install. I just changed server: cn and changed kde system settings http proxy in steamdeck. It runs fine before this and seems have network issue downloading DXVK. Before that it installed Wine just fine.

**Comment by laurinneff** [comment]
Try reinstalling webkit2gtk, a function it depends on is missing

**Comment by bagusNA** [comment]
Tried reinstalling webkit2gtk, still got the same error. When uninstalling the gnome group I didn't get any dependency issue though, so I just proceeded uninstalling normally.

I'll try it again with a fresh install just in case there's something messed up with my system.

**Comment by bagusNA** [comment]
Ended up doing a fresh install and it's running fine now. Still puzzles me though
