### ISSUE TITLE
[Issue]: Game download failed

### ISSUE THREAD

**Issue by CleMooling** [an-anime-team/an-anime-game-launcher#65]
### Distro

System: ArchLinux with KDE
Linux Kernel: Xanmod-6.1.12

### Installation Type

AUR

### Describe the issue

When press the Install button, the launcher started downloading, but  the progress bar was still static. And I'm sure there's no any problem with my network.
The config: server=cn
I also tried Ubuntu 22.04 LTS with the same kernel using .Appimage pack, the same problem appeared.

**Comment by Mar0xy** [comment]
Should be fixed by the recent release please check.

**Comment by CleMooling** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by CleMooling** [comment]
I noticed that the problem can be fixed by running winecfg.&nbsp;



---Original---
From: ***@***.***&gt;
Date: Mon, Feb 20, 2023 04:00 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [an-anime-team/an-anime-game-launcher] [Issue]: Game downloadfailed (Issue #65)




 
Should be fixed by the recent release please check.

**Comment by Mar0xy** [comment]
This indicates that maybe the wine prefix was broken but good to know that it works now. I will close the issue now.
