### ISSUE TITLE
[Feature Request]: lutris-GE-Proton7-37

### ISSUE THREAD

**Issue by Reireiyan** [an-anime-team/an-anime-game-launcher#66]
### What the feature is suppose to do

I'm not sure if this is considered a feature request, but I'm pretty sure it is: update lutris-GE-Proton7-35 to lutris-GE-Proton7-37 and make it the default at first install; it performs significantly better than 7-35, which causes a lot of lag.

### Describe the reason behind the request

Performance boost by default

**Comment by Mar0xy** [comment]
Should now be available via 3.0.0
