### ISSUE TITLE
[Issue]: ZFGameBrowser Error

### ISSUE THREAD

**Issue by Kaputschii** [an-anime-team/an-anime-game-launcher#67]
### Distro

Pop!_OS 22.04 LTS

### Installation Type

Flatpak

### Describe the issue

Heey Guys,

I wanted to get primos through completing paimons polls. Sadly when I try to ZFGameBrowser.exe is quiting. Used the flatpak version of the launcher. 

Error log: 

`0x0000000184a4d943 zf_cef+0x4a4d943: int	$3
Modules:
Module	Address					Debug info	Name (72 modules)
PE	00000000006a0000-00000000007d1000	Deferred        chrome_elf
PE	000000007b000000-000000007b0da000	Deferred        kernelbase
PE	000000007b600000-000000007b814000	Export          kernel32
PE	0000000140000000-00000001400d9000	Export          zfgamebrowser
PE	0000000170000000-00000001700a3000	Export          ntdll
PE	0000000180000000-000000018a43e000	Export          zf_cef
PE	00000001c4ee0000-00000001c4fb5000	Deferred        winspool
PE	00000001c69e0000-00000001c731b000	Deferred        shell32
PE	00000001c8b40000-00000001c8b60000	Deferred        msacm32
PE	00000001c8db0000-00000001c8e47000	Deferred        msvcrt
PE	00000001cfdf0000-00000001cfe13000	Deferred        dxva2
PE	00000001d97a0000-00000001d97a7000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	00000001dd3f0000-00000001dd4bf000	Deferred        crypt32
PE	00000001ec2b0000-00000001ec2d6000	Deferred        ws2_32
PE	00000001f51e0000-00000001f51f0000	Deferred        hid
PE	00000001fdfd0000-00000001fdff8000	Deferred        wintrust
PE	0000000201cf0000-0000000201d0f000	Deferred        secur32
PE	000000021a7e0000-000000021a857000	Deferred        setupapi
PE	0000000226310000-0000000226317000	Deferred        api-ms-win-core-string-l1-1-0
PE	0000000228450000-000000022847b000	Deferred        propsys
PE	0000000231ae0000-0000000231b62000	Deferred        rpcrt4
PE	000000023d820000-000000023da6f000	Deferred        user32
PE	0000000240030000-000000024005e000	Deferred        iphlpapi
PE	000000024f470000-000000024f48f000	Deferred        mpr
PE	00000002522e0000-0000000252324000	Deferred        oleacc
PE	000000025d740000-000000025d74e000	Deferred        dwmapi
PE	000000026b4c0000-000000026b53b000	Deferred        gdi32
PE	0000000270f60000-000000027123f000	Deferred        d3d9
PE	00000002739c0000-0000000273af7000	Deferred        oleaut32
PE	0000000274a50000-0000000274a5d000	Deferred        kerberos
PE	000000028dfa0000-000000028dfac000	Deferred        nsi
PE	000000029cfc0000-000000029cfd6000	Deferred        dnsapi
PE	000000029ea80000-000000029ea87000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	00000002a4090000-00000002a409e000	Deferred        wtsapi32
PE	00000002a9540000-00000002a9548000	Deferred        usp10
PE	00000002bb750000-00000002bb893000	Deferred        comctl32
PE	00000002cc880000-00000002cc88c000	Deferred        wevtapi
PE	00000002d23f0000-00000002d2417000	Deferred        credui
PE	00000002d4d40000-00000002d4d57000	Deferred        bcrypt
PE	00000002e3540000-00000002e3591000	Deferred        shlwapi
PE	00000002e8f10000-00000002e902b000	Deferred        ole32
PE	00000002edf00000-00000002ee107000	Deferred        dxgi
PE	00000002f1fa0000-00000002f1fae000	Deferred        version
PE	00000002f3920000-00000002f3930000	Deferred        esent
PE	00000002f7230000-00000002f725f000	Deferred        uxtheme
PE	00000002fa030000-00000002fa037000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	000000030a950000-000000030a9c1000	Deferred        dwrite
PE	000000030c980000-000000030c988000	Deferred        api-ms-win-core-synch-l1-2-0
PE	00000003126f0000-0000000312709000	Deferred        shcore
PE	000000031f800000-000000031f8ff000	Deferred        comdlg32
PE	0000000327020000-0000000327073000	Deferred        combase
PE	000000032a700000-000000032a72a000	Deferred        sechost
PE	0000000330260000-00000003302a0000	Deferred        advapi32
PE	0000000330a70000-0000000330aa9000	Deferred        uiautomationcore
PE	00000003422e0000-000000034237c000	Deferred        urlmon
PE	0000000346ba0000-0000000346bc1000	Deferred        jsproxy
PE	0000000351680000-0000000351688000	Deferred        api-ms-win-core-localization-l1-2-1
PE	0000000358120000-0000000358166000	Deferred        winhttp
PE	00000003673d0000-00000003673f8000	Deferred        netapi32
PE	0000000375610000-0000000375648000	Deferred        win32u
PE	00000003785e0000-00000003786b0000	Deferred        vulkan-1
PE	0000000388e20000-0000000388e2e000	Deferred        userenv
PE	00000003a0440000-00000003a04c3000	Deferred        wininet
PE	00000003a19e0000-00000003a19ef000	Deferred        ncrypt
PE	00000003aa4c0000-00000003aa4cc000	Deferred        dhcpcsvc
PE	00000003af670000-00000003af731000	Deferred        ucrtbase
PE	00000003afd00000-00000003afd1a000	Deferred        imm32
PE	00000003b6dc0000-00000003b6de8000	Deferred        winevulkan
PE	00000003b8f00000-00000003b8fc1000	Deferred        winmm
PE	00000003bb250000-00000003bb358000	Deferred        cryptui
PE	00000003be590000-00000003be5f4000	Deferred        dbghelp
PE	00007fb9de030000-00007fb9de034000	Deferred        winex11
Threads:
process  tid      prio (all id:s are in hex)
00000038 services.exe
	["C:\windows\system32\services.exe"]
	0000003c    0
	00000040    0
	00000054    0
	00000064    0
	00000078    0
	00000084    0
	000000a4    0
	000000bc    0
	000000f0    0
00000044 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000048    0
	0000005c    0
	00000060    0
	00000068    0
	000000c8    0
0000004c explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	00000050    0
	000000d4    0
	000000e0    0
00000070 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000074    0
	0000007c    0
	00000080    0
	00000088    0
	0000008c    0
	00000090    0
	00000098    0
0000009c plugplay.exe
	[C:\windows\system32\plugplay.exe]
	000000a0    0
	000000a8    0
	000000ac    0
	000000b0    0
	00000268    0
	0000026c    0
	000003cc    0
	000003d0    0
000000b4 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	000000b8    0
	000000c0    0
	000000c4    0
000000e8 rpcss.exe
	[C:\windows\system32\rpcss.exe]
	000000ec    0
	000000f8    0
	000000fc    0
	00000100    0
	00000104    0
	00000108    0
	00000518    0
00000110 tabtip.exe
	["C:\windows\system32\tabtip.exe"]
	00000114    0
	00000128    0
	0000012c    0
000001c8 GenshinImpact.exe
	["Z:\mnt\Extern\GenshinImpact\game\GenshinImpact.exe" -window-mode exclusive]
	000001cc    0
	000001d0    0
	000001e0    0
	000001e4    0
	000001e8    0
	000001ec    0
	000001f0    0
	000001f4    0
	000001f8    0
	000001fc   -1
	00000200    0
	00000204    0
	00000208    0
	0000020c    0
	00000210    0
	00000214    0
	00000218    0
	0000021c    0
	00000220    0
	00000224    0
	00000228   -2
	0000022c   -2
	00000230   -2
	00000234   -2
	00000238    0
	0000023c    0
	00000240    0
	00000244    0
	00000248    0
	0000024c   -2
	00000250   -2
	00000254   -2
	00000258   -2
	0000025c    0
	00000260   15
	00000264    0
	00000270   -1
	00000274   -1
	00000278    1
	0000027c    0
	00000280    1
	00000284    0
	00000288    0
	0000028c    0
	00000298    0
	000002a0   15
	000002a4    0
	000002a8    0
	000002ac   15
	000002b0    0
	000002c8    0
	000002cc    0
	000002f0    0
	000002f4    0
	000002f8   -2
	000002fc    0
	00000300    0
	0000032c    0
	00000330    0
	00000334    0
	00000364    0
	00000374    0
	000000f4    0
	000002b4    0
	000002d0    0
	00000354    0
	0000035c    0
	00000360    0
	00000484    0
	00000850    0
	000006e8    0
	00000704    0
	000006fc    0
	00000700    0
00000368 ZFGameBrowser.exe
	["Z:\mnt\Extern\GenshinImpact\game\GenshinImpact_Data\Plugins\ZFGameBrowser.exe" --zfBrowserAPIProxy zfb_proxyChannel-456]
	0000036c    0
	00000370    0
	00000378    0
	0000037c    0
	00000380    0
	00000390    0
	00000394    0
	00000398    0
	0000039c    0
	000003a0    0
	000003a4    0
	000003ac    0
	000003b4    0
	000003c0    0
	000003c4    0
	000003c8    0
	000003d4   -2
	000003d8    0
	000003dc    0
	000003e0   -2
	000003ec    0
	000003fc    0
	00000b40    0
	00000644    0
000003b8 ZFGameBrowser.exe
	[Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/ZFGameBrowser.exe --type=gpu-process --no-sandbox --disable-gpu-vsync --locales-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/locales --resources-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins --user-agent="Mozilla/5.0 (Windows NT 6.1; Unity 3D; ZFBrowser 2.1.0; Genshin Impact 3.4.0_12498014_12591909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.0 Safari/537.36" --lang=en-US --user-data-dir="C:\users\kaputschi\AppData\Local\CEF\User Data" --gpu-preferences=UAAAAAAAAADgAAAYAAAAAAAAAAAAAAAAAABgAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEgAAAAAAAAASAAAAAAAAAAYAAAAAgAAABAAAAAAAAAAGAAAAAAAAAAQAAAAAAAAAAAAAAAOAAAAEAAAAAAAAAABAAAADgAAAAgAAAAAAAAACAAAAAAAAAA= --log-file="C:\users\kaputschi\AppData\LocalLow/miHoYo/Genshin Impact/output_log.txt" --mojo-platform-channel-handle=640 --field-trial-handle=676,i,3138527298811654155,16057900367044433095,131072 --disable-features=CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:2]
	000003bc    1
	00000418    0
	00000424    0
	000004ec    0
	000004f0    0
	000004f4    0
	000004f8    0
	00000500   -2
	00000504    1
	00000508    0
	0000050c    0
	00000514    1
	0000051c    0
	00000520    0
	00000528   -2
	0000052c   -2
	00000530   -2
	000005f0    0
	000008e4    0
00000400 ZFGameBrowser.exe
	[Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/ZFGameBrowser.exe --type=utility --utility-sub-type=storage.mojom.StorageService --lang=en-US --service-sandbox-type=utility --no-sandbox --ignore-certificate-errors --ignore-certificate-errors --locales-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/locales --resources-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins --user-agent="Mozilla/5.0 (Windows NT 6.1; Unity 3D; ZFBrowser 2.1.0; Genshin Impact 3.4.0_12498014_12591909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.0 Safari/537.36" --lang=en-US --user-data-dir="C:\users\kaputschi\AppData\Local\CEF\User Data" --log-file="C:\users\kaputschi\AppData\LocalLow/miHoYo/Genshin Impact/output_log.txt" --mojo-platform-channel-handle=912 --field-trial-handle=676,i,3138527298811654155,16057900367044433095,131072 --disable-features=CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:8]
	00000404    0
	00000428    0
	0000042c    0
	00000434   -2
	00000438    0
	0000043c    0
00000408 ZFGameBrowser.exe
	[Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/ZFGameBrowser.exe --type=utility --utility-sub-type=network.mojom.NetworkService --lang=en-US --service-sandbox-type=none --no-sandbox --ignore-certificate-errors --ignore-certificate-errors --locales-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/locales --resources-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins --user-agent="Mozilla/5.0 (Windows NT 6.1; Unity 3D; ZFBrowser 2.1.0; Genshin Impact 3.4.0_12498014_12591909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.0 Safari/537.36" --lang=en-US --user-data-dir="C:\users\kaputschi\AppData\Local\CEF\User Data" --log-file="C:\users\kaputschi\AppData\LocalLow/miHoYo/Genshin Impact/output_log.txt" --mojo-platform-channel-handle=960 --field-trial-handle=676,i,3138527298811654155,16057900367044433095,131072 --disable-features=CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:8]
	0000040c    0
	00000444    0
	00000448    0
	00000454    0
	00000460    0
	00000464    0
	00000468   -2
	000004e8    0
	00000474    0
00000b50 (D) Z:\mnt\Extern\GenshinImpact\game\GenshinImpact_Data\Plugins\ZFGameBrowser.exe
	[Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/ZFGameBrowser.exe --type=renderer --locales-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/locales --resources-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins --user-agent="Mozilla/5.0 (Windows NT 6.1; Unity 3D; ZFBrowser 2.1.0; Genshin Impact 3.4.0_12498014_12591909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.0 Safari/537.36" --user-data-dir="C:\users\kaputschi\AppData\Local\CEF\User Data" --no-sandbox --autoplay-policy=no-user-gesture-required --log-file="C:\users\kaputschi\AppData\LocalLow/miHoYo/Genshin Impact/output_log.txt" --lang=en-US --device-scale-factor=1 --num-raster-threads=3 --enable-main-frame-before-activation --renderer-client-id=21 --launch-time-ticks=12291888104 --mojo-platform-channel-handle=720 --field-trial-handle=676,i,3138527298811654155,16057900367044433095,131072 --disable-features=CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:1]
	00000b54    0 <==
	00000b58    0
	00000b5c    0
	00000b64   -2
	00000b68    1
	00000b6c    0
	00000b70    0
	00000b78    0
	00000b7c    0
	00000b80    1
	00000b84    0
	00000b88    0
	00000b8c    0
	00000b90    0
	00000b94   -2
	000006a8    0
	000006cc    0
	000006d4    0
	000006b8    0
	000006d0    0
	000006a4    0
00000600 ZFGameBrowser.exe
	[Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/ZFGameBrowser.exe --type=renderer --locales-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins/locales --resources-dir-path=Z:/mnt/Extern/GenshinImpact/game/GenshinImpact_Data/Plugins --user-agent="Mozilla/5.0 (Windows NT 6.1; Unity 3D; ZFBrowser 2.1.0; Genshin Impact 3.4.0_12498014_12591909) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.0 Safari/537.36" --user-data-dir="C:\users\kaputschi\AppData\Local\CEF\User Data" --no-sandbox --autoplay-policy=no-user-gesture-required --log-file="C:\users\kaputschi\AppData\LocalLow/miHoYo/Genshin Impact/output_log.txt" --lang=en-US --device-scale-factor=1 --num-raster-threads=3 --enable-main-frame-before-activation --renderer-client-id=22 --launch-time-ticks=12533964542 --mojo-platform-channel-handle=660 --field-trial-handle=676,i,3138527298811654155,16057900367044433095,131072 --disable-features=CalculateNativeWinOcclusion,WinUseBrowserSpellChecker /prefetch:1]
	00000604    0
	0000060c    0
	00000610    0
	00000618   -2
	0000061c    1
	00000620    0
	00000624    0
	00000630    0
	00000634    1
	00000638    0
	00000648    0
	0000064c    0
	00000650    0
	0000069c   -2
	00000430    0
000006c8 explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	000006b0    0
	000006d8    0
	00000338    0
00000294 tabtip.exe
	["C:\windows\system32\tabtip.exe"]
	0000029c    0
	000006a0    0
	0000038c    0
System information:
    Wine build: wine-5.12-15601-g091f6fe77fd (Staging)
    Platform: x86_64
    Version: Windows 10
    Host system: Linux
    Host version: 6.0.12-76060006-generic
`

### Reproduction Steps

1. Open messages
2. Select Paimons-Poll for 100 Primogems
3. Click on the poll redirect
4. :(

**Comment by Mar0xy** [comment]
This is an issue with WINE that existed for years and can not be fixed by us nor is related to us. To use polls and minigames we recommended to find the URLs to their respective web pages and using your browser.
