### ISSUE TITLE
[Feature Request]: install location on sd card

### ISSUE THREAD

**Issue by Proptr** [an-anime-team/an-anime-game-launcher#68]
### What the feature is suppose to do

Install the game on a sd card

### Describe the reason behind the request

It always gives me error when using advanced installation so it would be better if i could choose the sd card as the install location

**Comment by chicco-carone** [comment]
just make a symlink from the game's files to the sd card

**Comment by Mar0xy** [comment]
Outdated as of Release 3.0.0 due to complete rewrite of launcher
