### ISSUE TITLE
[Issue]: I installed dual requirements but I still got 'Requirement not installed'

### ISSUE THREAD

**Issue by unknown10777** [an-anime-team/an-anime-game-launcher#69]
### Distro

Kali

### Installation Type

AppImage

### Describe the issue

![image](https://user-images.githubusercontent.com/83267603/221332237-56df0667-5a38-4b94-af65-5263bd6e6091.png)
![image](https://user-images.githubusercontent.com/83267603/221332259-23c61fb6-9d63-48c1-880d-9576954b0308.png)
and reshade-shaders have installed for this game executable.

### Reproduction Steps

1) double click AppImage
2) download everything needed
3) issue reproduced

**Comment by Mar0xy** [comment]
Outdated as of Release 3.0.0 due to complete rewrite of launcher
