### ISSUE TITLE
libbz2.so not found

### ISSUE THREAD

**Issue by AlphaCraft9658** [an-anime-team/an-anime-game-launcher#71]
When trying to launch the new version (3.0.0) on Fedora KDE 37 I get this error:
`./anime-game-launcher: error while loading shared libraries: libbz2.so.1.0: cannot open shared object file: No such file or directory`
How can I install the dependency, or how can I fix the issue? Why isn't the launcher being distributed as an appimage anymore?

**Comment by Mar0xy** [comment]
The Flatpak superseded the Appimage with the rewrite as that is the recommended way now.

The error you provided usually happens if bzip2 is missing on the system or if the binary was compiled with a newer version of bzip2

**Comment by AlphaCraft9658** [comment]
> The Flatpak superseded the Appimage with the rewrite as that is the recommended way now.
> 
> The error you provided usually happens if bzip2 is missing on the system or if the binary was compiled with a newer version of bzip2

bzip2 is installed. What can I do then? Should I install an older version?

**Comment by Mar0xy** [comment]
There are RPM builds on opensuse (listed in README) I am currently working on 3.0.0 release on the AAGL package so you could wait till it releases there

**Comment by AlphaCraft9658** [comment]
> There are RPM builds on opensuse (listed in README) I am currently working on 3.0.0 release on the AAGL package so you could wait till it releases there

Okay. Maybe I'll install it via the RPM then. For now I can used my self-compiled version. After finding out the missing rust packages for the compilation, I ran `cargo build --release`. It works well for now. Maybe you could also update the README that people should use the `--release` flag when building a non-test build for personal use.

**Comment by Mar0xy** [comment]
RPM Package is now built you can get it here https://build.opensuse.org/package/binaries/home:Maroxy:AAT-Apps/AAGL/Fedora_37

or add the repo itself https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/Fedora_37/

**Comment by AlphaCraft9658** [comment]
> RPM Package is now built you can get it here https://build.opensuse.org/package/binaries/home:Maroxy:AAT-Apps/AAGL/Fedora_37
> 
> or add the repo itself https://download.opensuse.org/repositories/home:/Maroxy:/AAT-Apps/Fedora_37/

The public key of that package is not installed. The GPG-Check failed.

**Comment by Mar0xy** [comment]
> The public key of that package is not installed

Nothing I can do about as they get automatically built by their build services.
