### ISSUE TITLE
FPS Unlocker not starting in 3.0.0

### ISSUE THREAD

**Issue by AlphaCraft9658** [an-anime-team/an-anime-game-launcher#73]
I started the game through the new version of the launcher, but the FPS unlocker doesn't work. It is enabled in the settings.

EDIT: It doesn't save the FPS I have set in the settings.

**Comment by krypt0nn** [comment]
Re-open if you still face this issue, or better ask it in our discord server

**Comment by AlphaCraft9658** [comment]
The FPS-Unlocker is another third-party tool, which should technically work with the launcher. Maybe by launching it with some flags. I don't exactly know how it works, but I would really appreciate if FPS-Unlocking worked in any way.
