### ISSUE TITLE
undefined symbol adw_about_window_set_issue_url

### ISSUE THREAD

**Issue by Ilia1** [an-anime-team/an-anime-game-launcher#74]
After running latest native version 3.0.1 I get error on Ubuntu 22.04.2
```
./anime-game-launcher: symbol lookup error: ./anime-game-launcher: undefined symbol: adw_about_window_set_issue_url, version LIBADWAITA_1_0
```

**Comment by Mar0xy** [comment]
Please use the flatpak if using Ubuntu as Ubuntu does not have the required library versions to run just the binary.
