### ISSUE TITLE
Add a tooltip to clarify what "Integer Scaling" means

### ISSUE THREAD

**Issue by zeGolem** [an-anime-team/an-anime-game-launcher#79]
Working on the French translations for the launcher. 
In "Preferences" -> "Enhancements" -> "Gamescope", there isn't a clean way to translate "Integer Scaling", and I think it'd be better to have a small text explaining what it does, like there is in the main preferences window.

If this is only a problem for the French translation, I'll leave it as is, but i do think it'd be better to clear things up for everyone!

**Comment by krypt0nn** [comment]
Done in f8c457b6995d1e4dabbe1a7ccf9d8cdc0f448297
