### ISSUE TITLE
Main window doesn't have a title or icon when using the classic appearence

### ISSUE THREAD

**Issue by zeGolem** [an-anime-team/an-anime-game-launcher#80]
This means the window doesn't show up properly in the system taskbar/icon view of most non-gnome desktop (see the 3rd item in the screenshot). This may also cause issues for screenreader users.

![Screenshot of the icon view in AwesomeWM](https://user-images.githubusercontent.com/40790374/222959657-e62f930b-a37b-44ff-bd41-05ae429eec43.png)

**Comment by Mar0xy** [comment]
Can confirm this also breaks in my taskbar and actually makes the launcher not show up at all in it
