### ISSUE TITLE
Dxvk 2.1 not actually applying

### ISSUE THREAD

**Issue by Reireiyan** [an-anime-team/an-anime-game-launcher#86]
dxvk 2.1 is not actually being used when selected, it instead uses v2.0. I have DXVK_HUD with the compiler option in the environment variables set, so it's pretty obvious that it's not using 2.1, because 2.1 actually shows a compile percentage from 1% to 100%. Older versions of dxvk do not show the compile percentage, plus it shows up as 2.0 with mangohud even though 2.1 is selected. The screenshot is of the game launched via Lutris with DXVK 2.1 compiling shaders. This is an issue because, for me, the game performs best with DXVK 2.1, but I don't want to launch the game through Lutris; I want to use the anime game launcher. ![Screenshot_20230305_201402](https://user-images.githubusercontent.com/62414119/222995320-e241b3e9-3bb4-4661-9621-2322fa83aceb.png)

**Comment by krypt0nn** [comment]
Just to clarify, did you select DXVK 2.1after downloading? Because currently launcher doesn't apply it if you didn't choose it. And it works well to me

**Comment by Reireiyan** [comment]
> Just to clarify, did you select DXVK 2.1 after downloading? Because currently launcher doesn't apply it if you didn't choose it. And it works well to me

Yes, I did select it, but whenever I go to launch the game, it still shows DXVK 2.0. being used, I even uninstalled all the other DXVK versions, and somehow it still says DXVK 2.1, even though 2.1 is the only one installed and selected.
![Screenshot_20230306_025658](https://user-images.githubusercontent.com/62414119/223040163-5679c969-e38f-4653-b1ea-9178952aef82.png)

**Comment by krypt0nn** [comment]
Well, don't know, applying works fine to me

![image](https://user-images.githubusercontent.com/29639507/223230912-fe07e2da-6230-48f0-aab4-71324f5a1b34.png)

**Comment by Reireiyan** [comment]
I really don't get what is happening with this launcher after removing everything and reinstalling it entirely; it now refuses to use my GPU and just wants the game to run on my integrated GPU. What the heck? I give up. I'll just use the launcher to update and patch the game, then Lutris with the launcher. bat as the executable
![Screenshot_20230306_174126](https://user-images.githubusercontent.com/62414119/223239460-674c2133-e5b7-4b58-8997-dd6a8b9573a7.png)

**Comment by Reireiyan** [comment]
I know this is closed, but I came back to say whatever happened after the latest updates to the launcher fixed the 2.1 not applying issue and every other issue that was happening with the launcher. Everything works now.

**Comment by krypt0nn** [comment]
Not actually everything. I manage to create new bugs every time I fix the old ones 😃
