### ISSUE TITLE
[Issue]: Mouse cursor invisible issue when switching workspaces if running the game

### ISSUE THREAD

**Issue by c02y** [an-anime-team/an-anime-game-launcher#9]
### Distro

Arch Linux 5.19.5-zen1-1-zen + i3 v4.20.1

### Installation Type

AUR

### Describe the issue

I use i3, (using picom or not doesn't matter here), when I play the fullscreen game in i3's another workspace, no mouse cursor visible most of the time since I use xbox wireless controller, if I switch focus to other program such as web browser in another workspace, the mouse cursor is invisible, I have to do something to the focused window to make the mouse cursor visible again such as switching focus to a third workspace where GI is not in and switching focus back, or togging the focused window floating on and off.

This issue is annoying since I do this a lot like switching focus to the web browser searching for something.

### Reproduction Steps

I'm not sure other people can reproduction this.

Just asking if other people have this issue as well or know how to fix it. Thanks.

**Comment by Mar0xy** [comment]
The game generally doesn't play nice if you switch workspaces and is mostly advised against while playing.

If you need to search for something I would recommend using a phone or if you have another monitor around to use another monitor for something like the browser.

You also have the option of trying a proton runner or virtual desktop to fix it but I don't know how succesfull that will be.

**Comment by Mar0xy** [comment]
Closed as stale due to no update for almost 2 weeks

**Comment by c02y** [comment]
This is resolved long time ago, I just forgot to add a reply here.

Solution: Check `borderless_window` in Settings of the launcher, the mouse cursor will work fine.
