### ISSUE TITLE
Failed to launch game. Telemetry is not disabled

### ISSUE THREAD

**Issue by feddevanderlist** [an-anime-team/an-anime-game-launcher#96]
I can't play the game anymore because of this. It just won't launch.
I tried to find something in settings but that doesn't work.
Repaired the installation too. But that didn't fix it
Log attached
[debug.log](https://github.com/an-anime-team/an-anime-game-launcher/files/10920912/debug.log)

**Comment by krypt0nn** [comment]
Update `/etc/hosts` file with these lines:

```
# Genshin logging servers (do not remove!)
0.0.0.0 sg-public-data-api.hoyoverse.com
0.0.0.0 log-upload-os.hoyoverse.com

# Some old global logging servers
0.0.0.0 log-upload-os.mihoyo.com
0.0.0.0 overseauspider.yuanshen.com

# Optional Unity proxy/cdn servers
0.0.0.0 prd-lender.cdp.internal.unity3d.com
0.0.0.0 thind-prd-knob.data.ie.unity3d.com
0.0.0.0 thind-gke-usc.prd.data.corp.unity3d.com
0.0.0.0 cdp.cloud.unity3d.com
0.0.0.0 remote-config-proxy-prd.uca.cloud.unity3d.com
```

**Comment by feddevanderlist** [comment]
> Update `/etc/hosts` file with these lines:
> 
> ```
> # Genshin logging servers (do not remove!)
> 0.0.0.0 sg-public-data-api.hoyoverse.com
> 0.0.0.0 log-upload-os.hoyoverse.com
> 
> # Some old global logging servers
> 0.0.0.0 log-upload-os.mihoyo.com
> 0.0.0.0 overseauspider.yuanshen.com
> 
> # Optional Unity proxy/cdn servers
> 0.0.0.0 prd-lender.cdp.internal.unity3d.com
> 0.0.0.0 thind-prd-knob.data.ie.unity3d.com
> 0.0.0.0 thind-gke-usc.prd.data.corp.unity3d.com
> 0.0.0.0 cdp.cloud.unity3d.com
> 0.0.0.0 remote-config-proxy-prd.uca.cloud.unity3d.com
> ```

Those are already in my `/etc/hosts/` I just replaced them with yours. Rebooted and still the same error.

**Comment by krypt0nn** [comment]
Then disable any running local server

**Comment by feddevanderlist** [comment]
> Then disable any running local web server

Welp, I didn't know that a server was still up and running. This fixed it. Thanks :)
