### ISSUE TITLE
Launcher logo in launcher seems missing

### ISSUE THREAD

**Issue by little-sheepycn** [an-anime-team/an-anime-game-launcher#98]
I use Manjaro Linux (stable),and I installed the launcher in AUR.The logo outside the launcher showed up correctly but they do not display in launcher.
![图片](https://user-images.githubusercontent.com/57757447/223737060-85e79613-a548-4418-b9db-0b11592a3d02.png)
![图片](https://user-images.githubusercontent.com/57757447/223737224-660c7c64-d7e3-449f-8715-842ff2947057.png)

![图片](https://user-images.githubusercontent.com/57757447/223737404-aad162a8-ce55-449c-8bf6-6a02e7fea4cb.png)

![图片](https://user-images.githubusercontent.com/57757447/223737589-9af0b14d-fe55-419f-985a-f88062838e96.png)

**Comment by Mar0xy** [comment]
This happens due to the icon being named incorrectly during install as it it's name is suppose to be moe.launcher.an-anime-game-launcher but the AUR package most likely names it differently.
